### ISSUE TITLE
UpdateReportedPropertiesAsync throws IotHubException after network connection lost/restored

### ISSUE THREAD

**Issue by joeax** [Azure/azure-iot-sdk-csharp#1056]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
Windows 10 Desktop x64
- **Application's .NET Target Framework :** <NETVERSION> 
netcoreapp2.2
- **Device:** <DEVICETYPE> 
Laptop
- **SDK version used:** <VERSION> 
Microsoft.Azure.Devices.Client 1.21.0

## Description of the issue:

Steps to repro:

1. Create new TwinCollection class, set a property
2. Purposefully cut network by going into airplane mode
3. Attempt to call UpdateReportedPropertiesAsync(), get IotCummunicationException after timeout
4. Restore network connection
5. Attempt to call UpdateReportedPropertiesAsync() again with same object.

It appears that once this happens, DeviceClient goes into some corrupt state. Instantiating a new DeviceClient is the only resolution.

## Code sample exhibiting the issue:

```
private bool _running = true;

private async Task TestTwinUpdate()
{
    TwinCollection collection = new TwinCollection();
    collection["foo"] = "12345";
    while (_running)
    {
        try
        {
            // pass 1: switch to airplane mode
            // pass 2: restore network
            await _deviceClient.UpdateReportedPropertiesAsync(collection);
        }
        catch (Exception ex)
        {
            // during pass 1: IotHubCommunicationException connection error (this is expected)
            // during pass 2: IotHubException (not good)
        }
        finally
        {
            Thread.Sleep(60_000);
        }
    }
}
```

## Console log of the issue:

```
{Microsoft.Azure.Devices.Client.Exceptions.IotHubException: request 516fc858-d17d-4f1d-94d6-63ef2977e753 returned status 400
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<>c__DisplayClass78_0.<SendTwinRequestAsync>b__0(Message possibleResponse)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendTwinRequestAsync(Message request, String rid, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass25_0.<<SendTwinPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
```

**Comment by timtay-microsoft** [comment]
@joeax are you still seeing this issue in the latest release?

**Comment by joeax** [comment]
Yes, it appears to be fixed. I updated to 1.21.1 and I no longer see the issue. Thanks!

**Comment by timtay-microsoft** [comment]
Great! I'll go ahead and close this issue, then

**Comment by az-iot-builder-01** [comment]
@CIPop, @joeax, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
