### ISSUE TITLE
key must be base64 encoded

### ISSUE THREAD

**Issue by interfacemirror** [Azure/azure-iot-sdk-csharp#1084]
- **OS, version, SKU and CPU architecture used:** <VERSION>  Window 10, C# .NET, x64
- **Application's .NET Target Framework :** .NET Core 3.0 and .NET Core 2.2

## Description of the issue:
I am using the sample solution provided by Microsoft on GitHub. After following the documentation, I see the exception "key must be base64 encoded". When I decode the key using UTF8, Unicode and ASCII, I get CONNECT failed: RefusedNotAuthorized
## Code sample exhibiting the issue:

```
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

//This is the code that sends messages to the IoT Hub for testing the routing as defined
//  in this article: https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-routing
//The scripts for creating the resources are included in the resources folder in this
//  Visual Studio solution. 

using Microsoft.Azure.Devices.Client;
using Newtonsoft.Json;
using System;
using System.Text;
using System.Threading.Tasks;

namespace SimulatedDevice
{
    class Program
    {
        private static DeviceClient s_deviceClient;
        private readonly static string s_myDeviceId = "******";
        private readonly static string s_iotHubUri = "******.azure-devices.net";
        // This is the primary key for the device. This is in the portal. 
        // Find your IoT hub in the portal > IoT devices > select your device > copy the key. 
        private static string s_deviceKey = "******";
        private static void Main(string[] args)
        {
// This line is added after exception "key must be base64 encoded"
            s_deviceKey = Convert.ToBase64String(ASCIIEncoding.Unicode.GetBytes(s_deviceKey));
            
            Console.WriteLine("Routing Tutorial: Simulated device\n"); 
            s_deviceClient = DeviceClient.Create(s_iotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey(s_myDeviceId, s_deviceKey), TransportType.Mqtt);
            SendDeviceToCloudMessagesAsync();
            Console.WriteLine("Press the Enter key to stop.");
            Console.ReadLine();
        }
        private static async void SendDeviceToCloudMessagesAsync()
        {
            double minTemperature = 20;
            double minHumidity = 60;
            Random rand = new Random();

            while (true)
            {
                double currentTemperature = minTemperature + rand.NextDouble() * 15;
                double currentHumidity = minHumidity + rand.NextDouble() * 20;

                string infoString;
                string levelValue;

                if (rand.NextDouble() > 0.7)
                {
                    if (rand.NextDouble() > 0.5)
                    {
                        levelValue = "critical";
                        infoString = "This is a critical message.";
                    }
                    else
                    {
                        levelValue = "storage";
                        infoString = "This is a storage message.";
                    }
                }
                else
                {
                    levelValue = "normal";
                    infoString = "This is a normal message.";
                }

                var telemetryDataPoint = new
                {
                    deviceId = s_myDeviceId,
                    temperature = currentTemperature,
                    humidity = currentHumidity,
                    pointInfo = infoString
                };
                var telemetryDataString = JsonConvert.SerializeObject(telemetryDataPoint);

                //set the body of the message to the serialized value of the telemetry data
                var message = new Message(Encoding.ASCII.GetBytes(telemetryDataString));
                message.Properties.Add("level", levelValue);

                await s_deviceClient.SendEventAsync(message);
                Console.WriteLine("{0} > Sent message: {1}", DateTime.Now, telemetryDataString);

                await Task.Delay(1000);
            }
        }
    }
}

## Console log of the issue:
Unhandled exception. Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at SimulatedDevice.Program.SendDeviceToCloudMessagesAsync() in C:\Users\jandost.khoso\Downloads\Routing\SimulatedDevice\Program.cs:line 82
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

C:\Users\jandost.khoso\Downloads\Routing\SimulatedDevice\bin\Debug\netcoreapp3.0\SimulatedDevice.exe (process 23144) exited with code -532462766.
Press any key to close this window . . .

**Comment by prmathur-microsoft** [comment]
What tool are you using to obtain device key?

**Comment by interfacemirror** [comment]
@prmathur there is no mention of device key generation in the tutorial. The documentation only says to use the key from azure portal setting.

**Comment by timtay-microsoft** [comment]
The DeviceAuthenticationWithRegistrySymmetricKey class is used for devices authenticating using symmetric keys after being provisioned by DPS. The symmetric key that the DeviceAuthenticationWithRegistrySymmetricKey expects is not the device's symmetric key, but the DPS enrollment's symmetric key. Based on your sample code, you don't seem to be using DPS, so you are using the wrong API to build your device client

If you are not using DPS to create your device, we recommend using this device client constructor:

```
string connectionString = ""; //get this from portal > IoT devices > select your device > copy the connectionstring, not the key
DeviceClient.CreateFromConnectionString(connectionString);
```

**Comment by interfacemirror** [comment]
Hello

Thanks for the clarification. In this case, I believe the best would be to
add this description in the documentation as well since I was following the
same steps as described in the documentation.

Regards,
Jandost Khoso

**Comment by timtay-microsoft** [comment]
Alright, since this was an issue with the documentation, and not the SDK, I'm going to close this issue

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @interfacemirror, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
