### ISSUE TITLE
AMQP transport exception with provisioning device with X509 cert using X509Sample project code

### ISSUE THREAD

**Issue by crpietschmann** [Azure/azure-iot-sdk-csharp#1109]
I'm getting the following exception when I try to run the `/provisioning/Samples/device/X509Sample` project with a certificate and .pfx I generated using OpenSSL. I haven't changed any of the code for the sample app.

https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/provisioning/Samples/device/X509Sample

Any direction on fixing this issue would be greatly appreciated. Thanks!

```
*****
Found certificate: E7D3831605D817D3FAE5E84AD1F22AEB36EC225A O=Internet Widgits Pty Ltd, S=Some-State, C=AU; PrivateKey: True
Using certificate E7D3831605D817D3FAE5E84AD1F22AEB36EC225A O=Internet Widgits Pty Ltd, S=Some-State, C=AU
RegistrationID = 
ProvisioningClient RegisterAsync . . . Unhandled exception. Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: AMQP transport exception
 ---> Microsoft.Azure.Amqp.AmqpException: The link address '0ne00090436/registrations/' did not match any of the expected formats.
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientLink.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.CreateLinksAsync(AmqpClientConnection connection, String linkEndpoint, String productInfo)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.ProvisioningDeviceClientSample.RunSampleAsync() in /Users/Chris/Desktop/IoT/azure-iot-samples-csharp-master/provisioning/Samples/device/Common/ProvisioningDeviceClientSample.cs:line 31
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.Program.Main(String[] args) in /Users/Chris/Desktop/IoT/azure-iot-samples-csharp-master/provisioning/Samples/device/X509Sample/Program.cs:line 74
```

**Comment by crpietschmann** [comment]
I updated the .csproj file to reference all the latest versions of the Nuget packages. This specific error went away, but a new exception came up...

Here's my .csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.21.1" />
    <PackageReference Include="Microsoft.Azure.Devices.Provisioning.Transport.Mqtt" Version="1.1.8" />
    <PackageReference Include="Microsoft.Azure.Devices.Provisioning.Transport.Amqp" Version="1.1.9" />
    <PackageReference Include="Microsoft.Azure.Devices.Provisioning.Transport.Http" Version="1.1.6" />
  </ItemGroup>

</Project>
```

Here's the new exception that is being thrown now by the application...

```
ChrisMacBookPro:l06 Chris$ dotnet run
Found certificate: 455ABE376C59E0EEBCBDAD6A18FDF22FD791D07A CN=build5nines.com, O=Internet Widgits Pty Ltd, L=Orlando, S=Florida, C=US; PrivateKey: True
Using certificate 455ABE376C59E0EEBCBDAD6A18FDF22FD791D07A CN=build5nines.com, O=Internet Widgits Pty Ltd, L=Orlando, S=Florida, C=US
RegistrationID = build5nines.com
Unhandled exception. System.FormatException: Invalid registrationId: The registration ID is alphanumeric, lowercase, and may contain hyphens
   at SymmetricKeySimulatedDevice.ProvisioningDeviceLogic.VerifyRegistrationIdFormat(String v) in /Users/Chris/Desktop/IoT/L06/Program.cs:line 178
   at SymmetricKeySimulatedDevice.ProvisioningDeviceLogic.RunAsync() in /Users/Chris/Desktop/IoT/L06/Program.cs:line 128
   at SymmetricKeySimulatedDevice.Program.Main(String[] args) in /Users/Chris/Desktop/IoT/L06/Program.cs:line 66
ChrisMacBookPro:l06 Chris$ dotnet run
Found certificate: 455ABE376C59E0EEBCBDAD6A18FDF22FD791D07A CN=build5nines.com, O=Internet Widgits Pty Ltd, L=Orlando, S=Florida, C=US; PrivateKey: True
Using certificate 455ABE376C59E0EEBCBDAD6A18FDF22FD791D07A CN=build5nines.com, O=Internet Widgits Pty Ltd, L=Orlando, S=Florida, C=US
RegistrationID = build5nines.com
ProvisioningClient RegisterAsync . . . Unhandled exception. Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: AMQP transport exception
 ---> Microsoft.Azure.Amqp.AmqpException: {"errorCode":401002,"trackingId":"c20f12f3-55ac-4196-9d01-e52ace9ef132","message":"IotHubUnauthorizedAccess","timestampUtc":"2019-11-10T14:17:30.0419405Z"}
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientLink.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.CreateLinksAsync(AmqpClientConnection connection, String linkEndpoint, String productInfo)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   at SymmetricKeySimulatedDevice.ProvisioningDeviceLogic.RunAsync() in /Users/Chris/Desktop/IoT/L06/Program.cs:line 131
   at SymmetricKeySimulatedDevice.Program.Main(String[] args) in /Users/Chris/Desktop/IoT/L06/Program.cs:line 66
```

On to troubleshooting this next issue.

P.S. This might, or might not, be related to the SDK... The version mismatch issue throwing the first exception I got certainly was related to the SDK. I'll update where when I figure out the fix for this next exception. Hopefully this all helps someone else out!

**Comment by crpietschmann** [comment]
I've regenerated my x509 certificates fresh again, and now I'm getting the below error. It seems it's authenticating with DPS fine now, but there's an issue with the SDK connecting over AMQP.

```
ChrisMacBookPro:X509Sample Chris$ dotnet run
Enter the PFX password for certificate1.pfx:
*****
Found certificate: 5E464E878C8DDD2DCC83343E830C1BDBB65B7EE7 O=Internet Widgits Pty Ltd, S=Some-State, C=AU; PrivateKey: True
Using certificate 5E464E878C8DDD2DCC83343E830C1BDBB65B7EE7 O=Internet Widgits Pty Ltd, S=Some-State, C=AU
RegistrationID = 
ProvisioningClient RegisterAsync . . . Unhandled exception. Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: AMQP transport exception
 ---> Microsoft.Azure.Amqp.AmqpException: The link address '0ne0009354C/registrations/' did not match any of the expected formats.
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientLink.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.CreateLinksAsync(AmqpClientConnection connection, String linkEndpoint, String productInfo)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.ProvisioningDeviceClientSample.RunSampleAsync() in /Users/Chris/Desktop/IoT/azure-iot-samples-csharp-master/provisioning/Samples/device/Common/ProvisioningDeviceClientSample.cs:line 31
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.Program.Main(String[] args) in /Users/Chris/Desktop/IoT/azure-iot-samples-csharp-master/provisioning/Samples/device/X509Sample/Program.cs:line 74
```

When using HTTP protocol, the following Exception is thrown:

```
ChrisMacBookPro:X509Sample Chris$ dotnet run
Enter the PFX password for certificate1.pfx:
*****
Found certificate: 5E464E878C8DDD2DCC83343E830C1BDBB65B7EE7 O=Internet Widgits Pty Ltd, S=Some-State, C=AU; PrivateKey: True
Using certificate 5E464E878C8DDD2DCC83343E830C1BDBB65B7EE7 O=Internet Widgits Pty Ltd, S=Some-State, C=AU
RegistrationID = 
ProvisioningClient RegisterAsync . . . Unhandled exception. Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransport
Exception
 ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.RuntimeRegistration.RegisterDeviceWithHttpMessagesAsync(String re
gistrationId, String idScope, DeviceRegistration deviceRegistration, Nullable`1 forceRegistration, Dictionary`2 customHeaders
, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.RuntimeRegistrationExtensions.RegisterDeviceAsync(IRuntimeRegistr
ation operations, String registrationId, String idScope, DeviceRegistration deviceRegistration, Nullable`1 forceRegistration,
 CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerHttp.RegisterAsync(ProvisioningTransp
ortRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerHttp.RegisterAsync(ProvisioningTransp
ortRegisterMessage message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.ProvisioningDeviceClientSample.RunSampleAsync() in /Users/Chris/Des
ktop/IoT/azure-iot-samples-csharp-master/provisioning/Samples/device/Common/ProvisioningDeviceClientSample.cs:line 31
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.Program.Main(String[] args) in /Users/Chris/Desktop/IoT/azure-iot-s
amples-csharp-master/provisioning/Samples/device/X509Sample/Program.cs:line 74
```

**Comment by timtay-microsoft** [comment]
Did you create an x509 enrollment in your DPS instance before running this sample? And are you using the same registrationId in the sample that you assigned this enrollment?

**Comment by crpietschmann** [comment]
@timtay-microsoft  Yes, I created a Group Enrollment in DPS using the Intermediate Certificate option. Since I don't have a CA certificate in this case, I need to do Intermediate Certificate since that doesn't require proof of possession to be done. And, I didn't set a Registration ID, as that is only done for Individual Enrollment.

Thanks! I really appreciate you taking a look at this. I'm excited to get this resolved.

**Comment by crpietschmann** [comment]
I found that this transport exception will occur if the Common Name "CN=" value within the device x.509 certificate does not match the Group Enrollment name within DPS. The documentation seems to be a bit short in regards to the x.509 CA Certificate chain, and assumes you know OpenSSL and CA Certificates already.

**Comment by az-iot-builder-01** [comment]
@crpietschmann, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by crpietschmann** [comment]
Also, for reference, if you follow the instructions and helper script at the below link, you will be able to generate the appropriate x.509 CA Certificates necessary for DPS Group Enrollment to work:

<https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md>
