### ISSUE TITLE
IotHubCommunicationException: Transient network error occurred, please retry.

### ISSUE THREAD

**Issue by ChangeTheCode** [Azure/azure-iot-sdk-csharp#1138]
I get always the log about "IotHubCommunicationException: Transient network error occurred, please retry."  After starting my application, but after I got the error it looks like everything works fine. This error looks on windows and linux little bit different (see below). I also tried it from different networks so I can exclude it can be a firewall issue. 

Is this error critical or what could be the reason for this error? 

- **Application's .NET Target Framework :**
dotnet core 3.0 preview 7  
- **Device:** 
Laptop (Windows 10)  Raspberry PI2 (debian) 
- **SDK version used:** 
Microsoft.Azure.Devices.Client version 1.21.2 (also used 1.19.0) 

## Description of the issue:
If I start my program which tries to send data to the iot hub i got this exception one or more time but then everything works fine. 

## Console log of the issue:
**Stack trace from windows**
"Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SubscribeAsync(IChannelHandlerContext context, SubscribePacket packetPassed)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ProcessConnectAckAsync(IChannelHandlerContext context, ConnAckPacket packet)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ProcessMessage(IChannelHandlerContext context, Packet packet)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SubscribeAsync(IChannelHandlerContext context, SubscribePacket packetPassed)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SubscribeTwinResponsesAsync()
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass19_0.<<EnableMethodsAsync>b__0>d.MoveNext()

**Stack trace from linux**
"Iot.Connector.AzureIoTHub.AzureIotHubClient"."TrySend" Exception happened, handled in app code. "Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Unable to open transport
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at Microsoft.Azure.Devices.Client.Transport.TransportHandler.<>c__DisplayClass3_0.<HandleTimeoutCancellation>b__1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(Boolean explicitOpen, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.TryOpenPrioritizedTransportsAsync(Boolean explicitOpen, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at Microsoft.Azure.Devices.Client.Transport.GateKeeperDelegatingHandler.RecoverConnections(Object o, ConnectionType connectionType, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.<>c__DisplayClass71_0.<<OnConnectionClosed>b__0>d.MoveNext()
   at Iot.Connector.AzureIoTHub.AzureIotHubClient.CreateAzureDeviceClient(String connectionString)
   at Iot.Connector.AzureIoTHub.AzureIotHubClient.RefreshDeviceClient(CancellationToken ct)
   at Iot.Connector.AzureIoTHub.AzureIotHubClient.WaitForDeviceClientAsync(CancellationToken tok)
   at Iot.Connector.AzureIoTHub.AzureIotHubClient.Send(AzureIotHubBatch msg, CancellationToken tok)
   at Iot.Connector.AzureIoTHub.AzureIotHubClient.TrySend(IEnumerable`1 msgs, CancellationToken ct)"

**Comment by davilu** [comment]
@ChangeTheCode Thanks for report the issue. The exceptions you saw indicates there was exception trying open socket connection. SDK has retry logic to handle `IOException` so it recovered, that's why everything works fine to you.

**Comment by ChangeTheCode** [comment]
this issue is solved. This was an issue in the implementation. The application created multiple times a new DeviceClient which is not intended from the IoT Hub. 
The IoT Hub is closing a connection if to different connection are opened from the same device id

**Comment by az-iot-builder-01** [comment]
@davilu, @ChangeTheCode, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
