### ISSUE TITLE
Breaking Change: New timeout exception thrown by RegistryManager.GetDeviceAsync() when configured with proxy

### ISSUE THREAD

**Issue by and-rewsmith** [Azure/azure-iot-sdk-csharp#1228]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
OS: Ubuntu 18.04 amd64

- **Application's .NET Target Framework :** 2.1 
- **Device:** Azure VM 
- **SDK version used:** 
    PackageReference Include="Microsoft.Azure.Devices" Version="1.18.4" 

## Description of the issue:

With the release of Microsoft.Azure.Devices v1.18.4, the ```RegistryManager.GetDeviceAsync(string deviceId)``` method will wait then throw a timeout exception when the device id is not registered. Previous versions would return null in this scenario.

I know there is a related change documented in the release changelog as:
"Fix proxy handling on HTTP for requests with per-request timeout."

I'm guessing this change was not intentional?

## Code sample exhibiting the issue:

```
namespace CSharpModule
{
    using System;
    using System.Net;
    using System.Threading.Tasks;
    using Microsoft.Azure.Devices;

    class Program
    {
        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        static async Task MainAsync()
        {
            Console.WriteLine("Testing RegistryManager device creation behind proxy.");

            string proxyString = "<YOUR PROXY>";
            WebProxy proxy = new WebProxy(proxyString);

            Console.WriteLine("Making registry manager with proxy");
            var settings = new HttpTransportSettings();
            settings.Proxy = proxy;
            IotHubConnectionStringBuilder builder = IotHubConnectionStringBuilder.Create("<YOUR CONNECTION STRING");
            RegistryManager rm = RegistryManager.CreateFromConnectionString(builder.ToString(), settings);

            Console.WriteLine("Getting or Creating device Identity.");
            Device device = await rm.GetDeviceAsync("test-device");
        }
    }
}
```

## Console log of the issue:

```
Testing RegistryManager device creation behind proxy.
Making registry manager with proxy
Getting or Creating device Identity.
Unhandled Exception: System.AggregateException: One or more errors occurred. (The operation was canceled.) ---> Microsoft.Azure.Devices.Common.Exceptions.IotHubException: The operation was canceled. ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpClientHelper.GetAsync[T](Uri requestUri, TimeSpan operationTimeout, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, Boolean throwIfNotFound, CancellationToken cancellationToken)
   at CSharpModule.Program.MainAsync() in /home/vsts/tmp-workdir/Program.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CSharpModule.Program.Main(String[] args) in /home/vsts/tmp-workdir/Program.cs:line 12
```

**Comment by drwill-ms** [comment]
Found the cause and issued a fix. We're releasing it tonight/tomorrow as 1.19.0

**Comment by az-iot-builder-01** [comment]
@and-rewsmith, @drwill-ms, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
