### ISSUE TITLE
ModuleClient configured with Mqtt_Tcp_Only fails to reconnect after edgeHub restart then never recovers

### ISSUE THREAD

**Issue by and-rewsmith** [Azure/azure-iot-sdk-csharp#1239]
- **OS, version, SKU and CPU architecture used:** <VERSION> 
OS: Ubuntu 18.04 amd64

- **Application's .NET Target Framework :** 2.1 
- **Device:** Local VM Ubuntu 18.04 
- **SDK version used:** 
    PackageReference Include="Microsoft.Azure.Devices" Version="1.22.0" 

## Description of the issue:

This problem can be reproduced consistently. 

Start edgeHub with one [SimulatedTemperatureSensor](https://github.com/Azure/iotedge/tree/release/1.0.9/edge-modules/SimulatedTemperatureSensor) configured with Mqtt_Tcp_Only TransportType. The module will successfully make the initial connection and start sending messages. If edgeHub is restarted, the ModuleClient.SendEventAsync() will hang then eventually timeout. This then crashes the module, and a new ModuleClient will get created and start operating as expected. 

To further test, I added a try/catch around the ModuleClient.SendEventAsync() to detect if ModuleClient would recover after its initial timeout. Unfortunately, ModuleClient will **never recover** and timeout after **all** subsequent SendEventAsync() calls.

## Code sample exhibiting the issue:

Run iotedge with one [SimulatedTemperatureSensor module](https://github.com/Azure/iotedge/tree/release/1.0.9/edge-modules/SimulatedTemperatureSensor) configured with Mqtt_Tcp_Only. Restart edgeHub and this timeout will occur. 

## Console log of the issue:

SimulatedTemperatureSensor logs:
```
[2020-02-15 00:55:29 : Starting Module
SimulatedTemperatureSensor Main() started.
Initializing simulated temperature sensor to send unlimited messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Information: Trying to initialize module client using transport type [Mqtt_Tcp_Only].
Information: Successfully initialized module client of transport type [Mqtt_Tcp_Only].
	02/15/2020 00:55:37> Sending message: 1, Body: [{"machine":{"temperature":21.842550837710757,"pressure":1.0959868042961622},"ambient":{"temperature":21.113807129028164,"humidity":26},"timeCreated":"2020-02-15T00:55:37.2835997Z"}]
	02/15/2020 00:55:42> Sending message: 2, Body: [{"machine":{"temperature":21.690755489603969,"pressure":1.0786936633726041},"ambient":{"temperature":21.083049474089893,"humidity":24},"timeCreated":"2020-02-15T00:55:42.4668453Z"}]
	02/15/2020 00:55:47> Sending message: 3, Body: [{"machine":{"temperature":22.425635379588062,"pressure":1.1624141571682602},"ambient":{"temperature":20.744062242211804,"humidity":26},"timeCreated":"2020-02-15T00:55:47.4837664Z"}]
	02/15/2020 00:55:52> Sending message: 4, Body: [{"machine":{"temperature":23.179604310160318,"pressure":1.248309351790416},"ambient":{"temperature":21.202862168058225,"humidity":26},"timeCreated":"2020-02-15T00:55:52.4897686Z"}]
	02/15/2020 00:55:57> Sending message: 5, Body: [{"machine":{"temperature":24.030921823010278,"pressure":1.345294891229019},"ambient":{"temperature":20.916567907862628,"humidity":25},"timeCreated":"2020-02-15T00:55:57.5045027Z"}]
	02/15/2020 00:56:02> Sending message: 6, Body: [{"machine":{"temperature":24.939889543428965,"pressure":1.4488481758336795},"ambient":{"temperature":21.327289221262227,"humidity":24},"timeCreated":"2020-02-15T00:56:02.5144359Z"}]
	02/15/2020 00:56:07> Sending message: 7, Body: [{"machine":{"temperature":24.752444687766229,"pressure":1.4274936986062792},"ambient":{"temperature":20.721239088206197,"humidity":26},"timeCreated":"2020-02-15T00:56:07.5217324Z"}]
	02/15/2020 00:56:12> Sending message: 8, Body: [{"machine":{"temperature":25.608009566603233,"pressure":1.5249631151826466},"ambient":{"temperature":21.217757588586657,"humidity":26},"timeCreated":"2020-02-15T00:56:12.5349811Z"}]
	02/15/2020 00:56:17> Sending message: 9, Body: [{"machine":{"temperature":26.835189167449805,"pressure":1.6647683861651676},"ambient":{"temperature":20.772503043651817,"humidity":24},"timeCreated":"2020-02-15T00:56:17.5426183Z"}]
	02/15/2020 00:56:22> Sending message: 10, Body: [{"machine":{"temperature":27.14881726920084,"pressure":1.7004981699089565},"ambient":{"temperature":20.799432544177133,"humidity":24},"timeCreated":"2020-02-15T00:56:22.5497244Z"}]
	02/15/2020 00:56:27> Sending message: 11, Body: [{"machine":{"temperature":28.042496446423463,"pressure":1.8023097217444453},"ambient":{"temperature":20.582763399967348,"humidity":24},"timeCreated":"2020-02-15T00:56:27.5575871Z"}]
	02/15/2020 00:56:32> Sending message: 12, Body: [{"machine":{"temperature":28.642500712136972,"pressure":1.8706646380915537},"ambient":{"temperature":21.454146881566452,"humidity":25},"timeCreated":"2020-02-15T00:56:32.5642275Z"}]
	02/15/2020 00:56:37> Sending message: 13, Body: [{"machine":{"temperature":29.191622266518706,"pressure":1.9332227898565615},"ambient":{"temperature":21.004060147099224,"humidity":26},"timeCreated":"2020-02-15T00:56:37.5745303Z"}]
	02/15/2020 00:56:42> Sending message: 14, Body: [{"machine":{"temperature":30.261794517869966,"pressure":2.0551411476054389},"ambient":{"temperature":21.017816035318102,"humidity":26},"timeCreated":"2020-02-15T00:56:42.5834034Z"}]
	02/15/2020 00:56:47> Sending message: 15, Body: [{"machine":{"temperature":31.27697162168425,"pressure":2.17079423538175},"ambient":{"temperature":21.19174452204804,"humidity":25},"timeCreated":"2020-02-15T00:56:47.5944871Z"}]
	02/15/2020 00:56:52> Sending message: 16, Body: [{"machine":{"temperature":31.296091642368626,"pressure":2.172972465586299},"ambient":{"temperature":21.320466894572817,"humidity":24},"timeCreated":"2020-02-15T00:56:52.6010552Z"}]
	02/15/2020 00:56:57> Sending message: 17, Body: [{"machine":{"temperature":32.401873601904079,"pressure":2.2989476255333763},"ambient":{"temperature":21.383266543915155,"humidity":24},"timeCreated":"2020-02-15T00:56:57.6078023Z"}]
	02/15/2020 00:57:02> Sending message: 18, Body: [{"machine":{"temperature":33.426974872791661,"pressure":2.4157313146218344},"ambient":{"temperature":20.9932989196355,"humidity":24},"timeCreated":"2020-02-15T00:57:02.6144732Z"}]
	02/15/2020 00:57:07> Sending message: 19, Body: [{"machine":{"temperature":33.789065967332135,"pressure":2.45698219880999},"ambient":{"temperature":21.491323972582503,"humidity":26},"timeCreated":"2020-02-15T00:57:07.6247203Z"}]
	02/15/2020 00:57:12> Sending message: 20, Body: [{"machine":{"temperature":33.64659539011614,"pressure":2.4407513735575348},"ambient":{"temperature":20.580683367364426,"humidity":24},"timeCreated":"2020-02-15T00:57:12.6344732Z"}]
	02/15/2020 00:57:17> Sending message: 21, Body: [{"machine":{"temperature":34.836046552092789,"pressure":2.5762584679599376},"ambient":{"temperature":20.780834525488707,"humidity":26},"timeCreated":"2020-02-15T00:57:17.6420423Z"}]
	02/15/2020 00:57:22> Sending message: 22, Body: [{"machine":{"temperature":35.933980521715235,"pressure":2.7013395531067985},"ambient":{"temperature":21.406859835566422,"humidity":25},"timeCreated":"2020-02-15T00:57:22.6483743Z"}]
	02/15/2020 00:57:27> Sending message: 23, Body: [{"machine":{"temperature":36.410277650300543,"pressure":2.7556012513000621},"ambient":{"temperature":20.667542164757634,"humidity":25},"timeCreated":"2020-02-15T00:57:27.6530741Z"}]
	02/15/2020 00:57:33> Sending message: 24, Body: [{"machine":{"temperature":36.410247620619018,"pressure":2.7555978301971029},"ambient":{"temperature":20.739897444024635,"humidity":24},"timeCreated":"2020-02-15T00:57:33.0570214Z"}]
	02/15/2020 00:57:38> Sending message: 25, Body: [{"machine":{"temperature":36.82147449328167,"pressure":2.8024464612599371},"ambient":{"temperature":20.661588595324005,"humidity":26},"timeCreated":"2020-02-15T00:57:38.4920916Z"}]

Unhandled Exception: System.AggregateException: One or more errors occurred. (The operation timed out.) ---> System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   at SimulatedTemperatureSensor.Program.SendEvents(ModuleClient moduleClient, Int32 messageCount, SimulatorParameters sim, CancellationTokenSource cts) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 217
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 96
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 37
```
## Logs from the SDK:
These logs are not from the same test run as the above error logs, however this was intentional as I couldn't get the SDK logs with the straightforward out-of-the-box SimulatedTemperatureSensor image. Nevertheless, these should be helpful.
```
2020-02-14 23:32:33.8908: Enter Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:33.8908: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method SendEventAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:33.8910: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method SendEventAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:33.8911: Exit Microsoft.Azure.Devices.Client.InternalClient method SendEventAsync with args: [temperatureOutput, Microsoft.Azure.Devices.Client.Message].
2020-02-14 23:32:33.8913: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method WriteAsync with args: [MqttIotHubAdapter#0, Microsoft.Azure.Devices.Client.Message].
2020-02-14 23:32:33.8913: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method SendMessageAsync with args: [MqttIotHubAdapter#0, Microsoft.Azure.Devices.Client.Message].
2020-02-14 23:32:33.8917: Info Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method SendMessageAsync id=24 qos=AtLeastOnce topic=devices/linux-amd-64/modules/tempSensor1/messages/events/%24.on=temperatureOutput&sequenceNumber=20&batchId=c0f54f7a-83e6-4c11-a968-5d5c51aa1093/.
2020-02-14 23:32:33.8917: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method SendMessageToServerAsync with args: [MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtLeastOnce, Duplicate=False, Retain=False]].
2020-02-14 23:32:33.8921: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method SendMessageToServerAsync with args: [MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtLeastOnce, Duplicate=False, Retain=False]].
2020-02-14 23:32:34.2260: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelRead with args: [MqttIotHubAdapter#0, PubAckPacket[Type=PUBACK, QualityOfService=AtMostOnce, Duplicate=False, Retain=False]].
2020-02-14 23:32:34.2260: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ProcessMessage with args: [MqttIotHubAdapter#0, PUBACK].
2020-02-14 23:32:34.2261: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ProcessAckAsync with args: [MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtLeastOnce, Duplicate=False, Retain=False]].
2020-02-14 23:32:34.2261: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method SendMessageAsync with args: [MqttIotHubAdapter#0, Microsoft.Azure.Devices.Client.Message].
2020-02-14 23:32:34.2261: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method WriteAsync with args: MqttIotHubAdapter#0.
2020-02-14 23:32:34.2262: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ProcessAckAsync with args: [MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtLeastOnce, Duplicate=False, Retain=False]].
2020-02-14 23:32:34.2262: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ProcessMessage with args: [MqttIotHubAdapter#0, PUBACK].
2020-02-14 23:32:34.2262: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelRead with args: MqttIotHubAdapter#0.
2020-02-14 23:32:34.2262: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelReadComplete with args: MqttIotHubAdapter#0.
2020-02-14 23:32:34.2262: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelReadComplete with args: MqttIotHubAdapter#0.
2020-02-14 23:32:34.2264: Exit Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:34.2264: Exit Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler method SendEventAsync with args: [Microsoft.Azure.Devices.Client.Message, System.Threading.CancellationToken].
2020-02-14 23:32:37.8614: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelReadComplete with args: MqttIotHubAdapter#0.
2020-02-14 23:32:37.8615: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelReadComplete with args: MqttIotHubAdapter#0.
2020-02-14 23:32:37.8931: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelInactive with args: MqttIotHubAdapter#0.
2020-02-14 23:32:37.8969: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ShutdownOnError with args: [MqttIotHubAdapter#0, System.Net.Sockets.SocketException (104): Connection reset by peer].
2020-02-14 23:32:37.9022: Info Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OnTransportDisconnected OnTransportDisconnected.
2020-02-14 23:32:37.9037: Info Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method WaitForTransportClosedAsync Client disconnected..
2020-02-14 23:32:37.9039: Associate: Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method InnerHandler  is Associated to Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.
2020-02-14 23:32:37.9040: Associate: Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method InnerHandler Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler is Associated to Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.
2020-02-14 23:32:37.9040: Info Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OnTransportClosedGracefully OnTransportClosedGracefully.
2020-02-14 23:32:37.9042: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ShutdownOnError with args: MqttIotHubAdapter#0.
2020-02-14 23:32:37.9043: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter method ChannelInactive with args: MqttIotHubAdapter#0.
2020-02-14 23:32:37.9052: Info Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler method HandleDisconnect Transport disconnected: unexpected..
2020-02-14 23:32:37.9053: Enter Microsoft.Azure.Devices.Client.RetryStrategyAdapter method RetryStrategyAdapter.ShouldRetry with args: [0, Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Exception of type 'Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException' was thrown.].
2020-02-14 23:32:37.9053: Exit Microsoft.Azure.Devices.Client.RetryStrategyAdapter method ShouldRetry with args: RetryStrategyAdapter.ShouldRetry.
2020-02-14 23:32:38.0055: Enter Microsoft.Azure.Devices.Client.InternalClient method OnConnectionStatusChanged with args: [Disconnected_Retrying, Communication_Error].
2020-02-14 23:32:38.0055: Exit Microsoft.Azure.Devices.Client.InternalClient method OnConnectionStatusChanged with args: [Disconnected_Retrying, Communication_Error].
2020-02-14 23:32:38.0081: Info Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler method HandleDisconnect Attempting to recover subscriptions..
2020-02-14 23:32:38.0081: Enter Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:38.0082: Enter Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method ProtocolRoutingDelegatingHandler.OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:38.0082: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:38.0094: Info Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method CreateChannelFactory Connecting to 172.18.0.4.
2020-02-14 23:32:39.0219: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:39.0220: Exit Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method ProtocolRoutingDelegatingHandler.OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:39.0234: Error Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync Exception caught: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel was not opened
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
2020-02-14 23:32:39.0236: Exit Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:39.0270: Enter Microsoft.Azure.Devices.Client.RetryStrategyAdapter method RetryStrategyAdapter.ShouldRetry with args: [0, Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel was not opened
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<HandleDisconnect>b__0>d.MoveNext()].
2020-02-14 23:32:39.0270: Exit Microsoft.Azure.Devices.Client.RetryStrategyAdapter method ShouldRetry with args: RetryStrategyAdapter.ShouldRetry.
2020-02-14 23:32:39.1332: Info Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler method HandleDisconnect Attempting to recover subscriptions..
2020-02-14 23:32:39.1333: Enter Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:39.1333: Enter Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method ProtocolRoutingDelegatingHandler.OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:39.1333: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:39.1342: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:39.1343: Exit Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method ProtocolRoutingDelegatingHandler.OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:39.1347: Error Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync Exception caught: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel was not opened
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
2020-02-14 23:32:39.1348: Exit Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:39.1351: Enter Microsoft.Azure.Devices.Client.RetryStrategyAdapter method RetryStrategyAdapter.ShouldRetry with args: [1, Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel was not opened
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<HandleDisconnect>b__0>d.MoveNext()].
2020-02-14 23:32:39.1351: Exit Microsoft.Azure.Devices.Client.RetryStrategyAdapter method ShouldRetry with args: RetryStrategyAdapter.ShouldRetry.
2020-02-14 23:32:39.2302: Enter Microsoft.Azure.Devices.Client.InternalClient method SendEventAsync with args: [temperatureOutput, Microsoft.Azure.Devices.Client.Message].
2020-02-14 23:32:39.2302: Enter Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler method SendEventAsync with args: [Microsoft.Azure.Devices.Client.Message, System.Threading.CancellationToken].
2020-02-14 23:32:39.2303: Exit Microsoft.Azure.Devices.Client.InternalClient method SendEventAsync with args: [temperatureOutput, Microsoft.Azure.Devices.Client.Message].
2020-02-14 23:32:40.1334: Info Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler method HandleDisconnect Attempting to recover subscriptions..
2020-02-14 23:32:40.1335: Enter Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:40.1335: Enter Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method ProtocolRoutingDelegatingHandler.OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:40.1335: Enter Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:40.1342: Exit Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler method OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:40.1342: Exit Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler method ProtocolRoutingDelegatingHandler.OpenAsync with args: System.Threading.CancellationToken.
2020-02-14 23:32:40.1346: Error Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync Exception caught: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel was not opened
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
2020-02-14 23:32:40.1347: Exit Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler method ExecuteWithErrorHandlingAsync with args: ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync.
2020-02-14 23:32:40.1350: Enter Microsoft.Azure.Devices.Client.RetryStrategyAdapter method RetryStrategyAdapter.ShouldRetry with args: [2, Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel was not opened
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<HandleDisconnect>b__0>d.MoveNext()].
```

**Comment by az-iot-builder-01** [comment]
@and-rewsmith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
