### ISSUE TITLE
AMQP: Link already attached in Session 0

### ISSUE THREAD

**Issue by thnk2wn** [Azure/azure-iot-sdk-csharp#1283]
- **OS, version, SKU and CPU architecture used:** Custom Debian based ARM 32 OS
- **Application's .NET Target Framework :** .NET Core 3.1.0
- **Device:**  Raspberry PI3 (essentially - custom)
- **SDK version used:** Microsoft.Azure.Devices.Client 1.22.0

## Description of the issue:

Error Variant 1 (MethodsReceiverLink):

<pre>
Microsoft.Azure.Devices.Client.Exceptions.IotHubException: error(condition:amqp:resource-locked,description:A link with name 'MethodsReceiverLink' is already attached in session 0.)
 ---> Microsoft.Azure.Amqp.AmqpException: A link with name 'MethodsReceiverLink' is already attached in session 0.
   at Microsoft.Azure.Amqp.AmqpSession.AttachLink(AmqpLink link)
   at Microsoft.Azure.Amqp.AmqpLink.AttachTo(AmqpSession session)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenReceivingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String correlationId, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenReceivingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String correlationId, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenMethodsReceiverLinkAsync(DeviceIdentity deviceIdentity, String correlationIdSuffix, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenMethodsReceiverLinkAsync(AmqpIoTSession amqpIoTSession, String correlationIdSuffix, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnableMethodsAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.EnableMethodsAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass19_0.<<EnableMethodsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableMethodsAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SetMethodDefaultHandlerAsync(MethodCallback methodHandler, Object userContext, CancellationToken cancellationToken)
</pre>

Error Variant 2 (TwinSenderLink):

<pre>
Microsoft.Azure.Devices.Client.Exceptions.IotHubException: error(condition:amqp:resource-locked,description:A link with name 'TwinSenderLink' is already attached in session 0.)
 ---> Microsoft.Azure.Amqp.AmqpException: A link with name 'TwinSenderLink' is already attached in session 0.
   at Microsoft.Azure.Amqp.AmqpSession.AttachLink(AmqpLink link)
   at Microsoft.Azure.Amqp.AmqpLink.AttachTo(AmqpSession session)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenSendingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String CorrelationId, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenSendingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String CorrelationId, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenTwinSenderLinkAsync(DeviceIdentity deviceIdentity, String correlationIdSuffix, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenTwinSenderLinkAsync(AmqpIoTSession amqpIoTSession, String correlationIdSuffix, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnableTwinLinksAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.EnableTwinPatchAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass23_0.<<EnableTwinPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableTwinPatchAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SetDesiredPropertyUpdateCallbackAsync(DesiredPropertyUpdateCallback callback, Object userContext, CancellationToken cancellationToken)
</pre>

## Code sample exhibiting the issue:

````csharp
public async Task ConnectToHubAsync(CancellationToken cancellationToken)
{
    await semaphoreSlim.WaitAsync(cancellationToken);

    try
    {
        IsConnInProgress = true;
        bool isReconnect = _currentDeviceClient != null;

        // If this is a connection reattempt, dispose the current connection.
        if (isReconnect)
        {
            _currentDeviceClient.SetConnectionStatusChangesHandler(null);
            _currentDeviceClient.Dispose();
        }

        _logger.LogInformation(
            "{operation} to {host}",
            isReconnect ? "Reconnecting" : "Connecting",
            _deviceConfig.HubHost());

        // Create connection and monitor status changes:
        _currentDeviceClient = await CreateConnection(_deviceConfig, cancellationToken);
        _hubLogEvents.SetDeviceContext(new DeviceContext(_deviceConfig.DeviceId, _currentDeviceClient));

        // Enlist for received changes from the hub and agent changes to be sent back to the hub:
        await QueueDesiredPropertyPropertyChanges(_currentDeviceClient, cancellationToken);
        await _currentDeviceClient.SetMethodDefaultHandlerAsync(_directMethodCallback, null, cancellationToken);
    }
    catch (OperationCanceledException)
    {
        // ignore
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "Error connecting or subscribing to Hub");
    }
    finally
    {
        IsConnInProgress = false;
        semaphoreSlim.Release();
    }
}
````

## Console log of the issue:
N/A

## Other Details
This error started appearing in our logs in recent months after upgrading Azure.Devices.Client. If I had to guess, this PR introduced it: https://github.com/Azure/azure-iot-sdk-csharp/pull/1001. It's certainly possible there was an existing issue in our code base that was hidden until recent changes.

However in reviewing the code, I'm not seeing any changes to make to avoid this. Each device has one connection. There is code to monitor connection change / health and reconnect if needed. There's also a custom Serilog sink that routes logs through the IoT hub via device telemetry events - it gets passed the connection after creation.

Any suggestions? Thanks

**Comment by abhipsaMisra** [comment]
Thank you for bringing this to our attention @thnk2wn .
I suspect something in the reconnection logic might be driving the client to this state. This is how the SDK's retry policy works:
Unless disabled, when a disconnection event occurs in the device client, the device client status change handler will return a status of DISCONNECTED_RETRYING, and will internally try to recover the connection. At this point the ownership of recovery lies with the SDK, and the application does not need to take any action. If retry does not make sense/ retry policy has been exhausted, the  device client status change handler returns a status of DISCONNECTED. At this point it is safe to dispose your existing device client instance and re-create a mew instance.

From your sample:

1. Who calls `ConnectToHubAsync`? Is it called only during device client instantiation or also called on disconnection event?
2. If it is called on disconnection event, which event is the trigger? If you dispose the device client instance and try to re-create a new instance while the SDK is retrying internally (when connection status change handler returns status DISCONNECTED_RETRYING), this can potentially cause race conditions with the SDK and application both trying to open sessions/ links for the same device instance.

**Comment by thnk2wn** [comment]
Thanks @abhipsaMisra. It gets called at:

1. Device Startup
2. Connection status changed handler when connection state is ConnectionStatus.Disabled and reconnection is not in progress
3. A background task that sends heartbeats once a minute (when it can't send the heartbeat telemetry event - when it fails due to exception)

What is the built-in reconnection logic and how might that have changed in recent versions?

Items 2 and 3 above should not conflict due to both checking if a reconnection attempt is already underway.

In our client code, where should we safely attempt reconnection (if at all) that won't interfere with the built-in reconnection logic?

**Comment by abhipsaMisra** [comment]
Thank you for the update @thnk2wn .

Our SDK returns the following connection statuses:
1. `Connected` - the client is connection and ready to be used
2. `Disconnected_Retrying` - the client has received a disconnection event, and it attempting to recover. 
3. `Disconnected` - the client has been disconnected. This could be either because the retry policy has expired, or if the client received an unauthorized exception.
4. `Disabled` - the client has be closed by the application by calling `CloseAsync()`.

From the above, it is safe for the application to dispose and re-create a new device client instance when it receives either `Disconnected` or `Disabled`. Attempting to dispose and re-create the device client instance when the status is `Disconnected_Retrying` will have you run into the risk of having multiple device client instances attempting to gain access to the same transport resources.

For Item 3 that you've mentioned above:
> A background task that sends heartbeats once a minute (when it can't send the heartbeat telemetry event - when it fails due to exception)
Do you see the connection status change handler returning a status of `Disconnected`?

If you still do see this issue after putting the above checks in place, could you capture the device logs and share them with us? The steps to collect logs are present here: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

Also, we added some additional fixes around improving AMQP resiliency since v1.22.0. Would you be willing to upgrade to the latest version and giving it a try?

**Comment by thnk2wn** [comment]
Thanks @abhipsaMisra. The existing logic checks for Disconnected status with the exception of the background health check task that reconnects regardless of state when it receives an exception trying to send a message to the hub. I've since modified this to check the state though it's probably still redundant since in theory the state connection handler should in theory fire and reconnect when disconnected.

Our IoT devices with the latest version of our app are already running 1.24.0.

Once we deploy changes to Production soon I'll be able to verify if the additional change removes the error.

**Comment by abhipsaMisra** [comment]
Thanks for the update @thnk2wn .

What is the exception thrown when the heartbeat telemetry event fails? Is it a task cancelled exception? If yes, then at this state the device client is still retrying and the transport layer underneath has not been disposed. 
At this point, the operation (send telemetry, in this case) has timed out (operation timeout is set by `deviceClient.OperationTimeoutInMilliseconds`), causing this exception to be thrown. At this state, if you dispose the current device client instance and recreate a new instance, you would run into the scenario where you have multiple instances fighting for the same transport layer resources.
An easy way to test this would be to monitor the connection status change callback, and verify if the callback was triggered when the heartbeat telemetry event failed.

The recommended way to attempt reconnection (from the application side) is to monitor the connection status change callback, and on receiving a status of `Disconnected` or `Disabled`, dispose the existing device client instance and re-initialize a new instance.

Also, for the purpose of connection heartbeat, AMQP transport setting has a property `AmqpTransportSettings.IdleTimeout` which can be configured to have the AMQP library perform a heartbeat check. With idle timeout set, the AMQP layer will trigger the connection status change callback handler if the heartbeat is sent by the client library but not ack'ed by the service.

Let me know if this helps.

**Comment by thnk2wn** [comment]
A sample exception when the heartbeat telemetry event fails is:

<pre>
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: The operation did not complete within the allocated time 00:01:00 for object message.
 ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object message.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.SendAmqpMessageAsync(AmqpMessage amqpMessage, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.SendAmqpMessageAsync(AmqpMessage amqpMessage, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSendingLink.SendMessageAsync(Message message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.SendMessageAsync(Message message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.SendEventAsync(Message message, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
</pre>

In many cases from the logs however when the original exceptions happen, I'm not seeing evidence that the heartbeat message failed prior to.

As to not handling only from the connection status changed handler, the historical reason is that at least in prior versions of the Azure Devices SDK, we'd lose the device to cloud connection in cases where that event would never fire and this caused us to lose control of our devices remotely. In fact it was so bad in earlier versions that at one point there was even code to forcibly recreate the connection every 15 minutes (that has since been removed).

Perhaps with the current SDK version the connection status handler is enough but losing the connection is very expensive for us (i.e. sending service techs all over the country) so we want all the possible assurances the connection is healthy with no single point of failure.

**Comment by thnk2wn** [comment]
Not seeing this behavior anymore with the additional disconnected check when the heartbeat / health monitoring background task fails to communicate with the hub.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @thnk2wn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
