### ISSUE TITLE
UploadBlob async triggers System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by Harabi** [Azure/azure-iot-sdk-csharp#1398]
Hi, 

I have a .Net4.8 App which reference a NetStandard library 2.0 which reference the Microsoft.Azure.device.Client 1.25 library.

Most of the functionality are working fine expect when I am trying to call:

                _client?.UploadToBlobAsync(blobName, source).Wait();

In this case I am getting a:

System.PlatformNotSupportedException: 'Operation is not supported on this platform.'

The reason is at the:

   at System.Net.Http.HttpClientHandler.set_SslProtocols(SslProtocols value)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper..ctor(Uri baseAddress, IAuthorizationProvider authenticationHeaderProvider, IDictionary`2 defaultErrorMapping, TimeSpan timeout, Action`1 preRequestActionForAllRequests, X509Certificate2 clientCert, HttpClientHandler httpClientHandler, ProductInfo productInfo, IWebProxy proxy)
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler..ctor(IPipelineContext context, IotHubConnectionString iotHubConnectionString, Http1TransportSettings transportSettings, HttpClientHandler httpClientHandler)
   at Microsoft.Azure.Devices.Client.InternalClient.UploadToBlobAsync(String blobName, Stream source, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.DeviceClient.UploadToBlobAsync(String blobName, Stream source)
   

This issue seems to have been reported many times from what I can read it should not be there on the .Net framework 4.7.2 and above.

Could you please tell me more about it.

Thanks in advance,
Regards,
Hakim

**Comment by az-iot-builder-01** [comment]
@Harabi, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Harabi** [comment]
Hi Thanks for your comment it was a dead link to the version 1.23 which was the root cause.
