### ISSUE TITLE
[Bug Report] Device client WaitForDeviceStreamRequestAsync exception

### ISSUE THREAD

**Issue by kevin-yang** [Azure/azure-iot-sdk-csharp#1411]
Hello,

We have a program running with devicestream features. The device side is waiting for service side to connect to it, and then we notice the following exception thrown out

[2020-06-19T08:41:51 INF] Connection Status Changed to Disabled reason Client_Close
[2020-06-19T08:41:51 WRN] Got an unexpected exception: Microsoft.Azure.Devices.Client.Exceptions.IotHubException: error(condition:amqp:resource-locked,description:A link with name '_StreamsReceiverLink:' is already attached in session 0.)
 ---> Microsoft.Azure.Amqp.AmqpException: A link with name '_StreamsReceiverLink:' is already attached in session 0.
   at Microsoft.Azure.Amqp.AmqpSession.AttachLink(AmqpLink link)
   at Microsoft.Azure.Amqp.AmqpLink.AttachTo(AmqpSession session)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenReceivingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String correlationId, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenReceivingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String correlationId, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenStreamsReceiverLinkAsync(DeviceIdentity deviceIdentity, String correlationIdSuffix, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureStreamsReceiverLinkAsync(AmqpIoTSession amqpIoTSession, String correlationIdSuffix, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnableStreamsAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.WaitForDeviceStreamRequestAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass22_0.<<WaitForDeviceStreamRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.WaitForDeviceStreamRequestAsync(CancellationToken cancellationToken)
   at DeviceProxy.RunDeviceProxyAsync(CancellationTokenSource cancellationTokenSource, DeviceClient deviceClient)

This exception is random, more likely to be seen when the network is not good.

The following are some code snippet we have:
{
	......
	using (_deviceClient = DeviceClient.CreateFromConnectionString(ConnectionString, TransportType.Amqp))
	{
		_deviceClient.SetConnectionStatusChangesHandler(OnConnectionStatusChanged);
		using (_cancelTokenSource = new CancellationTokenSource())
		{
			await RunDeviceProxyAsync(_cancelTokenSource, _deviceClient).ConfigureAwait(false);
		}
	}
	......
}

public async Task RunDeviceProxyAsync(CancellationTokenSource cancellationTokenSource, DeviceClient deviceClient)
{
    DeviceStreamRequest streamRequest = await deviceClient.WaitForDeviceStreamRequestAsync(cancellationTokenSource.Token).ConfigureAwait(false);
    ......
} 

And from another side, we notice the connection event changed to disabled saying client_close connection, but there is no operation from client side/service side.

The program is running with dotnet core 3.1, and the azure sdk version is as below
	<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.29.0-preview-*" />

Thanks,
YK

**Comment by abhipsaMisra** [comment]
@kevin-yang I believe this could have been caused by an issue in the underlying AMQP library used, where it was not cleaning up older link references of a closed session. This issue has a possibility of surfacing up during device reconnection, when the SDK thinks that all older resources have been cleaned up, with the AMQP library is still keeping those references around.
We released a fix for this here: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-2-27, and brought those fixes into the "preview" bits as well, but have not released them yet.

Would it be possible for you to take a dependency on our [preview sourcecode](https://github.com/Azure/azure-iot-sdk-csharp/tree/preview/iothub/device) and see if that fixes your issue?

**Comment by kevin-yang** [comment]
Thanks for prompt response. After using the latest AMQP library, the issue seems solved. We will keep monitor the system and will reopen it if we see it again.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @kevin-yang, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
