### ISSUE TITLE
[Technical Question] Tpm2Lib Returns SessionMemory Exception

### ISSUE THREAD

**Issue by FrankSHLi** [Azure/azure-iot-sdk-csharp#1487]
## Backgrounds
While running the TpmSample on a Debian 9 armhf device with TPM 2.0 chip, ProvisioningDeviceClientSample raises exception at [line 116](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/9335a1da2debc0ab6aa85e5820556ac708d89084/provisioning/Samples/device/Common/ProvisioningDeviceClientSample.cs#L31). Note that we are transporting via http, so the exception comes from [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/768c68ffb3c8d886b8e166624b4ba435004c4ce4/provisioning/transport/http/src/ProvisioningTransportHandlerHttp.cs#L41).

## Console Log
```
Unhandled exception. Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: HTTP transport exception
 ---> Tpm2Lib.TpmException: Error {SessionMemory} was returned for command StartAuthSession.
Details:
[Code=TpmRc.SessionMemory],[RawCode=0x903,2307]
[ErrorEntity=Unknown], [ParmNum=0]
[ParmName=Unknown]
   at Tpm2Lib.Tpm2.ProcessError(TpmSt responseTag, UInt32 responseParamSize, TpmRc resultCode, TpmStructureBase inParms)
   at Tpm2Lib.Tpm2.DispatchMethod(TpmCc ordinal, TpmStructureBase inParms, Type expectedResponseType, TpmStructureBase& outParms, Int32 numInHandlesNotUsed, Int32 numOutHandlesNotUsed)
   at Tpm2Lib.Tpm2.StartAuthSession(TpmHandle tpmKey, TpmHandle bind, Byte[] nonceCaller, Byte[] encryptedSalt, TpmSe sessionType, SymDef symmetric, TpmAlgId authHash, Byte[]& nonceTPM)
   at Tpm2Lib.Tpm2.StartAuthSessionEx(TpmHandle boundEntity, TpmSe sessionType, TpmAlgId authHash, SessionAttr initialialAttrs, SymDef symDef, Int32 nonceCallerSize)
   at Tpm2Lib.Tpm2.StartAuthSessionEx(TpmSe sessionType, TpmAlgId authHash, SessionAttr initialialAttrs, SymDef symDef, Int32 nonceCallerSize)
   at Tpm2Lib.Tpm2.StartAuthSessionEx(TpmSe sessionType, TpmAlgId authHash, SessionAttr initialialAttrs, Int32 nonceCallerSize)
   at Tpm2Lib.Tpm2.StartAuthSessionEx(TpmSe sessionType, TpmAlgId authHash, Int32 nonceCallerSize)
   at Microsoft.Azure.Devices.Provisioning.Security.SecurityProviderTpmHsm.ActivateIdentityKey(Byte[] encryptedKey)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningSasBuilder.ExtractServiceAuthKey(SecurityProviderTpm securityProvider, String hostName, Byte[] activation)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.TpmDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.RuntimeRegistration.RegisterDeviceWithHttpMessagesAsync(String registrationId, String idScope, DeviceRegistration deviceRegistration, Nullable`1 forceRegistration, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.RuntimeRegistrationExtensions.RegisterDeviceAsync(IRuntimeRegistration operations, String registrationId, String idScope, DeviceRegistration deviceRegistration, Nullable`1 forceRegistration, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerHttp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerHttp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
```

## Questions
- Is this ever seen in the past?
- Any insight about this exception?
- How to trace into Tpm2Lib?

## Environment
- **SDK version used:**
    Microsoft.Azure.Devices.Client v1.27.0
    Microsoft.Azure.Devices.Provisioning.Client v1.6.0
    Microsoft.Azure.Devices.Provisioning.Security.Tpm v1.2.3
    Microsoft.Azure.Devices.Provisioning.Service v1.6.3
    Microsoft.Azure.Devices.Provisioning.Transport.Http v1.2.4

**Comment by timtay-microsoft** [comment]
@amarochk may be able to help here. For all things TPM, I recommend looking at [this repo](https://github.com/microsoft/TSS.MSR) and filing this bug there if necessary

**Comment by amarochk** [comment]
Not sure why the issue has 'BadAuth' in its title, as the call stack shows that the error is TpmRc.SessionMemory. This is not a TSS.Net (Tpm2lib) error, but the one returned by the TPM. This happens when a code tries to create and HMAC or policy session, but there are no vacant slots for active session in the TPM (most TPMs only allow for 3 active sessions). Such a situation usually occurs when an earlier executed code did not call FlushContext() for the session handles it used, or when a code creates one or more TPM sessions and is aborted without a chance to clean them up.

**Comment by vinagesh** [comment]
@FrankSHLi  Is this still a problem? Does this happen with the latest packages as well?

**Comment by vinagesh** [comment]
Closing this due to inactivity. Please reopen an issue if needed.

**Comment by az-iot-builder-01** [comment]
@FrankSHLi, @timtay-microsoft, @amarochk, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
