### ISSUE TITLE
[Bug Report] SendEventAsync throws NotSupportedException with .Net 5.0.

### ISSUE THREAD

**Issue by jcannata** [Azure/azure-iot-sdk-csharp#1489]
# Context
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 Build 18363
- **Application's .NET Target Framework :** net5.0
- **Device:** Desktop
- **SDK version used:** 5.0.100-preview.7.20366.6, Microsoft.Azure.Devices.Client 1.27.0

## Description of the issue
DeviceClient's _SendEventAsync_ method throws a System.NotSupportedException when built and run using .NET 5.0. The method succeeds when running .NET Core 3.1. This failure occurs every single time.
I am not sure if I should report this here or in the dotnet/runtime repo.

## Code sample exhibiting the issue
```
using System;
using System.Threading.Tasks;
using System.Text;
using Microsoft.Azure.Devices.Client;

namespace pic
{
    class Program
    {
        private static DeviceClient s_deviceClient;
        // The device connection string to authenticate the device with your IoT hub.
        // Using the Azure CLI:
        // az iot hub device-identity show-connection-string --hub-name {YourIoTHubName} --device-id MyDotnetDevice --output table
        private const string s_connectionString = "{your connection string}";

        static async Task Main()
        {
            // Connect to the IoT hub using the MQTT protocol
            s_deviceClient = DeviceClient.CreateFromConnectionString(s_connectionString, TransportType.Mqtt);

            var payload = new {
                message = "hello!"
            };

            var messageString = JsonConvert.SerializeObject(payload);
            var messageBytes = Encoding.ASCII.GetBytes(messageString);
            var message = new Message(messageBytes);

            await s_deviceClient.SendEventAsync(message);
        }
    }
}
```

## Console log of the issue
```
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at Microsoft.Azure.Devices.Client.Common.ReadOnlyMergeDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.get_Count()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.Azure.Devices.Client.Common.UrlEncodedDictionarySerializer.Serialize(IEnumerable`1 properties)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.PopulateMessagePropertiesFromMessage(String topicName, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ComposePublishPacketAsync(IChannelHandlerContext context, Message message, QualityOfService qos, String topicName)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at pic.Program.Main() in C:\Repos\sandbox\pic\Program.cs:line 34
   at pic.Program.<Main>()
```

**Comment by timtay-microsoft** [comment]
Our device client library currently only supports NetStandard 2.1, NetStandard 2.0, net472 and net451, so this is expected behavior. Could you use one of these frameworks for your project instead?

**Comment by jcannata** [comment]
Yes, I can use one of the supported frameworks. Hopefully it will be supported in the future. Thank you.

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @abhipsaMisra, @jcannata, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
