### ISSUE TITLE
GetFileUploadSasUriAsync throws NullReferenceException when using CA signed certificates to authenticate the device

### ISSUE THREAD

**Issue by Perun85** [Azure/azure-iot-sdk-csharp#1527]
- **OS, version, SKU and CPU architecture used:** <VERSION> Windows 10 Enterprise 2016 LTSB
- **Application's .NET Target Framework :** <NETVERSION> netcoreapp3.0; netcoreapp3.1
- **Device:** <DEVICETYPE> Laptop
- **SDK version used:** <VERSION>1.27.0; 1.29.1-preview-002

When CA signed certificates are used to authenticate the device, method GetFileUploadSasUriAsync throws NullReferenceException.

**StackTrace**

`at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Devices.Client.IAuthorizationProvider.GetPasswordAsync()
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<ExecuteAsync>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<PostAsync>d__17`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.<GetFileUploadSasUri>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.Client.InternalClient.<GetFileUploadSasUriAsync>d__77.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
`

**Comment by abhipsaMisra** [comment]
Do you have the corresponding CA certs uploaded to your hub instance?

**Comment by Perun85** [comment]
Yes, I do. I am able to connect to IoTHub and perform other operations except retrieving SAS URI for file upload.

**Comment by azabbasi** [comment]
We have checked in the fix for this issue, we will be releasing a new version of the Device SDK soon. 
Is there a specific reason you are using the preview version? (ex: Device streaming APIs) if not, we recommend using the GA version of the SDK as it will get the updates sooner than the preview SDK.

**Comment by Perun85** [comment]
Thank you for the info. 
Yes, there is. We have features that are based on device streaming API. 
I will build client from latest master just to confirm that we can SAS URI API with our flow.

**Comment by Perun85** [comment]
I have just tested it with version built from current master, and it works. 

There is one more thing. Client internally uses HTTPS to obtain the token, even though primary connection uses AMQP. Would it possible that entire communication is done over primary protocol?
I ask this because we have complex CA hierarchy. AMQP and MQTT protocols do not require from us to register all intermediate certificates (We have around 1000 of them and number is growing and IoTHub has limit of 20 certificates in total). On other hand HTTPS requires entire certificate chain.

**Comment by azabbasi** [comment]
Thanks for letting us know, We will bring these changes to the preview and release a new version shortly.

Yes, the only available protocol for the file upload APIs on the IoTHub service is HTTP, so regardless of the protocol you indicate when you are instantiating the DeviceClient, we will open an HTTP client.

One option would be for you to use SAS token credentials but since you are using certificates and those are generally preferred over SAS tokens, I am not sure that is the path you want to explore right?

The certificate limit is imposed by the service and Andrei ( @ailn ) might be able to provide guidance on what is recommended here.

**Comment by azabbasi** [comment]
@Perun85 We have published a new release for .NET SDK (both master and preview versions)
https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2020-9-21
https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2020-9-11

**Comment by Perun85** [comment]
Thank you for the info.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @Perun85, @azabbasi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
