### ISSUE TITLE
[Bug Report] Error: Missing IoT Hub Name when connecting through Gateway

### ISSUE THREAD

**Issue by ThomasPe** [Azure/azure-iot-sdk-csharp#1552]
# Context

- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** 1.28.0

## Description of the issue
When trying to connect an IoT Device through a transparent Gateway, [according to the docs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-authenticate-downstream-device#retrieve-and-modify-connection-string) I should be able to simplify the Connection String by setting the HostName to the Gateway Hostname instead of the IoT Hub address (provided the IoT Device is a Child of the Gateway). However, this shorthand seems to violate the SDKs Connection String Format check:

`private readonly static string s_connectionString = "HostName=MyHostName;DeviceId=SimulatedTestDevice;SharedAccessKey=.....................";`

![image](https://user-images.githubusercontent.com/4225039/92612649-590bb600-f2ba-11ea-9949-10b4d4e4dc8b.png)

The non-shorthand version seems to work, but I think it would be good to not throw an error if the docs explicitly tell you about it.

I've been using the [Quickstart sourcecode](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Quickstarts/simulated-device), only updating to .NET Core 3.1 and updating to the latest SDK version.

## Code sample exhibiting the issue
https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Quickstarts/simulated-device/SimulatedDevice.cs

## Console log of the issue
```
System.FormatException
  HResult=0x80131537
  Message=Missing IOT hub name
  Source=Microsoft.Azure.Devices.Client
  StackTrace:
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.SetIotHubName()
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.SetHostName(String hostname)
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.set_HostName(String value)
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.Parse(String iotHubConnectionString)
   at Microsoft.Azure.Devices.Client.IotHubConnectionStringBuilder.CreateWithIAuthenticationOverride(String iotHubConnectionString, IAuthenticationMethod authenticationMethod)
   at Microsoft.Azure.Devices.Client.ClientFactory.CreateFromConnectionString(String connectionString, IAuthenticationMethod authenticationMethod, ITransportSettings[] transportSettings, IDeviceClientPipelineBuilder pipelineBuilder, ClientOptions options)
   at Microsoft.Azure.Devices.Client.ClientFactory.CreateFromConnectionString(String connectionString, IAuthenticationMethod authenticationMethod, TransportType transportType, IDeviceClientPipelineBuilder pipelineBuilder, ClientOptions options)
   at Microsoft.Azure.Devices.Client.ClientFactory.CreateFromConnectionString(String connectionString, TransportType transportType, ClientOptions options)
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass10_0.<CreateFromConnectionString>b__0()
   at Microsoft.Azure.Devices.Client.DeviceClient.Create(Func`1 internalClientCreator)
   at Microsoft.Azure.Devices.Client.DeviceClient.CreateFromConnectionString(String connectionString, TransportType transportType, ClientOptions options)
   at simulated_device.SimulatedDevice.Main(String[] args) in C:\Users\Name\Desktop\Quickstarts\simulated-device\SimulatedDevice.cs:line 62
```

**Comment by abhipsaMisra** [comment]
Can you add a link to the document that specifies the shorthand format acceptable when connecting via a transparent gateway?

**Comment by ThomasPe** [comment]
I meant to do that, sorry. I updated my original post.

**Comment by abhipsaMisra** [comment]
Thanks for the info, I'll look into this.

**Comment by cdjoshi23** [comment]
Any update on this issue? I am having the same issue.

**Comment by abhipsaMisra** [comment]
The fix has now been merged in, and is available in the `master` branch. I will update this thread once the release is out.

**Comment by abhipsaMisra** [comment]
This fix has now been released: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021-01-21
