### ISSUE TITLE
After 1024 Successful Connection, DeviceClient ReceiveAsync Receives Exception as - Operation timeout expired & (at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__19`1.MoveNext()) 

### ISSUE THREAD

**Issue by traghunathan** [Azure/azure-iot-sdk-csharp#161]
We are executing C# tool for DeviceClient Connection to Azure IOT for 2000 devices. When the tool reaches 1000 plus device count, Tool Receives the exception as 
1. Operation timeout expired & 
2. (at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__19`1.MoveNext()) 
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Testing Scenario :
Scenario 1: 
Total Number of Device on Single Instance - 2000
Issue - Once device reach 1024 Client Connection, We Receive Exception as
 (at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__19`1.MoveNext()) 
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Scenario 2:
Running Two instances, Each Instance contain 1000 devices.
Issue - 1st Instance 1000 device connection is success.
2nd Instance, after 50 devices, Tool is receiving Exception as 
 (at Microsoft.Azure.Devices.Client.TaskHelpers.<WithTimeout>d__19`1.MoveNext()) 
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

We want to try around 5000 devices in single instance. Need help.

**Comment by CIPop** [comment]
@traghunathan I believe you are hitting the Hub throttling of maximum 100 connections / minute / unit for an S1 or S2 instance. 
From https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling:


Throttle | Free and S1 hubs | S2 hubs | S3 hubs
-- | -- | -- | --
Device connections | Higher of 100/sec or 12/sec/unit For example, two S1 units are 2*12 = 24/sec, but you have at least 100/sec across your units. With nine S1 units, you have 108/sec (9*12) across your units. | 120/sec/unit | 6000/sec/unit

There are a few ways to solve this:
1. Add some timeouts to ensure that the throttles are not reached using the simulator
2. Add random delayed retry logic after a timeout (to avoid having too many devices retry at the same time)

**Comment by tameraw** [comment]
@traghunathan - Please let us know if still have any issues. Regards.
