### ISSUE TITLE
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized

### ISSUE THREAD

**Issue by ulaurent** [Azure/azure-iot-sdk-csharp#1775]
Having an issue With a specific device ID unable to connect. I have systems already able to build a connection to the Hub properly and I can not recreate the issue on other systems with this device ID. Using the same deviceID  

The system is a Win 10 OS. Am wondering what can be the caused of this issue? 

Stack trace is as follows:

Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<OpenAsyncInternal>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<OpenAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.<OpenAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<EnsureOpenedAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass24_0.<<SendTwinGetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<SendTwinGetAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.InternalClient.<GetTwinAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Instron.Connect.Core.API.ConnectAPI.<GetDeviceTwinProperties>d__118.MoveNext() in C:\Connect.Core.API\Instron.Connect.Core.API\ConnectAPI.cs:line 1457
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Instron.Connect.Core.API.ConnectAPI.<CleanMessageQueueAsync>d__115.MoveNext() in C:\Connect.Core.API\Instron.Connect.Core.API\ConnectAPI.cs:line 1387
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Instron.Connect.Core.API.ConnectAPI.<ConnectMqtt>d__108.MoveNext() in C:\Connect.Core.API\Instron.Connect.Core.API\ConnectAPI.cs:line 123202/08/2021 02:39:16

**Comment by drwill-ms** [comment]
How do you authenticate with this device? Symmetric key? Certificate? TPM? The error sounds like the auth information is wrong.

You mention trying as the same Id from different systems. Do any systems try to connect using this device Id at the same time? That isn't supported, and existing clients will get bumped.

What transport protocol are you using? If you use AMQP you may get a better error message when disconnected.

**Comment by ulaurent** [comment]
Using a com derived symmetric key. No we are not connecting using the same device ID at the same time. We are sending D2C & C2D messages so every device Id is unique. I tested on another device using the device Id to see if I would get repeatability and I did not. The transport type gets set to MQtt_WebsocketOnly over port 443. The issue is understanding what would cause this to occur since the system in the field is already trying to connect via MQTT_WS. I have not seen this with other systems with different deviceID  and I have yet been able to recreate

**Comment by drwill-ms** [comment]
From a different machine, it could be any number of things (basic networking, bad input, firewall rules, proxy, .NET frameworks installed).

From the error message, it simply sounds like the wrong device Id or symmetric key. If you've validated that, you could try collecting logs from the SDK and sharing those with us.

Here are the steps for capturing SDK logs: <https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs>.

You can either start a trace collector tool, and capture them as ETL traces; or you can include this ConsoleEventListener in your test project and initialize the listener as below, which will route the logs to your console output.
(writing to console log would make debugging it easier, but it will also slow down your application’s execution).
 
// Instantiating this seems to do all we need for outputting SDK events to our console log
`_ = new ConsoleEventListener("Microsoft-Azure-");`

**Comment by ulaurent** [comment]
okay. In the process of getting the sdk logs. As of recently, we tried connecting with the same machine and with no changes the application was able to connect successfully with no exceptions. The links below are others who have had similar issues. it is very unclear on what can be the cause.

[2:43 PM] Laurent, Urbenson
https://github.com/Azure/iotedge/issues/24

[2:44 PM] Laurent, Urbenson
https://github.com/Azure/azure-iot-sdk-csharp/issues/776

**Comment by drwill-ms** [comment]
@ulaurent just checking in with you to see if you've been able to repro the issue. Thanks :)

**Comment by drwill-ms** [comment]
@ulaurent I'm going to close this issue for now, but please reactivate it if you have more info to share.
