### ISSUE TITLE
[Technical Question] Edge module and .NET 5

### ISSUE THREAD

**Issue by its-phil** [Azure/azure-iot-sdk-csharp#1782]
I have a number of Edge modules running fine under .NET Core 3.1. Switching their projects to .NET 5.0 breaks all modules when trying to connect the `ModuleClient`. Specifically, `OpenAsync` fails with exception "InvalidOperationException: Operation is not valid due to the current state of the object.". The `ModuleClient` instance is created with `ModuleClient.CreateFromEnvironmentAsync` and transport settings `Amqp_Tcp_Only`.
I read [here](https://github.com/Azure/azure-iot-sdk-csharp) that .NET Standard 2.1 is supported by the Azure IoT C# SDK and [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) that .NET 5 implements .NET Standard 2.1. I cannot find any documentation stating that the Azure IoT C# SDK doesn't support .NET 5, so I thought a transition would be easy. Am I wrong? Is .NET 5 not supported yet?

Versions in use:
- Azure.Devices.Client: 1.35.0
- dotnet --version: 5.0.102

**Comment by abhipsaMisra** [comment]
Your expectation is valid; while our clients don't officially support .NET 5 _yet_, we don't expect there to be too many blockers for the transition.
Would you be able to capture the sdk logs and share them with us: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs

**Comment by drwill-ms** [comment]
Call stack:
```
 Unexpected error System.NotSupportedException: Specified method is not supported.
   at Microsoft.Azure.Devices.Client.Common.ReadOnlyMergeDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.get_Count()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.Azure.Devices.Client.Common.UrlEncodedDictionarySerializer.Serialize(IEnumerable`1 properties)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.PopulateMessagePropertiesFromMessage(String topicName, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ComposePublishPacketAsync(IChannelHandlerContext context, Message message, QualityOfService qos, String topicName)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at Microsoft.Azure.Devices.Client.Samples.ModuleSample.SendMessagesAsync(CancellationToken cancellationToken) in C:\code\AzureSamples\azure-iot-samples-csharp\iot-hub\Samples\module\ModuleSample\ModuleSample.cs:line 208
```

**Comment by drwill-ms** [comment]
I repro'd it with 1.31.0, but it does not repro in 1.35.0. We appear to have fixed it between those releases.

**Comment by drwill-ms** [comment]
Never mind. My callstack isn't what @its-phil was seeing, and he's already on 1.35.0. I'm unable to repro it in our module sample.

**Comment by its-phil** [comment]
Thanks for your replies. I must confess, I can't repro the issue myself at the moment. Out of the blue, it just seems to work fine on .NET 5. Interesting enough, the same issue even occurred with `DeviceClient` projects yesterday, but not always reliably reproducible. I wonder: could it be a timing issue? I'll continue to try reproducing the error and report back here.

How far down the road is official .NET 5 support? As long as it is not officially supported I'd rather return to .NET Core 3.1.

**Comment by drwill-ms** [comment]
It should work, but we haven't validated our whole SDK with it yet. It is relatively high on our backlog.

I don't think the issue you ran into was net5-related, though.

**Comment by abhipsaMisra** [comment]
@its-phil Our internal testing hasn't revealed any issues in using module clients with .NET 5. 
We have added .NET 5 support into our [preview](https://github.com/Azure/azure-iot-sdk-csharp/tree/preview) branch and are working on getting a release out soon. In the meanwhile, you are welcome to use the preview branch for carrying out any tests.

**Comment by its-phil** [comment]
@abhipsaMisra That's good news. Thanks for letting me know!

**Comment by abhipsaMisra** [comment]
@its-phil We've now released a preview nuget with .NET 5 support added: https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/preview_2021-6-8

Let me know if you still face any issues; I'll wait for a couple of days before closing this.

**Comment by abhipsaMisra** [comment]
Closing this since the .NET 5 preview package has now been released. Feel free to file a new issue if you face any problems.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
