### ISSUE TITLE
Microsoft.Azure.Devices.Client does not work with dotnet core 5.0

### ISSUE THREAD

**Issue by uffebjorklund** [Azure/azure-iot-sdk-csharp#1894]
# Environment

```
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.10
 OS Platform: Linux
 RID:         ubuntu.20.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]
  5.0.102 [/usr/share/dotnet/sdk]
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Description of the issue

We have two runtimes, one for dotnet core 3.1 and the other for dotnet core 5.0.
Our class-libs are referenced by both these runtimes and they are all built for netstandard2.1
One of the libs are using `Microsoft.Azure.Devices.Client` to communicate with the Azure IoT Hub.
We use all available communicaiton-protocols (HTTP1, MQTT and AMQP) and in dotnet core 3.1 they all work, but in dotnet core 5.0 only HTTP1 works.

We have tested with the current release `<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.36.0" />` no difference in the result.

Basically the library does not work with dotnet core 5.0 if using MQTT or AMQP

Found a few other bugs, for example (https://github.com/Azure/azure-iot-sdk-csharp/issues/1562#issue-703886271) that seems to be related, but closed. 

### AMQP throws here for dotnet core 5.0 (works with the same code in dotnet core 3.1)
```
this.deviceClient = DeviceClient.Create(this.Settings.IotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey(this.AzureDeviceCredential.DeviceId, this.AzureDeviceCredential.DeviceKey), new ITransportSettings[] { Settings.GetTransportSettings() });
this.deviceClient.SetConnectionStatusChangesHandler(ConnectionStatusChangesHandler);
await this.deviceClient.OpenAsync();
```

### MQTT throws here (works with the same code in dotnet core 3.1)

```
await deviceClient.SendEventAsync(new Message(data));
```

## Console log of the issue

A big difference between the errors in AMQP and MQTT is that AMQP throws when connecting, but MQTT throws when sending

### Error when using MQTT

```
Failed to send to IoTHub Specified method is not supported. at Microsoft.Azure.Devices.Client.Common.ReadOnlyMergeDictionary`2.System.Collections.Generic.ICollection>.get_Count() at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source) at Microsoft.Azure.Devices.Client.Common.UrlEncodedDictionarySerializer.Serialize(IEnumerable`1 properties) at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.PopulateMessagePropertiesFromMessage(String topicName, Message message) at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ComposePublishPacketAsync(IChannelHandlerContext context, Message message, QualityOfService qos, String topicName) at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message) at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data) at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken) at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message) at Crosser.EdgeNode.Modules.Azure.IoT.Hub.D2C.IoTHubD2CModule.Send(Byte[] data)
```

### Error when using AMQP

```
Failed to connect to Azure IoT Hub: Operation is not valid due to the current state of the object. at Microsoft.Azure.Amqp.Transport.TransportStream.Flush() at System.IO.Stream.<>c.b__39_0(Object state) at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult) at Microsoft.Azure.Amqp.StreamExtensions.EndAuthenticateAsClient(SslStream sslStream, IAsyncResult asyncResult) at Microsoft.Azure.Amqp.Transport.TlsTransport.HandleOpenComplete(IAsyncResult result, Boolean syncComplete) --- End of stack trace from previous location --- at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception) at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result) at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result) at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result) at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.HandleTransportOpened(IAsyncResult result) at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.OnTransportOpened(IAsyncResult result) --- End of stack trace from previous location --- at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout) at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout) at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout) at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout) at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout) at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout) at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken) at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken) at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass32_0.<b__0>d.MoveNext() --- End of stack trace from previous location --- at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken) at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync() at Crosser.EdgeNode.Modules.Azure.IoT.Hub.Common.IoTHubClientModule`1.ConnectDeviceToCloud()
```

**Comment by drwill-ms** [comment]
Hi Bjorn. Thanks for the issue report. We know there are some issues with .NET 5.0. One of our team members has been closing the gap, and has the [changes](https://github.com/Azure/azure-iot-sdk-csharp/tree/previews/net5) ready to go out in preview soon.

**Comment by abhipsaMisra** [comment]
Hi @uffebjorklund , our library previously had a custom implementation of readonly dictionary, which was partially implemented, and gave rise to the exception that you've reported with MQTT. We removed this custom implementation a while back, and this should no longer be an issue: https://github.com/Azure/azure-iot-sdk-csharp/pull/1594
You've mentioned that you're seeing this error even with the latest version of the library, which surprises me given that `Microsoft.Azure.Devices.Client.Common.ReadOnlyMergeDictionary` no longer exists. Would you mind double-checking the version of the client library that you are testing with?

As David has mentioned above, we've incorporated .NET 5 into our library in the [preview branch](https://github.com/Azure/azure-iot-sdk-csharp/tree/previews/net5), and haven't seen any [major blockers](https://github.com/Azure/azure-iot-sdk-csharp/pull/1836). We are planning to release it as preview soon, but you are free to try it out in the meanwhile from the preview branch.

**Comment by uffebjorklund** [comment]
@abhipsaMisra @drwill-ms 
I can confirm that we are using the latest package `<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.36.0" />` if that was the package you meant? 

I have asked a colleague to double check since we have a custom package resolver that in theory could replace some assembly versions. Will post an update as soon as I hear back from him.

**Comment by uffebjorklund** [comment]
@abhipsaMisra @drwill-ms 
Happy to let you know that the issue was on my side. The latest package works as expected both for MQTT and AMQP.

Sorry for taking your time.

**Comment by abhipsaMisra** [comment]
Not a problem. I am glad it is working for you now.
