### ISSUE TITLE
DeviceClient-SendEventAsync throwing InvalidOperationException

### ISSUE THREAD

**Issue by jlingaa** [Azure/azure-iot-sdk-csharp#2232]
# Context

- **OS:** Mac BigSur 11.6
- **Application's .NET Target Framework :** netcoreapp3.1 
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client 1.39.0

## Description of the issue
Wrote a small console app trying to test the robustness of the iothub when sending 125000 messages(5000 messages every 5 min triggered by 25 timers). It all works fine but suddenly I see lot of error messages thrown especially related to InvalidOperationException - Collection was modified after the enumerator was instantiated.

This happens on the deviceClient.SendEventAsync API call.

Note sure if this is a bug or something we are not doing right, but it happens when ran for a long time. Please let us know if there is something on the application side we need to change.

## Code sample exhibiting the issue

```cs
       private static DeviceClient _iotHubClient = DeviceClient.CreateFromConnectionString(ConnectionString, TransportType.Mqtt_WebSocket_Only);
       private static string Message = "{}"; // Some valid json message.
        static void Main(string[] args)
        {
            Console.WriteLine("Number of instances to span: ");
            var instanceInput = Convert.ToInt32(Console.ReadLine());  // 25
            Console.WriteLine("Interval to send messages: ");
            var interval = Convert.ToInt32(Console.ReadLine());   // 5
            Console.WriteLine("Number of messages to send: Default is 5000");
            string messageCount = Console.ReadLine();   // 5000
            if (!String.IsNullOrEmpty(messageCount))
                _messageCount = Convert.ToInt32(messageCount);

            for (int instanceCount = 0; instanceCount < instanceInput; instanceCount++)
            {
                System.Timers.Timer timer = new System.Timers.Timer(TimeSpan.FromMinutes(interval).TotalMilliseconds);
                timer.AutoReset = true;
                timer.Elapsed += async(sender, e) => await SendMessagesToIOTHub(sender, e);
                timer.Start();
                Console.WriteLine($"{DateTime.Now}: Timer started to execute every {interval} minutes");
            }

            while (true)
            {
                Thread.Sleep(1000);
            }
        }

        private static async Task SendMessagesToIOTHub(object sender, ElapsedEventArgs e)
        {
            Console.WriteLine($"{DateTime.Now}: Sending {_messageCount} messages");
            for (int i = 1; i <= _messageCount; i++)
            {
                try
                {
                    var message = new Message(Encoding.ASCII.GetBytes(Message));
                    message.ContentType = "application/json";
                    message.ContentEncoding = "utf-8";

                    await _iotHubClient.SendEventAsync(message);
                }
                catch (IotHubCommunicationException ice)
                {
                    Console.WriteLine($"{DateTime.Now}: IotHubCommunicationException - {ice.ToString()}");
                }
                catch (NullReferenceException nre)
                {
                    Console.WriteLine($"{DateTime.Now}: NullReferenceException - {nre.ToString()}");
                }
                catch (AggregateException agE)
                {
                    Console.WriteLine($"{DateTime.Now}: AggregateException - {agE.ToString()}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"{DateTime.Now}: General Exception sending message {ex.ToString()}");
                }
            }
            Console.WriteLine($"{DateTime.Now}: {_messageCount} messages sent");
        }
```

## Console log of the issue
Here is the call stack of the error noticed...

11/4/2021 6:55:15 PM: General Exception sending message System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.OrderedTwoPhaseWorkQueue`2.CompleteWorkAsync(IChannelHandlerContext context, TWorkId workId)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.ProcessMessage(IChannelHandlerContext context, Packet packet)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)

**Comment by azabbasi** [comment]
@jlingaa 
Thank you for reporting this issue, we will investigate and get back to you with updates.

**Comment by azabbasi** [comment]
@jlingaa 
I don't see any issues with the code you are running except for not disposing of the messages once you send them. 

```

**Comment by azabbasi** [comment]
var message = new Message(Encoding.ASCII.GetBytes(Message));
                    message.ContentType = "application/json";
                    message.ContentEncoding = "utf-8";

                    await _iotHubClient.SendEventAsync(message);
                    message.Dispose();
```

This can potentially cause memory leaks but it isn't the root cause of the issue you came across, we have identified the issue and will have a fix out soon.

**Comment by jlingaa** [comment]
@azabbasi Thanks for the update. We will handle disposing the messages to avoid the memory leaks. Please let us know the version the fix is in, so we can update accordingly.
