### ISSUE TITLE
[Bug Report] IoT Hub SDK sometimes stops receiving messages after connection status changes

### ISSUE THREAD

**Issue by mkortemeier** [Azure/azure-iot-sdk-csharp#2267]
# Context

- OS version: Windows 10 Enterprise 20H2 x64, Windows Server 2019 Standard x64
- Application's .NET Target Framework : net5.0
- SDK version used: 1.39.0

## Description of the issue
We are using the IoT Hub SDK in environments where the internet connection can be unstable. After the IoT Hub SDK reconnects on connection losses, it can happen that the _client.ReceiveAsync() method is stuck and won't return. This can be reproduced by actively closing open TCP connections to the IoT Hub and also closing the TCP connections of reconnection attempts.

Our code looks like this:
``` c#
private async Task ListenAsync(CancellationToken cancellationToken)
{
	_client.SetConnectionStatusChangesHandler(ConnectionStatusChangeHandler);
	_log.Info(string.Format("[{0}] Listening for cloud-2-device messages from Azure service.", nameof(Ccc)));

	var failCounter = 0;

	while (!cancellationToken.IsCancellationRequested)
	{
		Message receivedMessage = null;

		try
		{
			_log.Info("- 0 - Listening for new message");
			receivedMessage = await _client.ReceiveAsync();
			_log.Info("- 1 - Listening finished");

			if (receivedMessage == null)
			{
				_log.Info("- 2 - received message null - continue");
				continue;
			}                        

			_log.Info("- 3 - Message Received: LockToken: " + receivedMessage.LockToken);

			await ProcessMessageAsync(receivedMessage, cancellationToken);

			_log.Info("- 4 - Message Processed: LockToken: " + receivedMessage.LockToken);

			await _client.CompleteAsync(receivedMessage);

			failCounter = 0;
			await Task.Yield();
		}
		catch (OperationCanceledException ex)
		{
			_log.Warn(String.Format("OperationCanceledException occured: {0}", ex));
			throw new Exception(ex.Message);
		}
		catch (IotHubException ex)
		{
			_log.Warn(string.Format("IotHubException occured: {0}", ex));

			failCounter++;

			if (failCounter < 2)
			{
				_log.Info("IotHubException occured - Create new Device Client an try again");
				await CreateDeviceClient();
			}
			else
			{
				_log.Warn("IotHubException occured - failCounter >= 2 - Throw Exception and Stop Service");
				throw new Exception(ex.Message);
			}
		}
		catch (Exception ex)
		{
			_log.Error(string.Format("Exception occured: {0}", ex));
			throw new Exception(ex.Message);
		}
		finally
		{
			if (receivedMessage != null)
			{
				// Found here:
				// https://csharp.hotexamples.com/examples/-/DeviceClient/ReceiveAsync/php-deviceclient-receiveasync-method-examples.html
				_log.Info("- 5 - dispose received message");
				receivedMessage.Dispose();
				_log.Info("- 6 - dispose received message done");
			}
		}
	}

	_log.Info("- 99 - Message listener terminated");
}

private static void ConnectionStatusChangeHandler(ConnectionStatus status, ConnectionStatusChangeReason reason)
{
	_log.Info($"[{nameof(Ccc)}] : Connection Status Changed to {status} ({reason}) at {DateTime.Now}");
}
```

Here are some log outputs that are showing the mentioned behaviour:
```
<Application was already running for 1 day>
[...]
2021-11-22 20:25:01,481 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:26:01,491 [28] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:26:01,491 [28] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:26:01,491 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:27:01,503 [30] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:27:01,503 [30] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:27:01,503 [30] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:28:01,512 [16] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:28:01,512 [16] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:28:01,512 [16] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:29:01,527 [28] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:29:01,527 [28] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:29:01,527 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:30:01,540 [28] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:30:01,540 [28] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:30:01,540 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:31:01,552 [28] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:31:01,552 [28] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:31:01,552 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:32:01,563 [89] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:32:01,563 [89] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:32:01,563 [89] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:33:01,584 [88] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-22 20:33:01,584 [88] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-22 20:33:01,584 [88] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-22 20:33:49,326 [10] INFO Aaa.Bbb.Ccc - [Ccc] : Connection Status Changed to Disconnected_Retrying (Communication_Error) at 22.11.2021 20:33:49
2021-11-22 20:33:49,796 [88] INFO Aaa.Bbb.Ccc - [Ccc] : Connection Status Changed to Connected (Connection_Ok) at 22.11.2021 20:33:49
<End of log - Application restart necessary>
```

```
<Application was already running for 3 days>
[...]
2021-11-25 23:40:28,830 [48] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:40:28,830 [48] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:40:28,830 [48] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:41:28,839 [48] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:41:28,839 [48] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:41:28,839 [48] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:42:28,842 [49] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:42:28,842 [49] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:42:28,842 [49] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:43:28,852 [17] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:43:28,852 [17] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:43:28,852 [17] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:44:28,862 [41] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:44:28,862 [41] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:44:28,862 [41] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:45:28,877 [41] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:45:28,877 [41] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:45:28,877 [41] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:46:28,882 [41] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:46:28,882 [41] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:46:28,882 [41] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:47:28,890 [37] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:47:28,890 [37] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:47:28,890 [37] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:48:28,901 [37] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:48:28,901 [37] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:48:28,901 [37] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:49:28,911 [53] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:49:28,911 [53] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:49:28,911 [53] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:50:28,918 [13] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:50:28,918 [13] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:50:28,918 [13] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:51:28,931 [13] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:51:28,931 [13] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:51:28,931 [13] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:52:28,942 [17] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-25 23:52:28,942 [17] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-25 23:52:28,942 [17] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-25 23:53:00,121 [18] INFO Aaa.Bbb.Ccc - [Ccc] : Connection Status Changed to Disconnected_Retrying (Communication_Error) at 25.11.2021 23:53:00
2021-11-25 23:53:00,623 [18] INFO Aaa.Bbb.Ccc - [Ccc] : Connection Status Changed to Connected (Connection_Ok) at 25.11.2021 23:53:00
<End of log - Application restart necessary>
```

```
<Application was already running for 2 days>
[...]
2021-11-27 23:03:55,654 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:04:55,667 [101] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:04:55,667 [101] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:04:55,667 [101] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:05:55,671 [100] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:05:55,671 [100] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:05:55,671 [100] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:06:55,675 [100] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:06:55,675 [100] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:06:55,675 [100] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:07:55,687 [71] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:07:55,687 [71] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:07:55,687 [71] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:08:55,702 [28] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:08:55,702 [28] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:08:55,702 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:09:55,710 [45] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:09:55,710 [45] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:09:55,710 [45] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:10:55,727 [56] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:10:55,727 [56] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:10:55,727 [56] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:11:55,738 [96] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:11:55,738 [96] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:11:55,738 [96] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:12:55,749 [94] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:12:55,749 [94] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:12:55,749 [94] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:13:55,751 [28] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:13:55,751 [28] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:13:55,751 [28] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:14:55,752 [94] INFO Aaa.Bbb.Ccc - - 1 - Listening finished
2021-11-27 23:14:55,753 [94] INFO Aaa.Bbb.Ccc - - 2 - received message null - continue
2021-11-27 23:14:55,753 [94] INFO Aaa.Bbb.Ccc - - 0 - Listening for new message
2021-11-27 23:15:28,762 [94] INFO Aaa.Bbb.Ccc - [Ccc] : Connection Status Changed to Disconnected_Retrying (Communication_Error) at 27.11.2021 23:15:28
2021-11-27 23:15:29,365 [6] INFO Aaa.Bbb.Ccc - [Ccc] : Connection Status Changed to Connected (Connection_Ok) at 27.11.2021 23:15:29
<End of log - Application restart necessary>
```

## Initial solution
We included the IoT Hub source code into our project and found out that the SDK got stuck in MqttTransportHandler.cs when calling _receivingSemaphore?.Dispose();
We added an instruction to release the semaphore as follows (second red box):
![image](https://user-images.githubusercontent.com/71387280/148453840-d23bb144-39fb-4677-b750-d54afe918432.png)

This solved our initial issue. We did not encounter any further problems after connection loss + reconnection attempts. The _client.ReceiveAsync() method is now returning every time.

## New problem
Since we introduced the change, the application is sometimes crashing with the following exception. This did not happen before the change:
```
2022-01-05 09:26:26,288 [45] ERROR Aaa.Bbb.Ccc - Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.ReceiveAsync(CancellationToken cancellationToken) in C:\Users\XXX\Documents\azure-iot-sdk-csharp\iothub\device\src\Transport\Mqtt\MqttTransportHandler.cs:line 310
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in C:\Users\XXX\Documents\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 197
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass18_0.<<ReceiveAsync>b__0>d.MoveNext() in C:\Users\XXX\Documents\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 162
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(CancellationToken cancellationToken) in C:\Users\XXX\Documents\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 157
   at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync() in C:\Users\XXX\Documents\azure-iot-sdk-csharp\iothub\device\src\InternalClient.cs:line 1259
   at Aaa.Bbb.Ccc.ListenAsync(CancellationToken cancellationToken) in C:\Users\XXX\source\repos\AslpEdgePrinting\src\Aaa.Bbb\Ccc.cs:line 255
```

At this point we are not sure if it is a good idea to release the semaphore, as we are doing right now, or if there is a better solution for this problem.

**Comment by drwill-ms** [comment]
Hi @mkortemeier - thanks so much for your issue report and with so much detail. It really helps us do a better job of helping you.

I've looked over your post and would like to know the contents of the method `CreateDeviceClient()`. Would you mind sharing that?

I also have a few ideas for you in the meantime:

1. We have a canonical sample for how to handle `DeviceClient` lifetime and connection status. If you haven't seen it, please check it out [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/main/iot-hub/Samples/device/DeviceReconnectionSample).
  - Pay special attention to the logic in the connection status callback and the conditions under which it recreates the client. The code above recreates the client more aggressively than this and may lead to issues.
  - It is important to call `CloseAsync()` on the device client before disposing. It shuts down the protocol layer, which prevents ongoing SDK retries. This may be why the `_receivingSemaphore` still has count. The SDK needs to shutdown gracefully or you could see errors, like the `NullReferenceException` you noticed.
  - When making device client calls, exceptions may be thrown after retries have been exhausted or in other specific conditions. In some cases, one should retry the operation, and in others it indicates the device client transport is in a bad state and needs to be reinitialized.  The [RetryOperationHelper](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/main/iot-hub/Samples/device/DeviceReconnectionSample/RetryOperationHelper.cs) class is one you can borrow and use to help make that determination.
2. The call to `ReceiveAsync()` will not return until a C2D message is detected. A better alternative is to use the flavor with a `CancellationToken` parameter. You can specify how long you're willing to wait for and it will cancel. Our sample shows an [example](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/main/iot-hub/Samples/device/DeviceReconnectionSample/DeviceReconnectionSample.cs#L311) of how to do that.
  - Note: the sample code handles differences in MQTT, AMQP, and HTTP. Based on your call stack above, I see that you are using MQTT, so you only need to code for that protocol.
3. Another, perhaps even better, option is to use the _somewhat_ new callback for C2D messages. Here's another [sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/main/iot-hub/Samples/device/MessageReceiveSample/MessageReceiveSample.cs#L55) that shows how to get C2D messages that way.
  - I like this one because events are better than polling, and you don't have to worry about getting exceptions when calling `ReceiveAsync()`.

**Comment by drwill-ms** [comment]
@mkortemeier I'm checking in with you again today. Did you get a chance to review my previous response?

Regards,
David

**Comment by mkortemeier** [comment]
Hi @drwill-ms,

Thanks for your detailed repsonse. Our `CreateDeviceClient()` looks like this:

```
private Task CreateDeviceClient()
{
	if (_client != null)
	{
		_client.CloseAsync();
	}

	var transportSettings = CreateTransportSettings();
	_client = DeviceClient.CreateFromConnectionString(_clientConnectionString, transportSettings.ToArray());
	_log.Info("- 6 - StartAsync: new Client created. ");
}

private List<ITransportSettings> CreateTransportSettings()
{
	var proxySettings = new MqttTransportSettings(TransportType.Mqtt_WebSocket_Only);
	try
	{
		if (_useProxy)
		{
			_log.Info(String.Format("[{0}] Applying proxy configuration from appsettings", nameof(Ccc)));
			proxySettings.Proxy = _useDefaultProxy ?
				Xxx.Yyy.CreateDefaultProxy() : Xxx.Yyy.CreateCustomProxy(_serverUri, _username, _password, _proxyPort);
		}
	}
	catch (Exception ex)
	{
		_log.Error(String.Format("[{0}] Unable to set up proxy: {1}", nameof(Ccc), ex.ToString()));
	}

	return new List<ITransportSettings> { proxySettings };
}
```

After reviewing your suggestions I think option 3 (callback for C2D messages) looks very promising. We decided to implement the callback method and monitor the situation, to see if this solves out intial issue.

Thanks + Best Regards,
Mike

**Comment by drwill-ms** [comment]
@mkortemeier thanks for sharing. Here are some important tips for improving the `CreateDeviceClient()` method.

1. Make it async, and await the call to `_client.CloseAsync()`, otherwise the new client is being created while the old one is still closing, which could cause issues, depending on timing.
1. Call `_client.Dispose()` after closing, otherwise your app will suffer memory leaks.
1. Consider protecting client initialization so only a single one is created using a semaphore.

   - If this method is ever called more than once at a time, you'll end up with a ghosted client instance that has not been closed and disposed, which will cause a **memory leak** each time that happens.
   - Also, it could end up fighting with the second one to be initialized and that would cause both clients using retry policy to keep stealing the device connection (only one can be active with the IoT hub at any given time).

1. Consider calling `await _client.OpenAsync()` after initialization to ensure the client can connect.

I'll watch for your response and hope to see the issues are resolved.

**Comment by drwill-ms** [comment]
Hi @mkortemeier - I hope the issues you were seeing are resolved. If not, let us know the latest.

Thanks!

**Comment by drwill-ms** [comment]
I'm going to close this issue for now, but feel free to comment back with any results, questions, or further concerns.
