### ISSUE TITLE
Changed behavior/incorrect exception using disposed object

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-csharp#2271]
In EdgeHub we use the client.ReceiveAsync() method which is being called in a loop. In certain situation it can happen that a client device got disconnected (which makes a DeviceClient object representing that client get disposed) but this loop runs again, and it can happen with a really bad timing: the client object gets disposed the time of the ReceiveAsync() call.

in version 1.33.x (the version EdgeHub used to reference) correctly threw an object disposed exception in this case, also the repeated calls threw that exception.

The current 1.36.3 we use, throws different exceptions:
- the first call is a "System.InvalidOperationException: Invalid transport state: Closed"
- subsequent calls "System.NullReferenceException: Object reference not set to an instance of an object."

The major problem is not the type of the exception: when the new exception happens, the mqtt protocol head we provide for client devices and driven by dotnetty becomes extremely slow or even frozen, preventing clients to connect. I am not quite sure at this moment that the "invalid transport state" may cause a lock or something in dotnetty to cause this. When you investigate the problem with the exceptions, please also provide your opinion about this.

This is an ongoing investigation regarding an IcM.

this is an example code that repros the problem:

```
            var transportSettings = new MqttTransportSettings(Microsoft.Azure.Devices.Client.TransportType.Mqtt_Tcp_Only);

            var milestone = new SemaphoreSlim(0, 1);
            var disposeDone = false;

            var client = Microsoft.Azure.Devices.Client.DeviceClient.CreateFromConnectionString("HostName=<somehub>.azure-devices.net;DeviceId=dev_c;SharedAccessKey=<somekey>", new ITransportSettings[] { transportSettings });
            await client.OpenAsync();

            for (var i = 1; i < 10; i++)
            {
                try
                {
                    if (!disposeDone)
                    {
                        _ = Task.Run(async () =>
                        {
                            milestone.Release();
                            client.Dispose();
                            disposeDone = true;
                        });
                    }

                    if (!disposeDone)
                    {
                        await milestone.WaitAsync();
                    }
                    Console.WriteLine($"entering {i}. call");
                    _ = await client.ReceiveAsync(TimeSpan.FromSeconds(5));
                    //_ = await client.ReceiveAsync();

                    Console.Write(".");
                }
                catch (Exception e)
                {
                    Console.WriteLine("\n\ngot this: " + e);                  
                }

                await Task.Delay(TimeSpan.FromSeconds(1));
            }
        }
```

this is the result using 1.33.1:

```
entering 1. call


got this: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IoT Client'.
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.ThrowIfDisposed()
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>n__4(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass19_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync(TimeSpan timeout)
   at SdkIoTClient.Program.C2DTortureAsync() in D:\Dev\QuickTests\SdkIoTClient\Program.cs:line 242
entering 2. call


got this: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IoT Client'.
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.ThrowIfDisposed()
   at Microsoft.Azure.Devices.Client.Transport.DefaultDelegatingHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>n__4(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass19_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync(TimeSpan timeout)
   at SdkIoTClient.Program.C2DTortureAsync() in D:\Dev\QuickTests\SdkIoTClient\Program.cs:line 242
```

this is the result using 1.36.3:

```
entering 1. call


got this: System.InvalidOperationException: Invalid transport state: Closed
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.EnsureValidState(Boolean throwIfNotOpen)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass19_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.ReceiveAsync(TimeoutHelper timeoutHelper)
   at Microsoft.Azure.Devices.Client.InternalClient.ReceiveAsync(TimeSpan timeout)
   at SdkIoTClient.Program.C2DTortureAsync() in D:\Dev\QuickTests\SdkIoTClient\Program.cs:line 242
entering 2. call


got this: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.DeviceClient.ReceiveAsync(TimeSpan timeout)
   at SdkIoTClient.Program.C2DTortureAsync() in D:\Dev\QuickTests\SdkIoTClient\Program.cs:line 242
```

**Comment by vipeller** [comment]
This may help, found with my debugging the original problem. The context is that when the problem I described above happens, then the mqtt protocol head of edgeHub stops accepting new connections. It seems that with this problem something starts eating up threads as they always get locked.

![image](https://user-images.githubusercontent.com/51135538/148863913-850a8b73-94de-4b53-b592-b3307ede9452.png)

**Comment by azabbasi** [comment]
@vipeller 
So the reason you see two types of exceptions is that Disposal of device client takes time and since your call to ReceiveAsync comes in immediately after the call to Dispose, internally not everything is closed up but the MQTT connection has closed down so the invalid transport state exception is thrown. If instead of `client.Dispose()` you call `await client.DisposeAsync()` then you will see a consistent pattern of exceptions that bubble up. Unfortunately the exception that bubbles up is a NRE which not ideal and I will have to talk to my team about it. Ideally we should be throwing a ObjectDisposedException in this case.

`await DisposeAsync()` is broken down into `await CloseAsync()` and then `Dispose()` which is the alternative you can use. So if you call `await CloseAsync()` before `Dispose()` you should be good. 
I am curious if that also resolves your issue with the worker threads and how it causes the subsequent client calls to be slow.

**Comment by azabbasi** [comment]
We have released a new patch for the LTS version on device client [here](https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2021_03_18-patch4). 
It addresses the incorrect exception issue that was mentioned in the description.

**Comment by azabbasi** [comment]
The LTS version is patched and the changes are also present in the 1.40.0 version that was recently published. Closing the issue.
