### ISSUE TITLE
[Bug Report] NRE in MqttTransportHandler

### ISSUE THREAD

**Issue by ravi-shaw** [Azure/azure-iot-sdk-csharp#2281]
# Context

- **OS, version, SKU and CPU architecture used:**  Windows 10 Desktop x64 Version 10.0.18363 Build 18363, 0906, 
- **Application's .NET Target Framework :** net 5.0
- **Device:** Laptop
- **SDK version used:** 1.39.0 

## Description of the issue
DeviceClient object is throwing exception "Object reference not set to an instance of an object", event though there is a null check for device client object.  This exception is coming at SetReceiveMessageHandlerAsync operation. Only few times we are getting exception. Most of the time it works fine.

## Code sample exhibiting the issue
                IotDeviceClient = DeviceClient.CreateFromConnectionString(connectionString, GetTransportSettings(), options);
                if (IotDeviceClient == null)
                    return false;

                IotDeviceClient.SetConnectionStatusChangesHandler(ConnectionStatusChangeEventHandler);
                await IotDeviceClient.SetReceiveMessageHandlerAsync(RecieveCloudToDeviceMessageAsync, null);
                await IotDeviceClient.SetDesiredPropertyUpdateCallbackAsync(RecieveDesiredPropertyChangeAsync, null);

## Console log of the issue
System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=Microsoft.Azure.Devices.Client
StackTrace:
at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<EnableReceiveMessageAsync>d__84.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__28`1.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass20_0.<<EnableReceiveMessageAsync>b__0>d.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<EnableReceiveMessageAsync>d__20.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Devices.Client.InternalClient.<SetReceiveMessageHandlerAsync>d__96.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Azure.Devices.Client.InternalClient.<SetReceiveMessageHandlerAsync>d__96.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by abhipsaMisra** [comment]
The code you've shared above doesn't highlight any issue that would cause an NRE to be thrown. Would you be able to capture the SDK logs following the steps [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs) and share them with us?

**Comment by abhipsaMisra** [comment]
@ravi-shaw Is this still an issue that you're seeing? Were you able to capture the SDK logs?

**Comment by abhipsaMisra** [comment]
Closing due to lack of response. 
@ravi-shaw If you run into this issue again, feel free to reopen the issue with the relevant logs.
