### ISSUE TITLE
[Bug Report] InvokeDeviceMethodAsync throws exception when no moduleId and CloudToDeviceMethod has payloadJson

### ISSUE THREAD

**Issue by rtheil-growlink** [Azure/azure-iot-sdk-csharp#2321]
# Context
- Windows 10 Desktop x64
- **Application's .NET Target Framework :** 4.7.2
- **Device:** Desktop PC
- **SDK version used:** 1.36.0 or 1.37.0 and default dependency version requirements

## Description of the issue
We've been running this for years and works great for Azure edge devices, but I am working to implement non-edge Azure devices and when making a call to InvokeDeviceMethodAsync( string, CloudToDeviceMethod ) after adding a payload to the CloudToDeviceMethod object with SetPayloadJson, it throws an exception with this message

{"Message":"The requested resource does not support http method 'POST'."}

This issue does not occur when calling the overload for InvokeDeviceMethodAsync that requires the moduleId. We can't use this because these newer devices do not have any modules.

stack trace
```
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__36.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<ExecuteAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.HttpClientHelper.<PostAsync>d__26`2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Hydropods.ControllerServices.AzureEdge.AzureDeviceClient.<InvokeDirectMethod>d__3.MoveNext() in ...\AzureEdge\AzureDeviceClient.cs:line 56
```
## Code sample exhibiting the issue
```
var _serviceClient = ServiceClient.CreateFromConnectionString( connectionString );
var cloudToDeviceMethod = new CloudToDeviceMethod( "switchDevice");
cloudToDeviceMethod.SetPayloadJson( "\"000000000000d6b8,3,false\"" );
await _serviceClient.InvokeDeviceMethodAsync( deviceId, cloudToDeviceMethod );
```

**Comment by rtheil-growlink** [comment]
After some lengthy troubleshooting, the solution here is that deviceId was null. Just a strange error for some missing info.

**Comment by drwill-ms** [comment]
I'm submitting a PR to fix the parameter validation. Thanks @rtheil-growlink.
