### ISSUE TITLE
[Bug Report] Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred when NetworkMode = "host"

### ISSUE THREAD

**Issue by wiltonkkw** [Azure/azure-iot-sdk-csharp#2356]
# Context

- **OS, version, SKU and CPU architecture used:** Ubuntu 20.04 x86
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client (1.40.0)

## Description of the issue
I'm using Ubuntu 20.04 and setting the network mode to "host" since I need to access the network interface (CAN interface) from the host. I can get the interfaces but ModuleClient got network error.

After adding the options in my custom edge module:
```
                "NetworkingConfig": {
                    "EndpointsConfig": {
                         "host": {}
                    }
                },
                "HostConfig": {
                    "NetworkMode": "host"
                }
```
The edge module can access the network interface from the host. But got the follow error when executing
```
            var _ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await _ioTHubModuleClient.OpenAsync();
```
Error message:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.OpenInternalAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(Boolean withRetry, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at InzightEdge.Program.Init() in /app/Program.cs:line 72
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at InzightEdge.Program.Main(String[] args) in /app/Program.cs:line 32
```
If the Network Mode set to **default**, the error is gone.

The DNS of the **Container Create Options** is:
```
{
   :
   :
   "Dns": [
       "1.1.1.1",
       "8,8,8,8",
       "192.168.1.1"
   ]
}
```
In the container, it can access external URL using **curl** but have error when opening ModuleClient.

## Code sample exhibiting the issue
Please remove any connection string information!

## Console log of the issue
```
2022-04-22T12:39:19.7835657 [Microsoft-Azure-Devices-Device-Client-Info] (RetryDelegatingHandler#4515895, EnsureOpenedAsync, Opening connection).
2022-04-22T12:39:19.7873536 [Microsoft-Azure-Devices-Device-Client-Enter] (RetryDelegatingHandler#4515895, OpenAsync, (CancellationToken#45788532)).
2022-04-22T12:39:19.7892144 [Microsoft-Azure-Devices-Device-Client-Enter] (ErrorDelegatingHandler#3862624, ExecuteWithErrorHandlingAsync, ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync).
2022-04-22T12:39:19.7902453 [Microsoft-Azure-Devices-Device-Client-Enter] (ProtocolRoutingDelegatingHandler#29456748, ProtocolRoutingDelegatingHandler.OpenAsync, (CancellationToken#45788532)).
2022-04-22T12:39:19.7907340 [Microsoft-Azure-Devices-Device-Client-Info] (ProtocolRoutingDelegatingHandler#29456748, ProtocolRoutingDelegatingHandler.OpenAsync, Trying Mqtt_Tcp_Only).
2022-04-22T12:39:19.7908955 [Microsoft-Azure-Devices-Device-Client-Info] (PipelineContext#65330082, Set, ITransportSettings = MqttTransportSettings#22639330).
2022-04-22T12:39:19.7933933 [Microsoft-Azure-Devices-Device-Client-Associate] (MqttTransportHandler#29112358, InnerHandler, MqttTransportHandler#29112358, (null)).
2022-04-22T12:39:19.7939966 [Microsoft-Azure-Devices-Device-Client-Associate] (ProtocolRoutingDelegatingHandler#29456748, InnerHandler, ProtocolRoutingDelegatingHandler#29456748, MqttTransportHandler#29112358).
2022-04-22T12:39:19.7946522 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttTransportHandler#29112358, OpenAsync, (CancellationToken#45788532)).
2022-04-22T12:39:29.8205769 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttTransportHandler#29112358, OpenAsync, CancellationToken#45788532).
2022-04-22T12:39:29.8213139 [Microsoft-Azure-Devices-Device-Client-Exit] (ProtocolRoutingDelegatingHandler#29456748, ProtocolRoutingDelegatingHandler.OpenAsync, CancellationToken#45788532).
2022-04-22T12:39:29.8391699 [Microsoft-Azure-Devices-Device-Client-ErrorMessage] (ErrorDelegatingHandler#3862624, ExecuteWithErrorHandlingAsync, Exception caught: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)).
2022-04-22T12:39:29.8428701 [Microsoft-Azure-Devices-Device-Client-Exit] (ErrorDelegatingHandler#3862624, ExecuteWithErrorHandlingAsync, ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync).
2022-04-22T12:39:29.8446691 [Microsoft-Azure-Devices-Device-Client-Info] (RetryDelegatingHandler#4515895, HandleConnectionStatusExceptions, Received exception: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenInternalAsync>b__0>d.MoveNext(), connectFailed=False).
2022-04-22T12:39:29.8451128 [Microsoft-Azure-Devices-Device-Client-Enter] (InternalClient#13009416, OnConnectionStatusChanged, (Disconnected_Retrying, Communication_Error)).
2022-04-22T12:39:29.8452580 [Microsoft-Azure-Devices-Device-Client-Exit] (InternalClient#13009416, OnConnectionStatusChanged, Disconnected_Retrying, Communication_Error).
2022-04-22T12:39:29.8453037 [Microsoft-Azure-Devices-Device-Client-Info] (RetryDelegatingHandler#4515895, HandleConnectionStatusExceptions, Connection status change: status=Disconnected_Retrying, reason=Communication_Error).
2022-04-22T12:39:29.8453986 [Microsoft-Azure-Devices-Device-Client-Exit] (RetryDelegatingHandler#4515895, OpenAsync, CancellationToken#45788532).
2022-04-22T12:39:29.8482693 [Microsoft-Azure-Devices-Device-Client-Enter] (RetryStrategyAdapter#41728762, RetryStrategyAdapter.ShouldRetry, (0, Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenInternalAsync>b__0>d.MoveNext())).
2022-04-22T12:39:29.8487217 [Microsoft-Azure-Devices-Device-Client-Exit] (RetryStrategyAdapter#41728762, ShouldRetry, RetryStrategyAdapter.ShouldRetry).
2022-04-22T12:39:29.9503862 [Microsoft-Azure-Devices-Device-Client-Enter] (RetryDelegatingHandler#4515895, OpenAsync, (CancellationToken#45788532)).
2022-04-22T12:39:29.9508671 [Microsoft-Azure-Devices-Device-Client-Enter] (ErrorDelegatingHandler#3862624, ExecuteWithErrorHandlingAsync, ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync).
2022-04-22T12:39:29.9511993 [Microsoft-Azure-Devices-Device-Client-Enter] (ProtocolRoutingDelegatingHandler#29456748, ProtocolRoutingDelegatingHandler.OpenAsync, (CancellationToken#45788532)).
2022-04-22T12:39:29.9515238 [Microsoft-Azure-Devices-Device-Client-Info] (ProtocolRoutingDelegatingHandler#29456748, ProtocolRoutingDelegatingHandler.OpenAsync, Trying Mqtt_Tcp_Only).
2022-04-22T12:39:29.9517753 [Microsoft-Azure-Devices-Device-Client-Info] (PipelineContext#65330082, Set, ITransportSettings = MqttTransportSettings#22639330).
2022-04-22T12:39:29.9536125 [Microsoft-Azure-Devices-Device-Client-Associate] (MqttTransportHandler#2174563, InnerHandler, MqttTransportHandler#2174563, (null)).
2022-04-22T12:39:29.9539964 [Microsoft-Azure-Devices-Device-Client-Associate] (ProtocolRoutingDelegatingHandler#29456748, InnerHandler, ProtocolRoutingDelegatingHandler#29456748, MqttTransportHandler#2174563).
2022-04-22T12:39:29.9562384 [Microsoft-Azure-Devices-Device-Client-Info] (MqttTransportHandler#29112358, OnTransportClosedGracefully, OnTransportClosedGracefully).
2022-04-22T12:39:29.9621659 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttTransportHandler#2174563, OpenAsync, (CancellationToken#45788532)).
2022-04-22T12:39:39.9743801 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttTransportHandler#2174563, OpenAsync, CancellationToken#45788532).
2022-04-22T12:39:39.9764688 [Microsoft-Azure-Devices-Device-Client-Exit] (ProtocolRoutingDelegatingHandler#29456748, ProtocolRoutingDelegatingHandler.OpenAsync, CancellationToken#45788532).
2022-04-22T12:39:39.9886958 [Microsoft-Azure-Devices-Device-Client-ErrorMessage] (ErrorDelegatingHandler#3862624, ExecuteWithErrorHandlingAsync, Exception caught: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)).
2022-04-22T12:39:39.9903457 [Microsoft-Azure-Devices-Device-Client-Exit] (ErrorDelegatingHandler#3862624, ExecuteWithErrorHandlingAsync, ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync).
2022-04-22T12:39:39.9954546 [Microsoft-Azure-Devices-Device-Client-Info] (RetryDelegatingHandler#4515895, HandleConnectionStatusExceptions, Received exception: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenInternalAsync>b__0>d.MoveNext(), connectFailed=False).
2022-04-22T12:39:39.9963713 [Microsoft-Azure-Devices-Device-Client-Enter] (InternalClient#13009416, OnConnectionStatusChanged, (Disconnected_Retrying, Communication_Error)).
2022-04-22T12:39:39.9967785 [Microsoft-Azure-Devices-Device-Client-Exit] (InternalClient#13009416, OnConnectionStatusChanged, Disconnected_Retrying, Communication_Error).
2022-04-22T12:39:39.9972033 [Microsoft-Azure-Devices-Device-Client-Info] (RetryDelegatingHandler#4515895, HandleConnectionStatusExceptions, Connection status change: status=Disconnected_Retrying, reason=Communication_Error).
2022-04-22T12:39:39.9978028 [Microsoft-Azure-Devices-Device-Client-Exit] (RetryDelegatingHandler#4515895, OpenAsync, CancellationToken#45788532).
2022-04-22T12:39:40.0019419 [Microsoft-Azure-Devices-Device-Client-Enter] (RetryStrategyAdapter#41728762, RetryStrategyAdapter.ShouldRetry, (1, Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenInternalAsync>b__0>d.MoveNext())).
```

**Comment by bqstony** [comment]
I get also sometimes, every 2-3 weeks a `Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.`. I am running on Ubuntu 20.04 Host behind a proxy with regular network settings. 

For me the error is happen when a Device to cloud message should be send. 

**context**
OS, version, SKU and CPU architecture used: Ubuntu 20.04 x64
Application's .NET Target Framework : net6.0
SDK version used: Microsoft.Azure.Devices.Client (1.40.0)

Here is the stacktrace, i hope this can help

```
[2022-04-25 07:10:16.875 +00:00 ERR] Connection id "0HMGS9ASJNV8T", Request id "0HMGS9ASJNV8T:00000002": An unhandled exception was thrown by the application. <s:Microsoft.AspNetCore.Server.Kestrel>
Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.<>c.<SendMessageAsync>b__12_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpIotSendingLink.SendAmqpMessageAsync(AmqpMessage amqpMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpIotSendingLink.SendMessageAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpUnit.SendMessageAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIot.AmqpUnit.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass16_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at BeaconTelemetryConverter.Bar.ProtoTelemetryPublisher.SendEventAsync(String dataSubject, Message message, CancellationToken cancellationToken) in /app/fooIotEdge/modules/BeaconTelemetryConverter/Bar/ProtoTelemetryPublisher.cs:line 87
   at BeaconTelemetryConverter.Bar.ProtoTelemetryPublisher.SendEventAsync[T](String dataSubject, T dataMessage, CancellationToken cancellationToken) in /app/fooIotEdge/modules/BeaconTelemetryConverter/Bar/ProtoTelemetryPublisher.cs:line 81
   at BeaconTelemetryConverter.Controllers.fooWebSocketHandler.AddSocketAsync(WebSocket webSocket, HttpContext httpContext, CancellationToken cancellationToken) in /app/fooIotEdge/modules/BeaconTelemetryConverter/Controllers/fooWebSocketHandler.cs:line 218
   at BeaconTelemetryConverter.Controllers.fooWebSocketController.Get(CancellationToken cancellationToken) in /app/fooIotEdge/modules/BeaconTelemetryConverter/Controllers/fooWebSocketController.cs:line 44
   at lambda_method14(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by drwill-ms** [comment]
@varunpuranik Any insight here on the NetworkMode deployment settings for a module?

**Comment by varunpuranik** [comment]
@bqstony - are you seeing this error in your module, or in EdgeHub module? In any case, this error is different from what wiltonkkw is seeing, and most likely a transient error. Does retry make the issue go away?

**Comment by wiltonkkw** [comment]
@varunpuranik 
I have checked the file /etc/aziot/config.toml. No hostname is specified. Is that a problem? The content of /etc/hostname is "ubuntu"

```
auto_reprovisioning_mode = "OnErrorOnly"

[provisioning]
source = "manual"
connection_string = "HostName=xxxxx="

[aziot_keys]

[preloaded_keys]

[cert_issuance]

[preloaded_certs]

[agent]
name = "edgeAgent"
type = "docker"
imagePullPolicy = "on-create"

[agent.config]
image = "mcr.microsoft.com/azureiotedge-agent:1.2"

[agent.config.createOptions]

[agent.env]

[connect]
workload_uri = "unix:///var/run/iotedge/workload.sock"
management_uri = "unix:///var/run/iotedge/mgmt.sock"

[listen]
workload_uri = "fd://aziot-edged.workload.socket"
management_uri = "fd://aziot-edged.mgmt.socket"
min_tls_version = "tls1.0"

[watchdog]
max_retries = "infinite"

[moby_runtime]
uri = "unix:///var/run/docker.sock"
network = "azure-iot-edge"
```

**Comment by bqstony** [comment]
> @bqstony - are you seeing this error in your module, or in EdgeHub module? In any case, this error is different from what wiltonkkw is seeing, and most likely a transient error. Does retry make the issue go away?

After restart of the Module the error goes away

**Comment by wiltonkkw** [comment]
> @varunpuranik I have checked the file /etc/aziot/config.toml. No hostname is specified. Is that a problem? The content of /etc/hostname is "ubuntu"
> 
> ```
> auto_reprovisioning_mode = "OnErrorOnly"
> 
> [provisioning]
> source = "manual"
> connection_string = "HostName=xxxxx="
> 
> [aziot_keys]
> 
> [preloaded_keys]
> 
> [cert_issuance]
> 
> [preloaded_certs]
> 
> [agent]
> name = "edgeAgent"
> type = "docker"
> imagePullPolicy = "on-create"
> 
> [agent.config]
> image = "mcr.microsoft.com/azureiotedge-agent:1.2"
> 
> [agent.config.createOptions]
> 
> [agent.env]
> 
> [connect]
> workload_uri = "unix:///var/run/iotedge/workload.sock"
> management_uri = "unix:///var/run/iotedge/mgmt.sock"
> 
> [listen]
> workload_uri = "fd://aziot-edged.workload.socket"
> management_uri = "fd://aziot-edged.mgmt.socket"
> min_tls_version = "tls1.0"
> 
> [watchdog]
> max_retries = "infinite"
> 
> [moby_runtime]
> uri = "unix:///var/run/docker.sock"
> network = "azure-iot-edge"
> ```

I tried adding hostname (both localhost and ubuntu) in the config.toml file. But still not work.

**Comment by wiltonkkw** [comment]
When I take away the DNS in the CreateOptions. It works perfectly
```
        "Dns": [
            "1.1.1.1"
        ]
```
