### ISSUE TITLE
[Bug Report] 1.41.0 Error sending messages to module

### ISSUE THREAD

**Issue by zachcdr** [Azure/azure-iot-sdk-csharp#2449]
## Expected Behavior
Edge hub routes message to the module
Module processes and returns `MessageResponse.Completed`
Edge hub does not retry message

## Current Behavior
Edge hub routes message to the module
Module processes and returns `MessageResponse.Completed`
Edge hub retries the message over and over, on 90-second intervals (blocking all other messages in queue)

## Logs
<details>
<summary>edge-hub logs</summary>

```
<!--
<4> 2022-06-15 16:45:45.218 +00:00 [WRN] - Received unknown feedback message from <module> with lock token <token> and status Complete. Abandoning message.
<4> 2022-06-15 16:46:14.969 +00:00 [WRN] - Did not receive ack for message 58baec18-726a-4229-ad63-4614e82ecc28 from device/module <module>
<4> 2022-06-15 16:46:14.969 +00:00 [WRN] - Error sending messages to module <module>
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 494
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
-->
```
</details>

<details>
<summary>edge-hub logs after restart</summary>

```
<!--
<6> 2022-06-16 15:03:50.130 +00:00 [INF] - Termination requested, initiating shutdown.
<6> 2022-06-16 15:03:50.130 +00:00 [INF] - Stopping the protocol heads...
<6> 2022-06-16 15:03:50.130 +00:00 [INF] - Closing protocol heads - (MQTT, AMQP, HTTP)
<6> 2022-06-16 15:03:50.131 +00:00 [INF] - Stopping
<6> 2022-06-16 15:03:50.144 +00:00 [INF] - Closing HTTP head
<6> 2022-06-16 15:03:50.147 +00:00 [INF] - Closed HTTP head
<6> 2022-06-16 15:03:50.147 +00:00 [INF] - Waiting for cleanup to finish
2022-06-16 15:04:00  Starting Edge Hub
2022-06-16 15:04:01.050 +00:00 Edge Hub Main()
<6> 2022-06-16 15:04:01.871 +00:00 [INF] - Installing certificates <certificate> to Root
<6> 2022-06-16 15:04:01.909 +00:00 [INF] - Installing certificates <certificate> to Root
<6> 2022-06-16 15:04:01.917 +00:00 [INF] - Enabling SSL protocols: Tls, Tls11, Tls12
<6> 2022-06-16 15:04:02.054 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<6> 2022-06-16 15:04:02.467 +00:00 [INF] - Created persistent store at /tmp/edgeHub
<6> 2022-06-16 15:04:02.505 +00:00 [INF] - Initializing Edge Hub
<6> 2022-06-16 15:04:02.505 +00:00 [INF] - 
        ââââââ âââââââââââ   ââââââââââ ââââââââ
       âââââââââââââââââââ   âââââââââââââââââââ
       ââââââââ  âââââ âââ   âââââââââââââââââ
       ââââââââ âââââ  âââ   âââââââââââââââââ
       âââ  âââââââââââââââââââââââ  âââââââââââ
       âââ  âââââââââââ âââââââ âââ  âââââââââââ

 âââ âââââââ âââââââââ    âââââââââââââââ  âââââââ ââââââââ
 âââââââââââââââââââââ    ââââââââââââââââââââââââ ââââââââ
 ââââââ   âââ   âââ       ââââââ  âââ  ââââââ  ââââââââââ
 ââââââ   âââ   âââ       ââââââ  âââ  ââââââ   âââââââââ
 ââââââââââââ   âââ       âââââââââââââââââââââââââââââââââ
 âââ âââââââ    âââ       âââââââââââââââ  âââââââ ââââââââ

<6> 2022-06-16 15:04:02.507 +00:00 [INF] - Version - 1.1.8.48502653 (54b31809c98ee83e36679ecf92c5582de37172c4)
<6> 2022-06-16 15:04:02.507 +00:00 [INF] - OptimizeForPerformance=True
<6> 2022-06-16 15:04:02.507 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2022-06-16 15:04:02.510 +00:00 [INF] - Loaded server certificate with expiration date of "2022-09-14T15:04:00.0000000+00:00"
<6> 2022-06-16 15:04:02.524 +00:00 [INF] - Using Asp Net server for metrics
<6> 2022-06-16 15:04:02.572 +00:00 [INF] - Created new message store
<6> 2022-06-16 15:04:02.572 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2022-06-16 15:04:02.639 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2022-06-16 15:04:04.064 +00:00 [INF] - Created device scope identities cache
<6> 2022-06-16 15:04:04.069 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2022-06-16 15:04:04.079 +00:00 [INF] - Initialized storing twin manager
<6> 2022-06-16 15:04:04.088 +00:00 [INF] - Initializing configuration
<6> 2022-06-16 15:04:04.103 +00:00 [INF] - New device connection for device <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:04.117 +00:00 [INF] - Client <edgeDevice>/$edgeHub connected to edgeHub, processing existing subscriptions.
<6> 2022-06-16 15:04:04.238 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:04.246 +00:00 [INF] - Attempting to connect to IoT Hub for client <edgeDevice>/$edgeHub via AMQP...
<6> 2022-06-16 15:04:04.708 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2022-06-16 15:04:04.931 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2022-06-16 15:04:04.931 +00:00 [INF] - messagesTo<module>: FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint("/modules/<module>/inputs/input1")
<6> 2022-06-16 15:04:04.931 +00:00 [INF] - <module>ToIoTHub: FROM /messages/modules/<module>/outputs/crate-bundle INTO $upstream
<6> 2022-06-16 15:04:04.932 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2022-06-16 15:04:04.933 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2022-06-16 15:04:04.957 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2022-06-16 15:04:04.958 +00:00 [INF] - Initialized edge hub configuration
<6> 2022-06-16 15:04:04.966 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2022-06-16 15:04:05.029 +00:00 [INF] - Scheduling server certificate renewal for "2022-09-14T15:01:30.0000885Z".
<6> 2022-06-16 15:04:05.030 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2022-06-16 15:04:05.032 +00:00 [INF] - Starting MQTT head
<6> 2022-06-16 15:04:05.091 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2022-06-16 15:04:05.148 +00:00 [INF] - Exiting disconnected state
<6> 2022-06-16 15:04:05.170 +00:00 [INF] - Received device connected callback
<6> 2022-06-16 15:04:05.177 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2022-06-16 15:04:05.179 +00:00 [INF] - Processing subscriptions for client <edgeDevice>/$edgeHub on device connected to cloud.
<6> 2022-06-16 15:04:05.179 +00:00 [INF] - Skipping <edgeDevice>/$edgeHub for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:04:05.193 +00:00 [INF] - Entering connected state
<6> 2022-06-16 15:04:05.196 +00:00 [INF] - Cloud connection for <edgeDevice>/$edgeHub is True
<6> 2022-06-16 15:04:05.199 +00:00 [INF] - Connection status for <edgeDevice>/$edgeHub changed to ConnectionEstablished
<6> 2022-06-16 15:04:05.207 +00:00 [INF] - Client <edgeDevice>/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2022-06-16 15:04:05.207 +00:00 [INF] - Skipping <edgeDevice>/$edgeHub for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:04:05.209 +00:00 [INF] - Created cloud proxy for client <edgeDevice>/$edgeHub via AMQP, with client operation timeout 20 seconds.
<6> 2022-06-16 15:04:05.214 +00:00 [INF] - Starting AMQP head
<6> 2022-06-16 15:04:05.220 +00:00 [INF] - Initialized cloud proxy 133ec3db-685c-4d66-ae66-97a49fb2189d for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:05.232 +00:00 [INF] - Started MQTT head
<6> 2022-06-16 15:04:05.233 +00:00 [INF] - Created cloud connection for client <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:05.385 +00:00 [INF] - Started AMQP head
<6> 2022-06-16 15:04:05.387 +00:00 [INF] - Starting HTTP head
<6> 2022-06-16 15:04:05.495 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/$edgeHub
<4> 2022-06-16 15:04:05.568 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2022-06-16 15:04:05.574 +00:00 [INF] - Started HTTP head
<6> 2022-06-16 15:04:05.584 +00:00 [INF] - Updated reported properties for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:04:05.672 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2022-06-16 15:04:05.768 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - messagesTo<module>: FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint("/modules/<module>/inputs/input1")
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - <module>ToIoTHub: FROM /messages/modules/<module>/outputs/crate-bundle INTO $upstream
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2022-06-16 15:04:05.806 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2022-06-16 15:04:05.956 +00:00 [INF] - Client <edgeDevice>/<module> in device scope authenticated locally.
<6> 2022-06-16 15:04:05.964 +00:00 [INF] - Successfully generated identity for clientId <edgeDevice>/<module> and username <edgeDevice>/<edgeDevice>/<module>/?api-version=2020-09-30&DeviceClientType=.NET%2F1.41.0%20%28.NET%20Core%203.1.26%3B%20Linux%205.4.0-65-generic%20%2373-Ubuntu%20SMP%20Mon%20Jan%2018%2017%3A25%3A17%20UTC%202021%3B%20X64%29
<6> 2022-06-16 15:04:05.970 +00:00 [INF] - ClientAuthenticated, <edgeDevice>/<module>, 6e58d842
<6> 2022-06-16 15:04:06.000 +00:00 [INF] - New device connection for device <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.001 +00:00 [INF] - Client <edgeDevice>/<module> connected to edgeHub, processing existing subscriptions.
<6> 2022-06-16 15:04:06.012 +00:00 [INF] - Bind device proxy for device <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.013 +00:00 [INF] - Binding message channel for device Id <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.032 +00:00 [INF] - Processing subscriptions TwinResponse, ModuleMessages, DesiredPropertyUpdates for client <edgeDevice>/<module>.
<6> 2022-06-16 15:04:06.033 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.040 +00:00 [INF] - Attempting to connect to IoT Hub for client <edgeDevice>/<module> via AMQP...
<6> 2022-06-16 15:04:06.046 +00:00 [INF] - Set subscriptions from session state for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.051 +00:00 [INF] - Processing subscriptions TwinResponse, ModuleMessages, DesiredPropertyUpdates for client <edgeDevice>/<module>.
<6> 2022-06-16 15:04:06.052 +00:00 [INF] - Set subscriptions from session state for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.054 +00:00 [INF] - Processing subscriptions TwinResponse, ModuleMessages, DesiredPropertyUpdates for client <edgeDevice>/<module>.
<6> 2022-06-16 15:04:06.055 +00:00 [INF] - Set subscriptions from session state for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Cloud connection for <edgeDevice>/<module> is True
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Connection status for <edgeDevice>/<module> changed to ConnectionEstablished
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Client <edgeDevice>/<module> connected to cloud, processing existing subscriptions.
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Skipping <edgeDevice>/<module> for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Created cloud proxy for client <edgeDevice>/<module> via AMQP, with client operation timeout 20 seconds.
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Initialized cloud proxy 9704530f-ac86-4288-a3ac-4988c5675ee9 for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.195 +00:00 [INF] - Created cloud connection for client <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.239 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:06.240 +00:00 [INF] - Processing pending subscriptions for <edgeDevice>/<module>
<6> 2022-06-16 15:04:09.270 +00:00 [INF] - Updated reported properties for <edgeDevice>/$edgeHub
<6> 2022-06-16 15:05:03.065 +00:00 [INF] - Client <leafDevice> in device scope authenticated locally.
<6> 2022-06-16 15:05:03.066 +00:00 [INF] - Successfully generated identity for clientId <leafDevice> and username <edgeDevice>/<leafDevice>/?api-version=2020-09-30&DeviceClientType=.NET%2F1.40.0%20%28.NET%206.0.3%3B%20Microsoft%20Windows%2010.0.19044%20WindowsProduct%3A0x00000004%3B%20X64%3B%20%7Bdb4c906c-0f48-4e1c-9957-662bf3106537%7D%29
<6> 2022-06-16 15:05:03.067 +00:00 [INF] - ClientAuthenticated, <leafDevice>, 594816b0
<6> 2022-06-16 15:05:03.068 +00:00 [INF] - New device connection for device <leafDevice>
<6> 2022-06-16 15:05:03.069 +00:00 [INF] - Client <leafDevice> connected to edgeHub, processing existing subscriptions.
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Bind device proxy for device <leafDevice>
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Binding message channel for device Id <leafDevice>
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Attempting to connect to IoT Hub for client <leafDevice> via AMQP...
<6> 2022-06-16 15:05:03.070 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.155 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, C2D for client <leafDevice>.
<6> 2022-06-16 15:05:03.155 +00:00 [INF] - Set subscriptions from session state for <leafDevice>
<6> 2022-06-16 15:05:03.160 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, C2D for client <leafDevice>.
<6> 2022-06-16 15:05:03.161 +00:00 [INF] - Set subscriptions from session state for <leafDevice>
<6> 2022-06-16 15:05:03.244 +00:00 [INF] - Processing subscriptions TwinResponse, Methods, C2D for client <leafDevice>.
<6> 2022-06-16 15:05:03.244 +00:00 [INF] - Set subscriptions from session state for <leafDevice>
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Cloud connection for <leafDevice> is True
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Connection status for <leafDevice> changed to ConnectionEstablished
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Client <leafDevice> connected to cloud, processing existing subscriptions.
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Skipping <leafDevice> for subscription processing, as it is currently being processed.
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Created cloud proxy for client <leafDevice> via AMQP, with client operation timeout 20 seconds.
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Initialized cloud proxy 3946b286-4635-4d77-8f98-a90b548b6010 for <leafDevice>
<6> 2022-06-16 15:05:03.246 +00:00 [INF] - Created cloud connection for client <leafDevice>
<6> 2022-06-16 15:05:03.248 +00:00 [INF] - Start listening for C2D messages for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.351 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.352 +00:00 [INF] - Processing pending subscriptions for <leafDevice>
<6> 2022-06-16 15:05:03.379 +00:00 [INF] - Updated reported properties for <edgeDevice>/$edgeHub
<4> 2022-06-16 15:05:33.505 +00:00 [WRN] - Did not receive ack for message 39db8087-d4e3-4c11-bbd4-d6ef44d0d5ee from device/module <edgeDevice>/<module>
<4> 2022-06-16 15:05:33.507 +00:00 [WRN] - Error sending messages to module <edgeDevice>/<module>
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 491
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, CancellationToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
-->
```
</details>

## Additional Information
This started happening after upgrading the device client SDK from 1.40.0 to 1.41.0. The issue goes away after downgrading back to 1.40.0. Related to [Issue 6448](https://github.com/Azure/iotedge/issues/6448)
![image](https://user-images.githubusercontent.com/9221566/174155519-942b59a0-2c69-4fa1-ad2b-36d6a923d03c.png)

Essentially our module receives a message, transforms the message, and attempts to send the transformed message to many leaf devices via a collection of tasks: 

```
        public static async Task SendMessage<T>(ModuleClient moduleClient, T message, string methodName)
        {
            if (message != null)
            {
                MethodRequest methodRequest = new MethodRequest(methodName, Encoding.UTF8.GetBytes(Converter<T>.ToJson(message)));

                var deviceIds = GetDeviceIds(await moduleClient.GetTwinAsync());

                IEnumerable<Task<bool>> tasks =
                    from deviceId in deviceIds
                    select InvokeMethod(moduleClient, methodRequest, deviceId);

                List<Task<bool>> tasksToRun = tasks.ToList();

                while (tasksToRun.Any())
                {
                    Task<bool> finishedTask = await Task.WhenAny(tasksToRun);
                    tasksToRun.Remove(finishedTask);
                    await finishedTask;
                }
            }
        }

        private static async Task<bool> InvokeMethod(ModuleClient moduleClient, MethodRequest methodRequest, string deviceId)
        {
            var doRetry = true;
            var retryCount = 3;
            var cancelAfter = 3000;
            var attempt = 0;

            while (doRetry && attempt < retryCount)
            {
                var cts = new CancellationTokenSource();
                cts.CancelAfter(cancelAfter);

                try
                {
                    Console.WriteLine($"Invoking direct method on device: {deviceId}");

                    var response = await moduleClient.InvokeMethodAsync(deviceId, methodRequest, cts.Token);

                    Console.WriteLine($"Successfully invoked direct method on device: {deviceId}");

                    doRetry = false;

                }
                catch (OperationCanceledException)
                {
                    Console.WriteLine($"Failed to invoke direct method on device: {deviceId} :: RETRYING");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to invoke direct method on device: {deviceId} :: Exception {ex.Message}");

                    doRetry = false;
                }

                attempt++;
                cancelAfter += 1000;
            }

            return !doRetry;
        }
```

**Comment by shoter** [comment]
I have the same issue.

Currently pushing new build in the pipeline with your workaround to see if it works.

**Comment by drwill-ms** [comment]
Hi @zachcdr -

I'll try to get to this later this week or next. It is going to be a non-trivial setup and debugging scenario, so it'll probably take a while longer than normal.

One small thing I noticed while reviewing your repro code above, is that the cancellation token source is not disposed. It would introduce a small, but growing, memory leak. I'd advise adding the `using` keyword when instantiating it.

In the meantime, if you have a repro setup where it would be easy for you to capture SDK logs, that would be helpful to the investigation. Instructions can be found [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/tools/CaptureLogs).

**Comment by drwill-ms** [comment]
@zachcdr and @shoter - what transport protocol are you using to initialize your module client? AMQP? MQTT? With web socket or TCP?

@zachcdr - could you share the code you have for receiving and dispatching C2D messages (the code that calls `SendMessage<T>()`? I have an idea that the messages are being replayed because the lock token is expiring, which would explain why the C2D message is being sent to the module again. Would also be good to add a stopwatch to measure the time taken to compare before/after the SDK version upgrade, and ensure no exceptions are thrown when completing that message (especially one that indicates the lock token was lost).

**Comment by shoter** [comment]
@drwill-ms 
In my case I was using MQTT over websockets and over tcp. Both options were failing.

Mostly I used over tcp. Once I checked if websockets are going to change anything in new version. Sadly - they did not change anything.

**Comment by drwill-ms** [comment]
My best take based on what we're seeing and inspecting the code is that the C2D messages are taking too long to be completed.

For some reason, with the ModuleClient flow (compared to DeviceClient), the callback asks for a MessageResponse value and then calls `CompleteAsync() or `AbandonAsync()` for you. In other callbacks we have, it is still the responsibility of the callback to make this call.

Because your code doesn't make this call, you can't observe the message lost lock exception that you would otherwise see. When that happens, the message goes back to the queue and is delivered again, again matching what you report above.

Looking at the code, it appears you could choose to return `MessageResponse.None` and the SDK code won't do anything. So, before returning that value, you can make a call to `moduleClient.CompleteAsync(message)` with a try/catch around it to observe any exceptions.

I'd also suggest putting a timer around the code that runs all the device commands to see how long it is taking. You can measure before and after the SDK upgrade and measure several iterations with the same devices to compare how long it takes to run.

**Comment by shoter** [comment]
> @drwill-ms we thought it was something like that at first too. I was able to replicate with responding immediately with `return MessageResponse.Completed`

I had same reasoning few weeks ago and replicated it with the same method :P.

We are not working with @zachcdr on the same project or anything btw.

**Comment by drwill-ms** [comment]
> we thought it was something like that at first too. I was able to replicate with responding immediately with `return MessageResponse.Completed`

Interesting, so you can simply receive a message and respond with `MessageResponse.Completed` and the messages are still redelivered? Sounds like we can simplify the repro code.

**Comment by shoter** [comment]
@drwill-ms 

That's correct. It is important to note as I previously stated that our module was not authenticated. That might be another clue.

**Comment by drwill-ms** [comment]
@shoter what does your module initialization look like if it is not authenticated?

**Comment by shoter** [comment]
`            lock (creationLockObject)
            {
                if (client != null)
                {
                    return;
                }

                var mqttSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);

                ITransportSettings[] settings = { mqttSetting };
                var iotHubModuleClient = ModuleClient.CreateFromEnvironmentAsync(settings).Result;
                iotHubModuleClient.OpenAsync().Wait();
                client = iotHubModuleClient;
            }
`

**Comment by shoter** [comment]
> Ah, create from environment gets its information from environment variables, which includes identity and authentication, I believe.

Probably - dunno.

Remember that it works on previous version of that library as suggested by @zachcdr , This new version only does not work for some reason.

**Comment by wisedev-pstach** [comment]
In newest version it still does not work correctly - I experienced same problems as @shoter mentioned. Downgrading to 1.4.0 resolves problem

**Comment by shoter** [comment]
@drwill-ms When this critical bug is going to be addressed? I think it should have highest priority as it completely denies one an ability to use new version of library.

It is to my complete surprise that bug of such caliber is still not fixed after 3 months.

**Comment by drwill-ms** [comment]
@shoter -

I apologize for the delay. The team has been busy working on a major rev of the clients, while reported bugs with workarounds have been pushed back for now. My assumption here, and this may be an error, was that the ability to stay on an older version was working. Are there features or bug fixes in later versions that you need?

**Comment by simonachmueller** [comment]
I have the same problem, downgrading to 1.4.0 resolves it.

**Comment by drwill-ms** [comment]
@shoter -

I'm back on the case. I have Edge setup to debug; I just need to code up a module or two, deploy, and debug.

One thing I noticed from the logs posted above is that you are running version 1.1.8.48502653. It is worth noting that you are running an old (and no longer supported) version of Edge. It is not quite at the nearest LTS version of [1.1.17](https://github.com/Azure/iotedge/releases/tag/1.1.17), which loses support at the end of this year. I'd recommend at least upgrading to that version, or if you can manage it, all the way to the latest LTS of [1.4](https://github.com/Azure/iotedge/releases/tag/1.4.2). Edge version info can be found [here](https://learn.microsoft.com/azure/iot-edge/version-history#version-history).

In the meantime, can you share a little more info about your configuration?

- What initiates the workstream? Where does the initial message come from that is being routed to your module, another module or a leaf device?
- What does your module routing look like?

Regards,
David

**Comment by drwill-ms** [comment]
@wisedev-pstach and @simonachmueller, perhaps the two of you can help me with some of your repro environment details, as I am unable to repro on the latest device client SDK version as you've all reported. I'm trying to figure out what the difference is in making it repro.

1. What version is your edgeHub and edgeAgent?
   - You'll find this in your deployment manifest, or you can view it from the Azure Portal (view Edge device, click $edgeAgent, inspect "Image URI" value.
1. How are messages getting to your module? From a leaf device via a routing rule? From another module via a module-to-module message? Are any routing rules involved?
1. Do any of your edge modules do anything other than process incoming messages? Do they receive direct method requests? Do they make direct method requests on leaf devices or other modules? Do they send/forward telemetry?
1. What .NET target do you use for your .NET module?

My setup is:

1. Version 1.1.8 for edgeAgent and edgeHub, to match what @shoter has.
1. Version 1.41.0 device/module SDK, to match the version reported that should repro this.
1. An Edge VM running Ubuntu 20.04 LTS.
1. Two modules, one sending telemetry to the other, and the receiver validating it isn't getting messages resent to it.
   - Routing rules as such:
      ```json
          "routes": {
            "ObserverModuleToIoTHub": "FROM /messages/modules/ObserverModule/outputs/* INTO $upstream",
            "TelemetryModuleToIoTHub": "FROM /messages/modules/TelemetryModule/outputs/* INTO BrokeredEndpoint(\"/modules/ObserverModule/inputs/input1\")"
          }
    ```

What am I missing?

Thanks,
David

**Comment by drwill-ms** [comment]
Folks -

We've had several other related issues logged from other customers and were able to repro and debug one of them. From that, we found that C2D could break if a twin or direct method operation happened. I suspect this may be the same issue you are seeing. Would you try this new version of our SDK and see if it still repros for you?

Release: <https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2022-11-16>
NuGet: <https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.41.3>

Thanks,
David

**Comment by drwill-ms** [comment]
Closing this one optimistically. Let us know if you are still able to repro after trying it out on 1.41.3 or higher.
