### ISSUE TITLE
FileUploadE2ETests.FileUpload_X509_SmallFile_Http test failed intermittently for NetStandard

### ISSUE THREAD

**Issue by jasmineymlo** [Azure/azure-iot-sdk-csharp#259]
Failed   Microsoft.Azure.Devices.E2ETests.FileUploadE2ETests.FileUpload_X509_SmallFile_Http
Error Message:
 Test method Microsoft.Azure.Devices.E2ETests.FileUploadE2ETests.FileUpload_X509_SmallFile_Http threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
Stack Trace:
    at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Devices.Client.IAuthorizationProvider.GetPasswordAsync() in D:\jenkins\workspace\csharp-windows-wip\device\Microsoft.Azure.Devices.Client\IotHubConnectionString.Core.cs:line 22
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<ExecuteAsync>d__21.MoveNext() in D:\jenkins\workspace\csharp-windows-wip\device\Microsoft.Azure.Devices.Client\Transport\HttpClientHelper.cs:line 417
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<PostAsync>d__17`2.MoveNext() in D:\jenkins\workspace\csharp-windows-wip\device\Microsoft.Azure.Devices.Client\Transport\HttpClientHelper.cs:line 320
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.<UploadToBlobAsync>d__11.MoveNext() in D:\jenkins\workspace\csharp-windows-wip\device\Microsoft.Azure.Devices.Client\Transport\HttpTransportHandler.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.E2ETests.FileUploadE2ETests.<uploadFile>d__19.MoveNext() in D:\jenkins\workspace\csharp-windows-wip\e2e\Microsoft.Azure.Devices.E2ETests\FileUploadE2ETests.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.E2ETests.FileUploadE2ETests.<FileUpload_X509_SmallFile_Http>d__15.MoveNext() in D:\jenkins\workspace\csharp-windows-wip\e2e\Microsoft.Azure.Devices.E2ETests\FileUploadE2ETests.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by CIPop** [comment]
This is failing on NetCore E2E runs only.

**Comment by labiraus** [comment]
This bug makes the library unusable for x509 authentication with file upload and can be traced to device/Microsoft.Azure.Devices.Client/Transport/HttpClientHelper.cs line 73 (constructor) and 415 (ExecuteAsync).
When the constructor finds itself in a uwp, plc or netstandard1.3 (for core) it ignores whether you have a certificate - so when you get to ExecuteAsync you skip over using the certificate and try and create a password which, because there is no token refresher, throws the above exception.

I've altered the section in my own code to use an HttpClientHandlerin the #else block and managed to successfully upload a file, but I'm more than a bit new to the open source community so haven't made a change to the repository yet.
The change is as follows:
(from line 62 HttpClientHelper.cs)
            HttpClientHandler handler = null;
#if !WINDOWS_UWP && !PCL && !NETSTANDARD1_3
            if (clientCert != null)
            {
                handler = new WebRequestHandler();
                (handler as WebRequestHandler).ClientCertificates.Add(clientCert);
                this.usingX509ClientCert = true;
            }
#else
            if (clientCert != null)
            {
                handler = new HttpClientHandler
                {
                    ClientCertificateOptions = ClientCertificateOption.Manual,
                };
                (handler as HttpClientHandler).ClientCertificates.Add(clientCert);
                this.usingX509ClientCert = true;
            }
#endif
            this.httpClientObj = handler != null ? new HttpClient(handler) : new HttpClient();

**Comment by CIPop** [comment]
Thanks @labiraus for identifying the issue! Feel free to submit a PR with the change that also re-enables the test.

>  I'm more than a bit new to the open source community so haven't made a change to the repository yet.

If you'd like to make this change, start by Fork-ing this repo then cloning the fork on your machine. After you push the change to your fork, you will be able to create a Pull Request (using the GitHub website).

**Comment by zolvarga** [comment]
Closing as it is linked to issue #424

**Comment by KasperHoldum** [comment]
This issue still isn't resolved even though both this issue and the issue referenced (#424) are closed.

Any update on when this will be fixed?

**Comment by CIPop** [comment]
Thanks @KasperHoldum: Looks like the test is still deactivated, pointing at this issue.
