### ISSUE TITLE
AMQP Token doesn't refresh - Intermittently failing : Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.DeviceClient_TokenIsRefreshed_Ok_Amqp 

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#263]
```
Assert.IsTrue failed. [12/3/2017 9:16:47 AM] Token should have been refreshed after TTL expired.

RemoveDeviceAsync Enumerating devices.
RemoveDeviceAsync Removing E2E_Message_TokenRefresh_0b096a2d-970b-4226-98ef-54f36975f095.
Removing device E2E_Message_TokenRefresh_0b096a2d-970b-4226-98ef-54f36975f095
Device successfully removed
Creating device E2E_Message_TokenRefresh_7dd8c1ef-f4b6-4ac4-9845-5df56aee6c55
[12/3/2017 9:16:36 AM] OpenAsync
[12/3/2017 9:16:37 AM] Refresher: Creating new token 0
Token: SharedAccessSignature sr=[...] se=1512292603
[12/3/2017 9:16:37 AM] SendEventAsync (1)
[12/3/2017 9:16:41 AM] Waiting 6 seconds.
[12/3/2017 9:16:47 AM] SendEventAsync (2)

Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Internal>d__4.MoveNext() in D:\jenkins\workspace\csharp-windows-vs2017\e2e\Microsoft.Azure.Devices.E2ETests\DeviceTokenRefreshE2ETests.cs: line 79
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Internal>d__4.MoveNext() in D:\jenkins\workspace\csharp-windows-vs2017\e2e\Microsoft.Azure.Devices.E2ETests\DeviceTokenRefreshE2ETests.cs: line 98
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Ok_Amqp>d__2.MoveNext() in D:\jenkins\workspace\csharp-windows-vs2017\e2e\Microsoft.Azure.Devices.E2ETests\DeviceTokenRefreshE2ETests.cs: line 29
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()

```

**Comment by CIPop** [comment]
Just hit this on Linux Ubuntu 16.04 (real machine)

```
Failed   DeviceClient_TokenIsRefreshed_Ok_Amqp
Error Message:
 Assert.IsTrue failed. [12/20/17 7:20:43 PM] Token should have been refreshed after TTL expired.
Stack Trace:
   at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Internal>d__4.MoveNext() in /home/cristian/azure-iot-sdk-csharp/e2e/Microsoft.Azure.Devices.E2ETests/DeviceTokenRefreshE2ETests.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Internal>d__4.MoveNext() in /home/cristian/azure-iot-sdk-csharp/e2e/Microsoft.Azure.Devices.E2ETests/DeviceTokenRefreshE2ETests.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Ok_Amqp>d__2.MoveNext() in /home/cristian/azure-iot-sdk-csharp/e2e/Microsoft.Azure.Devices.E2ETests/DeviceTokenRefreshE2ETests.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Standard Output Messages:
 RemoveDeviceAsync Enumerating devices.
 RemoveDeviceAsync Removing E2E_Message_TokenRefresh_5cc17eb3-eba2-41a8-b92e-009da7a8af37.
 Removing device E2E_Message_TokenRefresh_5cc17eb3-eba2-41a8-b92e-009da7a8af37
 Device successfully removed
 Creating device E2E_Message_TokenRefresh_9b6243e4-f1d6-415f-aad2-3e47f5601066
 [12/20/17 7:20:36 PM] OpenAsync
 [12/20/17 7:20:36 PM] Refresher: Creating new token 0
 Token: SharedAccessSignature sr=crispop-iothub1.azure-devices.net%2Fdevices%2FE2E_Message_TokenRefresh_9b6243e4-f1d6-415f-aad2-3e47f5601066&sig=***********************%2BLPFf6FjXTBt2w%3D&se=1513797643
 [12/20/17 7:20:36 PM] SendEventAsync (1)
 [12/20/17 7:20:37 PM] Waiting 6 seconds.
 [12/20/17 7:20:43 PM] SendEventAsync (2)
```

**Comment by CIPop** [comment]
Tracking with #319; fixed by #357.

**Comment by CIPop** [comment]
We have seen this failing in our CI again. Reopening.

**Comment by CIPop** [comment]
```
15:28:57 Failed   DeviceClient_TokenIsRefreshed_Ok_Amqp
15:28:57 Error Message:
15:28:57  Assert.IsTrue failed. [6/12/2018 10:28:56 PM] Token should have been refreshed after TTL expired.
15:28:57 Stack Trace:
15:28:57    at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Internal>d__4.MoveNext() in D:\jenkins\workspace\csharp-windows\e2e\test\DeviceTokenRefreshE2ETests.cs:line 93
15:28:57 --- End of stack trace from previous location where exception was thrown ---
15:28:57    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:28:57    at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Internal>d__4.MoveNext() in D:\jenkins\workspace\csharp-windows\e2e\test\DeviceTokenRefreshE2ETests.cs:line 98
15:28:57 --- End of stack trace from previous location where exception was thrown ---
15:28:57    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:28:57    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:28:57    at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Ok_Amqp>d__2.MoveNext() in D:\jenkins\workspace\csharp-windows\e2e\test\DeviceTokenRefreshE2ETests.cs:line 29
15:28:57 --- End of stack trace from previous location where exception was thrown ---
15:28:57    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
15:28:57    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
15:28:57 
15:28:57 Standard Output Messages:
15:28:57  RemoveDeviceAsync Enumerating devices.
15:28:57  RemoveDeviceAsync Removing E2E_Message_TokenRefresh_8cecea57-0bbc-42ba-b9e5-b5953ee01605.
15:28:57  Removing device E2E_Message_TokenRefresh_8cecea57-0bbc-42ba-b9e5-b5953ee01605
15:28:57  Device successfully removed
15:28:57  Creating device E2E_Message_TokenRefresh_804b60f8-7df3-4b9b-9a97-96c92dbf40a3
15:28:57  [6/12/2018 10:28:43 PM] OpenAsync
15:28:57  [6/12/2018 10:28:43 PM] Refresher: Creating new token 0
15:28:57  Token: SharedAccessSignature sr=azureiot-csharp-win-df-e2e.df.azure-devices-int.net%2Fdevices%2FE2E_Message_TokenRefresh_804b60f8-7df3-4b9b-9a97-96c92dbf40a3&sig=O3LnEhQXu1wZurn68wcEZeL8Qs0pd0C3zc8LA3gF0zw%3D&se=1528842530
15:28:57  [6/12/2018 10:28:50 PM] SendEventAsync (1)
15:28:57  [6/12/2018 10:28:50 PM] Waiting 6 seconds.
15:28:57  [6/12/2018 10:28:56 PM] SendEventAsync (2)
15:28:57 
```

**Comment by timtay-microsoft** [comment]
It appears the fix for this has long since been checked in, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
