### ISSUE TITLE
VS 15.5 Mono Linker throws NullReferenceException when trying to link on Xamarin.Andoird

### ISSUE THREAD

**Issue by PureWeen** [Azure/azure-iot-sdk-csharp#270]
[AzureDeviceClient.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/1533169/AzureDeviceClient.zip)

Windows 10 and iOS

I'm using the latest 1.6.0 but the same issues exists with 1.5.2

# Description of the issue:
Compiling Xamarin android with full linking on causes the following exception

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Linker.TypeReferenceExtensions.<GetMethods>d__4.MoveNext()
   at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.<GetBaseMethodsInInterfaceHierarchy>d__12.MoveNext()
   at Mono.Linker.Steps.TypeMapStep.MapVirtualInterfaceMethod(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1696	

# Code sample exhibiting the issue:
I've attached a project that's just an empty Android project I added the IoT libraries to that should exhibit the issues

**Comment by PureWeen** [comment]
I tried stepping through it a little bit with windbg and it seems like it chokes on BufferedInputStream when it's trying to match up properties with interfaces

https://github.com/mono/linker/blob/e4dfcf006b0705aba6b204aab2d603b781c5fc44/linker/Mono.Linker.Steps/TypeMapStep.cs#L158

seems to return a null value that gets passed into
```
TryMatchMethod 
```

**Comment by PureWeen** [comment]
It seems like these being netstandard1.3 + the ICloneable fake out in AMQP + me using netstandard2.0 = Not Happy Linker

I pulled down this and the AMQP project and just changed the Netstandard libraries over to 2.0 and removed ICloneable from the NETSTANDARD typedef since ICloneable is part of the Netstandard2.0 spec

I also had to do this
https://github.com/aspnet/EntityFrameworkCore/issues/8922
(Highlighting that I needed to add version 4.3.0 of the Unsafe nuget.)
and added this into my linker.xml file
```
  <assembly fullname="Microsoft.Azure.Amqp">
    <type fullname="System.Collections.Generic.KeyedByTypeCollection`1">
      <method name=".ctor" />
    </type>
    <type fullname="System.Collections.Generic.KeyedByTypeCollection`1" />
    <type fullname="*" />
  </assembly>
```

Now my Android project is able to compile and run and IoT messages are happily working

**Comment by CIPop** [comment]
Thanks @PureWeen  for reporting the issue and the __solution__!
I'd need more time to understand why we need `ICloneable` in NetStandard. If we can remove it, this should fix the netstandard1.3 build. If not, we can at least build netstandard2.0 as well for Android support.

@tameraw @jasmineymlo

**Comment by CIPop** [comment]
Thanks again @PureWeen for researching and finding a workaround. I was going through the issues linked and found a few Xamarin/Android issues that are tracking a bug-fix on their side:

https://github.com/xamarin/xamarin-android/issues/1196#issuecomment-358746048
A group of related to bugs is also documented here: https://github.com/xamarin/AndroidSupportComponents/issues/75#issuecomment-361282393

**Comment by abhipsaMisra** [comment]
@PureWeen : Could you please try again with the latest Visual Studio version? According to Xamarin issue [#1196](https://github.com/xamarin/xamarin-android/issues/1196), updating to latest version should work. We have also added a readme and some samples to our repository. Please let us know if that helps.

**Comment by CIPop** [comment]
Thanks @abhipsaMisra  for the investigation and new sample! 
Xamarin appears to have released a new version fixing the linker problem.

Closing for now: please reopen if this is still observed on the latest Visual Studio release.
