### ISSUE TITLE
[Technical Question] AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-iot-sdk-csharp#2921]
The issue is in the China region when I try to connect my device to DPS.
For other regions it works as expected, even when I connect from Europe to China DPS it works. The problem is only when connecting from China to China  ("global.azure-devices-provisioning.cn").

Could you please point me to where it can be an issue?
Please let me know what information should I provide to investigate the issue.

StackTrace:

```
Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: MQTT transport exception
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.ProvisionOverTcpCommonAsync(ProvisioningTransportRegisterMessage message, ClientTlsSettings tlsSettings, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   at AzureIoTHubAdapter.AzureIoTHubAdapter.RegisterDeviceAsync(SecurityProviderX509Certificate security, String dpsIdScope)
Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: MQTT transport exception
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.ProvisionOverTcpCommonAsync(ProvisioningTransportRegisterMessage message, ClientTlsSettings tlsSettings, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   at AzureIoTHubAdapter.AzureIoTHubAdapter.RegisterDeviceAsync(SecurityProviderX509Certificate security, String dpsIdScope)
---
System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.ProvisionOverTcpCommonAsync(ProvisioningTransportRegisterMessage message, ClientTlsSettings tlsSettings, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
```

**Comment by abhipsaMisra** [comment]
It looks like you're running into issues when negotiating the TLS handshake. The client isn't able to access the certificate revocation list and is thus unable to verify if the remote certificate presented is valid or not. 
System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation

This is what these [status](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainstatusflags?view=net-6.0) mean:
Enum | Description
--- | --- 
OfflineRevocation | Specifies that the online certificate revocation list (CRL) the X509 chain relies on is currently offline. 
RevocationStatusUnknown | Specifies that it is not possible to determine whether the certificate has been revoked. This can be due to the certificate revocation list (CRL) being offline or unavailable. 

Are you able to check if you can access the certificate revocation list from China?

**Comment by abhipsaMisra** [comment]
The CRL distribution point on the DPS Digicert server cert is http://crl.digicert.cn/DigiCertBasicRSACNCAG2.crl. Could you try checking if this is accessible from China?

**Comment by Marusyk** [comment]
Thx I'll try in a few days and let you know. Please keep the issue opene

**Comment by abhipsaMisra** [comment]
It looks like there is some networking rule/limitation that is restricting your client from accessing the certificate revocation list.
Could you try connecting using Mqtt_Ws and see if that helps? The certificate revocation list check is not turned on by default for websocket based connections.

Just as an FYI - I would like to call out that certificate revocation list checks and remote certificate validation callbacks should be implemented with care. Incorrect implementation could leave your client exposed to security vulnerabilities.

**Comment by abhipsaMisra** [comment]
A question - is this an X509 certificate client or a symmetric key based client that you are trying to register using DPS?

**Comment by Marusyk** [comment]
it's X509 certificate

**Comment by abhipsaMisra** [comment]
Yes, connecting with `WebSocketOnly` will force the connection to use websockets. Note that this will require that port 443 be open and usable.

**Comment by abhipsaMisra** [comment]
@Marusyk - were you able to give this a try?
