### ISSUE TITLE
[Technical Question] Spported Authentication

### ISSUE THREAD

**Issue by hommeabeil** [Azure/azure-iot-sdk-csharp#2991]
I can't find the answer so I am asking it.  Does the `SecurityProviderTpmHsm` class support  authentication  like password ? I can't find a field where I can pass something like that. I am also wondering which kind of TPM authorization this lib support. Following is the error I get if I set a password on my endorsement key. Thanks

```
Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: HTTP transport exception
       ---> Tpm2Lib.TpmException: Error {BadAuth} was returned for command PolicySecret.
      Details:
      [Code=TpmRc.BadAuth],[RawCode=0x9A2,2466]
      [ErrorEntity=Session], [ParmNum=1]
      [ParmName=Unknown]
         at Tpm2Lib.Tpm2.ProcessError(TpmSt responseTag, UInt32 responseParamSize, TpmRc resultCode, TpmStructureBase inParms)
         at Tpm2Lib.Tpm2.DispatchMethod(TpmCc ordinal, TpmStructureBase inParms, Type expectedResponseType, TpmStructureBase& outParms, Int32 numInHandlesNotUsed, Int32 numOutHandlesNotUsed)
         at Tpm2Lib.Tpm2.PolicySecret(TpmHandle authHandle, TpmHandle policySession, Byte[] nonceTPM, Byte[] cpHashA, Byte[] policyRef, Int32 expiration, TkAuth& policyTicket)
         at Tpm2Lib.TpmPolicySecret.Execute(Tpm2 tpm, AuthSession sess, PolicyTree policy)
         at Tpm2Lib.AuthSession.RunPolicy(Tpm2 tpm, PolicyTree policyTree, String branchToEvaluate, Boolean allowErrors)
         at Microsoft.Azure.Devices.Provisioning.Security.SecurityProviderTpmHsm.ActivateIdentityKey(Byte[] encryptedKey)
         at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningSasBuilder.ExtractServiceAuthKey(SecurityProviderTpm securityProvider, String hostName, Byte[] activation)
         at Microsoft.Azure.Devices.Provisioning.Client.Transport.TpmDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Microsoft.Azure.Devices.Provisioning.Client.Transport.RuntimeRegistration.RegisterDeviceWithHttpMessagesAsync(String registrationId, String idScope, DeviceRegistration deviceRegistration, Nullable`1 forceRegistration, Dictionary`2 customHeaders, CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Provisioning.Client.Transport.RuntimeRegistrationExtensions.RegisterDeviceAsync(IRuntimeRegistration operations, String registrationId, String idScope, DeviceRegistration deviceRegistration, Nullable`1 forceRegistration, CancellationToken cancellationToken)
         at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerHttp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerHttp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
         at DpsProvisinningService.ExecuteAsync(CancellationToken stoppingToken) in /home/jbouchard/ws/dotnet/tpm/DpsProvisionningService.cs:line 32
```

**Comment by abhipsaMisra** [comment]
Could you explain a bit what you mean by passing a password to a TPM based security provider?

The DPS service uses the endorsement key and a nonce-based challenge to authenticate TPM based devices. This nonce is then saved into the TPM and is used to sign shared access signature tokens and connect to IoT services. 
You can read more about it here: https://learn.microsoft.com/azure/iot-dps/concepts-tpm-attestation

**Comment by timtay-microsoft** [comment]
@hommeabeil can you provide a bit more context on what you are asking here?

**Comment by ngastelum-ms** [comment]
Closing this issue, please feel free to create a new one if you're still having this problem.
