### ISSUE TITLE
ProvisioningServiceClient X509 tests fail on Linux / Ubuntu 16.04

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#307]
We're hitting https://github.com/dotnet/corefx/issues/16029
@mamokarz pointed out this same certificate works well for our Java SDK on both Linux and Windows.

(49 tests failing:)

AttestationMechanism_Constructor_ThrowsOnAttestationNull

```
Error Message:
 Unable to create instance of class Microsoft.Azure.Devices.Provisioning.Service.Test.AttestationMechanismTests. Error: Interop+Crypto+OpenSslCryptographicException: error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error.
Stack Trace:
    at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
   at Microsoft.Azure.Devices.Provisioning.Service.X509CertificateWithInfo.ValidateCertificate(String certificate) in /home/cristian/azure-iot-sdk-csharp/provisioning/service/src/Config/X509CertificateWithInfo.cs:line 145
   at Microsoft.Azure.Devices.Provisioning.Service.X509CertificateWithInfo..ctor(String certificate) in /home/cristian/azure-iot-sdk-csharp/provisioning/service/src/Config/X509CertificateWithInfo.cs:line 94
   at Microsoft.Azure.Devices.Provisioning.Service.X509Certificates..ctor(String primary, String secondary) in /home/cristian/azure-iot-sdk-csharp/provisioning/service/src/Config/X509Certificates.cs:line 142
   at Microsoft.Azure.Devices.Provisioning.Service.X509Attestation.CreateFromRootCertificates(String primary) in /home/cristian/azure-iot-sdk-csharp/provisioning/service/src/Config/X509Attestation.cs:line 242
   at Microsoft.Azure.Devices.Provisioning.Service.Test.AttestationMechanismTests..ctor() in /home/cristian/azure-iot-sdk-csharp/provisioning/service/tests/Config/AttestationMechanismTests.cs:line 33
```

**Comment by CIPop** [comment]
Fixed by #308.
