### ISSUE TITLE
Error while opening the device connection

### ISSUE THREAD

**Issue by ponsakthi** [Azure/azure-iot-sdk-csharp#321]
**OS and version used:** Windows 10

 **SDK version used:** Microsoft.Azure.Devices.Client 1.5.0

We are using Amqp_WebSocket_Only as Transport Type. While opening the connection, an exception is thrown intermittenlty.

Code:
`deviceClient.OpenAsync()`

Exception:
` System.IO.IOException: The encryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The context has expired and can no longer be used
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.DelegatedStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketConnectionStream.WebSocketConnection.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.DelegatedStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketConnectionStream.<>n__1(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketConnectionStream.<WriteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendFrameAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Amqp.Transport.ClientWebSocketTransport.<WriteAsyncCore>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<TryOpenPrioritizedTransportsAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Devices.Client.DeviceClient.<TryOpenPrioritizedTransportsAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<EnsureOpenedAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.DeviceClient.<EnsureOpenedAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Client.IotHub.Internal.CopiedFromIoTHub.IoTHubTransport.<OpenDeviceClientAsync>d__c.MoveNext()`

**Comment by CIPop** [comment]
This seems to be a security exception from Schannel: SEC_E_CONTEXT_EXPIRED (https://msdn.microsoft.com/en-us/library/windows/desktop/aa375390(v=vs.85).aspx) within SslStream which is used by System.Net.WebSockets.

Could you give us more details regarding:
* OS SKU (Client / Server / IoT)
* .NET Version (from the stack, I assume this is .NET Framework)
* Is the System Clock automatically synchronized using NTP (is there a noticeable clock time difference on that machine?)

If you are able to reproduce the issue, would you be able to capture the following:
* full-memory dump
* Wireshark trace
* Schannel trace:
```
     logman start schannel_trace -p "{37D2C3CD-C5D4-4587-8531-4696C44244C8}" 0x4000ffff -o schannel.etl -ets -ln schannel

     Run the repro.

     logman stop schannel_trace -ets
```

**Important:** Since memory dumps and traces may contain sensitive information, please share dumps or schannel traces that were generated using test devices. After generating the traces/dumps please delete or renew the keys in Azure.

**Comment by CIPop** [comment]
@ponsakthi did you have any time/luck getting this to repro and capturing the above traces?

**Comment by CIPop** [comment]
@ponsakthi , please reopen also adding the information above. 

There isn't much we can investigate based on the above stack.
