### ISSUE TITLE
Received an Exception - The Operation was canceled

### ISSUE THREAD

**Issue by traghunathan** [Azure/azure-iot-sdk-csharp#372]
- **OS and version used:** <Windows Server 2016> 
- **SDK version used:** <1.6.1> 

# Description of the issue:
We are running a simulator with 2000 devices in single instance (total 5 instances in single machine), which was working fine for last 2 months. When we test the same simulator tool yesterday, we received "The Operation was canceled" exception during long run.

# Code sample exhibiting the issue:
DeviceClientObj = DeviceClient.CreateFromConnectionString(ConnectionString, Microsoft.Azure.Devices.Client.TransportType.Amqp);
DeviceClientObj.OpenAsync();
#With 1 minute frequency we are sending below message
var msg = new Microsoft.Azure.Devices.Client.Message(Encoding.UTF8.GetBytes(evntMsg));
#removed propery details
await DeviceClientObj?.SendEventAsync(msg);

# Console log of the issue:
Microsoft.Azure.Devices.Client.Exceptions.IotHubException: The operation was canceled.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c.<ApplyTimeout>b__72_1(Task t)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DeviceEntityManager.DasEntityManager.<StartReceiveMessage>d__156.MoveNext()

****

**Comment by CIPop** [comment]
@traghunathan In v1.6.1 there were changes made to the retry mechanism to fix a memory leak.
Since you have 2000 devices in a single instance, there is a chance that some of them timed-out based on `OperationTimeoutInMilliseconds` which defaults at 4 minutes. In case of network issues or throttling this would be an expected exception.

Could you add more information such as:
1. What .NET runtime are you using? (Framework, Core, etc)
2. What is the frequency of devices failing with this error (e.g. 4 devices each 10 hrs)
3. What is the time after which SendEventAsync fails with this error? (Is it less than 4 minutes?)
4. Why are you ignoring null within `await DeviceClientObj?.`? Could something else potentially have disposed the client on another thread?

**Comment by traghunathan** [comment]
@CIPop 
i think, its not because of throttling, as we using S3 IoT hub. We tested the same scenarios many times earlier.
We plan to monitor network during our execution next time, 

Please find the list of information asked in above comments,
1. What .NET runtime are you using? - **.NET Framework 4.5.2**
2. What is the frequency of devices failing with this error (e.g. 4 devices each 10 hrs) - **"We observed device failing after 8hrs, around 1980 devices of total 2000 failed"**
3. What is the time after which SendEventAsync fails with this error? (Is it less than 4 minutes?) - **75% of time, we received this error while sending the heartbeat message.**
4. Why are you ignoring null within await DeviceClientObj?.? Could something else potentially have disposed the client on another thread? - **DeviceClientObj is not disposed in any other thread,**

**Comment by CIPop** [comment]
Thanks @traghunathan . There isn't sufficient information to investigate in the bug - we'll need to repro on our side or have you collect a full-memory dump when this is happening.

We did have a fix for #319 that we plan to release shortly. It could be that the clients fail to refresh their CBS links.

For us to repro, please supply:
1. A simple project that creates and uses the 2000 clients (I'm most interested if you use a `Task` array vs Threads, etc).
2. The details of the client machine running this code (is it Azure, what SKU?)

**Comment by traghunathan** [comment]
Thanks @CIPop. We identified the reason for the issue. Please read below two points. It may help,
- We identified that **TTF Time in IoT hub is changed to 10 seconds**. I believe, message is queued up. So, Due to that, sdk not able to send ack for the message with in 10 seconds, as we running 2k devices in one instance. We received this above exception issue in ReceiveAsync().
- We tried to change TTF to 180 seconds, we didnt receive any exception.

**Comment by CIPop** [comment]
@traghunathan I don't know what TTF Time is. Where did you change this option on IoT Hub?

/cc @mastermanu @simonporter @yzhong94

**Comment by CIPop** [comment]
Closing: no activity/replies.
