### ISSUE TITLE
Cannot run tests unless in an Administrator console

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-csharp#394]
- **OS and version used:** <VERSION> 
Windows 10 Enterprise 1709
- **SDK version used:** <VERSION> 
master cd93e75fd8914b6247f23eb6a5cfd7aea459676f

# Description of the issue:

When running the build in a standard console, the build fails. When running the build in an elevated console, it succeeds.
# Code sample exhibiting the issue:

# Console log of the issue:

```Test run for C:\dev\azure-iot-sdk-csharp\iothub\service\tests\bin\Debug\netcoreapp2.0\Microsoft.Azure.Devices.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20180109-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 161. Passed: 0. Failed: 153. Skipped: 8.
Test Run Failed.
Test execution time: 1.1432 Seconds
Results File: C:\dev\azure-iot-sdk-csharp\iothub\service\tests\TestResults\iadavis_MININT-HR1MSQJ_2018-03-09_13_03_01.trx
```

The file contains many errors like this test DeviceAuthenticationGoodAuthConfigTest3:

```
Assembly Initialization method Microsoft.Azure.Devices.Api.Test.ClientWebSocketTransportTests.AssembyInitialize threw exception. System.Net.HttpListenerException: System.Net.HttpListenerException: Access is denied. Aborting test execution.
at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Azure.Devices.Api.Test.ClientWebSocketTransportTests.AssembyInitialize(TestContext testcontext) in C:\dev\azure-iot-sdk-csharp\iothub\service\tests\ClientWebSocketTransportTests.cs:line 36
```

**Comment by CIPop** [comment]
/cc @abhipsaMisra 

@idavis We need a better story for our test prerequisite documentation.
Please follow the prerequisite installation here: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/iothub/service/tests
