### ISSUE TITLE
Exception throwed when calling RegisterAsync of ProvisioningDeviceClient in UWP environment

### ISSUE THREAD

**Issue by henry1111** [Azure/azure-iot-sdk-csharp#407]
OS Windows 10 IOT Core, OS version 10.0.16299.248, x64
Application's .NET Target Framework :  
  NetCore UWP
 
DEVICETYPE:  Raspberry PI3, Upboard 
SDK version used:
    Azure.Devices.Client v1.7.0
    Azure.Devices.Provisioning.Client  v.1.1.0

# Description of the issue:
using x509 certificate for security, the following line throw exceptions regardless HTTP, MQTT or AMQP transport are used.

DeviceRegistrationResult result = await provClient.RegisterAsync();

For HTTP, a little interesting.   it complains certificate not found in the personal(\my) store.  The certificate was imported in LocalMachine\My store.   when I try to add the certificate to CurrentUser\My, it returns with AccessDenied.  This is strange.  Even if I can successfully add the certificate personal store, it will be still a different user other than the app running on, as I am logged in Administrator account, and App is running in DefaultAccount.

Using http,

Client certificate was not found in the personal (\"MY\") certificate store. In UWP, client certificates are only supported if they have been added to that certificate store.

   at System.Net.Http.HttpClientHandler.<ApplyClientCertificateSettings>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Net.Http.HttpClientHandler.<ConfigureRequest>d__104.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.<SendAsync>d__111.MoveNext()

Using MQTT
One or more errors occurred. (The credentials supplied to the package were not recognized)

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningChannelHandlerAdapter.<ChannelActive>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.<ProvisionOverTcpUsingX509CertificateAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerMqtt.<RegisterAsync>d__12.MoveNext()

using AMQP

Method not found: 'Void Microsoft.Azure.Amqp.Transport.TlsTransportSettings.set_Certificate(System.Security.Cryptography.X509Certificates.X509Certificate2)'.

   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientConnection.<OpenAsync>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientConnection.OpenAsync(TimeSpan timeout, Boolean useWebSocket, X509Certificate2 clientCert)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpAuthStrategyX509.OpenConnectionAsync(AmqpClientConnection connection, TimeSpan timeout, Boolean useWebSocket)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.<RegisterAsync>d__7.MoveNext()

# Code sample exhibiting the issue:

 public sealed class StartupTask : IBackgroundTask
    {
        private BackgroundTaskDeferral _deferral;
        private const string GlobalDeviceEndpoint = "global.azure-devices-provisioning.net";
        private static string s_idScope = "0ne00008EC9";
        public async void Run(IBackgroundTaskInstance taskInstance)
        {
            // 
            // TODO: Insert code to perform background work
            //
            // If you start any asynchronous methods here, prevent the task
            // from closing prematurely by using BackgroundTaskDeferral as
            // described in http://aka.ms/backgroundtaskdeferral
            //

            _deferral = taskInstance.GetDeferral();
            await ProvisionTaskAsync();

        }

        private  async Task ProvisionTaskAsync()
        {
            try
            {
                X509Store store = new X509Store(StoreLocation.LocalMachine);
                store.Open(OpenFlags.ReadOnly);
                X509Certificate2 deviceCert = null;
                foreach (var cert in store.Certificates)
                {
                    if (cert.HasPrivateKey == true)
                    {
                        deviceCert = cert;
                        break;
                    }
                }

                using (var security = new SecurityProviderX509Certificate(deviceCert))
                using (var transport = new ProvisioningTransportHandlerHttp())
                //using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.TcpOnly))
                //using (var transport = new ProvisioningTransportHandlerMqtt(TransportFallbackType.TcpOnly))
                {
                    ProvisioningDeviceClient provClient =
                        ProvisioningDeviceClient.Create(GlobalDeviceEndpoint, s_idScope, security, transport);

                    Debug.WriteLine($"RegistrationID = {security.GetRegistrationID()}");
                    Debug.Write("ProvisioningClient RegisterAsync . . . ");
                    DeviceRegistrationResult result = await provClient.RegisterAsync();

                    Debug.WriteLine($"{result.Status}");
                    Debug.WriteLine($"ProvisioningClient AssignedHub: {result.AssignedHub}; DeviceID: {result.DeviceId}");

                    if (result.Status != ProvisioningRegistrationStatusType.Assigned) return;

                    IAuthenticationMethod auth = new DeviceAuthenticationWithX509Certificate(result.DeviceId, deviceCert);
                    using (DeviceClient iotClient = DeviceClient.Create(result.AssignedHub, auth))
                    {
                        Debug.WriteLine("DeviceClient OpenAsync.");
                        await iotClient.OpenAsync();
                        Debug.WriteLine("DeviceClient SendEventAsync.");
                        await iotClient.SendEventAsync(new Message(Encoding.UTF8.GetBytes("TestMessage")));
                        Debug.WriteLine("DeviceClient CloseAsync.");
                        await iotClient.CloseAsync();
                    }
                }

            }
            catch( Exception ex)
            {

            }
        }
    }

**Comment by CIPop** [comment]
Thanks @henry1111 for the detailed report! I've added this to the Xamarin stabilization effort.

**Comment by umichjoe** [comment]
Any update on this?  I'm running into similar issues with DPS on an ARM device via UWP background task.  I can't seem to find any permutation of transport configuration where this works.  Any workarounds/tips would be greatly appreciated.  Thanks!  :)

**Comment by RubiaL** [comment]
we are working on stabilizing Windows IoT Core for C# SDK. we will update you here once we have a fix.

**Comment by vinagesh** [comment]
Can you update to the latest version of the SDK and still hit this issue?

**Comment by vinagesh** [comment]
Please let us know if this is still an issue.

**Comment by vinagesh** [comment]
Closing issue due to inactivity.

**Comment by az-iot-builder-01** [comment]
@henry1111, @CIPop, @umichjoe, @RubiaL, @vinagesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
