### ISSUE TITLE
Value can not be null, Parameters: Parameter name: parameters

### ISSUE THREAD

**Issue by uma075** [Azure/azure-iot-sdk-csharp#441]
# Description of the issue:
On running GroupCertificateVerificationSample getting this error.

`System.ArgumentNullException: Value cannot be null.
Parameter name: parameters
   at Org.BouncyCastle.Crypto.Parameters.ParametersWithRandom..ctor(ICipherParameters parameters, SecureRandom random)
   at Org.BouncyCastle.Crypto.Operators.Asn1SignatureFactory.CreateCalculator()
   at Org.BouncyCastle.X509.X509V3CertificateGenerator.Generate(ISignatureFactory signatureCalculatorFactory)
   at Microsoft.Azure.Devices.Provisioning.Samples.VerificationCertificateGenerator.GenerateAndSignCertificate(X509Name subjectName, X509Name issuerName, AsymmetricKeyParameter privateSigningKey)
   at Microsoft.Azure.Devices.Provisioning.Samples.VerificationCertificateGenerator.GenerateSignedCertificate(X509Certificate2 signerCertificate, String commonName)
   at Microsoft.Azure.Devices.Provisioning.Samples.Program.Main(String[] args)`

# Code sample exhibiting the issue:
Just running sample by providing my inputs in Main method. like
`  string certificatePath = @"D:\Learning\Azure\azure-iot-sdk-csharp-master\azure-iot-sdk-csharp-master\provisioning\device\samples\ProvisioningDeviceClientX509\certificate.pfx";// args[0];
            string certificatePassword = "Test@12345"; //args[1];
            string verificationCode = "85855ADE70C2C89BFEA29866399AB51DC6A2118A3C88D00A";//args[2];`

**Comment by CIPop** [comment]
@uma075 This is probably because the certificate you are trying to use is not a CA / signing certificate.
A correct certificate would have the following properties:

```diff
+ KU = Certificate Signing (04)
+ EKU= <empty>
```

The one in `provisioning\device\samples\ProvisioningDeviceClientX509\certificate.pfx` cannot be used for this purpose as it has the wrong Key Usage and Enhanced Key Usage:
```diff
- KU = Digital Signature, Key Encipherment (a0)
- EKU = Client Authentication (1.3.6.1.5.5.7.3.2)
```

Please go through: https://docs.microsoft.com/en-us/azure/iot-dps/how-to-verify-certificates
The correct certificate generation tool is also linked here: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/provisioning/device/samples/ProvisioningDeviceClientX509#using-your-certificates.

**Comment by yzhong94** [comment]
@uma075 , thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute customer satisfaction survey
