### ISSUE TITLE
RemoveDevices2Async throws MissingManifestResourceException

### ISSUE THREAD

**Issue by jwendl** [Azure/azure-iot-sdk-csharp#489]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 
- **Application's .NET Target Framework :** netcoreapp2.0 
- **Device:** Laptop 
- **SDK version used:** 
Microsoft.Azure.Devices: 1.5.1
Microsoft.Azure.Devices.Client: 1.6.2

 

# Description of the issue:
``` csharp
            var registryManager = BuildRegistryManager(deviceServiceSettings);
            var deviceQuery = registryManager.CreateQuery("select * from devices", 1000);
            do
            {
                var deviceTwins = await deviceQuery.GetNextAsTwinAsync();
                var devices = new List<Device>();
                foreach (var deviceTwin in deviceTwins)
                {
                    devices.Add(new Device(deviceTwin.DeviceId));
                }

                var bulkRegistryOperationResult = await registryManager.RemoveDevices2Async(devices);
                if (!bulkRegistryOperationResult.IsSuccessful)
                {
                    foreach (var error in bulkRegistryOperationResult.Errors)
                    {
                        DeviceSimulatorActorEventSource.Current.ExceptionOccured($"Error deleting device {error.DeviceId} because {error.ErrorCode} : {error.ErrorStatus}");
                    }
                }
            } while (deviceQuery.HasMoreResults);
```

Throws an exception of type MissingManifestResourceException
```
Actor's async method threw an exception. Method name: IDeviceSimulator.CleanDevicesAsync, actor type: DeviceSimulator.DeviceSimulatorActor, actor ID: 24ae9fd3-ceb2-4d89-bcf7-d24eb5d64c21, exception: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure \"Microsoft.Azure.Devices.ApiResources.resources\" was correctly embedded or linked into assembly \"Microsoft.Azure.Devices\" at compile time, or that all the satellite assemblies required are loadable and fully signed.
       at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
       at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
       at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
       at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
       at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
       at Microsoft.Azure.Devices.HttpRegistryManager.GenerateExportImportDeviceListForBulkOperations(IEnumerable`1 devices, ImportMode importMode)
       at Microsoft.Azure.Devices.HttpRegistryManager.RemoveDevices2Async(IEnumerable`1 devices, Boolean forceRemove, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.HttpRegistryManager.RemoveDevices2Async(IEnumerable`1 devices)
       at DeviceSimulator.DeviceSimulatorActor.<CleanDevicesAsync>d__12.MoveNext() in C:\Source\GitHub\iot-device-simulator\src\DeviceSimulation\Actor\DeviceSimulatorActor\DeviceSimulatorActor.cs:line 116
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<>c.<ContinueWith>b__8_0(Task t)
       at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<>c__DisplayClass45_0.<ActorMethodDispatch>b__0(Task`1 t).
```

# Code sample exhibiting the issue:

https://github.com/jwendl/iot-device-simulator/blob/master/src/DeviceSimulation/Actor/DeviceSimulatorActor/DeviceSimulatorActor.cs#L103-L125

# Console log of the issue:

**Comment by jwendl** [comment]
We can actually close this. It was because I was using an older version of the SDKs
Updating like the following works.

    <PackageReference Include="Microsoft.Azure.Devices" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.7.1" />
