### ISSUE TITLE
Exception when using Stream overload of Message constructor

### ISSUE THREAD

**Issue by rydergillen-compacSort** [Azure/azure-iot-sdk-csharp#543]
- **OS, version, SKU and CPU architecture used:** Windows 10 Pro - 64bit
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client - 1.17.0

## Description of the issue:
When passing the BodyStream property of an existing Message to the Constructor ```new Message(existing.BodyStream)``` an exception is thrown.

Note: using the Byte[] overload works as intended.

## Code sample exhibiting the issue:

This is the default code generated by the IoT Module C# template

``` CSHARP
        static async Task<MessageResponse> PipeMessage(Message message, object userContext)
        {
            int counterValue = Interlocked.Increment(ref counter);

            var moduleClient = userContext as ModuleClient;
            if (moduleClient == null)
            {
                throw new InvalidOperationException("UserContext doesn't contain " + "expected values");
            }

            byte[] messageBytes = message.GetBytes();
            string messageString = Encoding.UTF8.GetString(messageBytes);
            Console.WriteLine($"Received message: {counterValue}, Body: [{messageString}]");

            if (!string.IsNullOrEmpty(messageString))
            {
                //var pipeMessage = new Message(messageBytes); //THIS WORKS!!!
                var pipeMessage = new Message(message.BodyStream); //THIS CAUSES EXCEPTION
                foreach (var prop in message.Properties)
                {
                    pipeMessage.Properties.Add(prop.Key, prop.Value);
                }
                await moduleClient.SendEventAsync("output1", pipeMessage);//EXCEPTION IS THROWN HERE
                Console.WriteLine("Received message sent");
            }
            return MessageResponse.Completed;
        }
```

## Console log of the issue:
```
Specified method is not supported.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by CIPop** [comment]
Thanks for reporting @rydergillen-compacSort ! We'll need to investigate.

**Comment by wickste** [comment]
@CIPop - using 1.18.1 I am seeing a different behavior (slightly worse imo): the Message(stream) ctor actually succeeds now, but it results in an empty message body. This is worse as it's harder to detect/root cause because there is no exception at the time of creating the message. I only see the issue when inspecting my data on the backend.

**Comment by CIPop** [comment]
Thanks @wickste . 

1. What protocol are you using?
2. Please capture logs to understand what causes the exception to be thrown: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/CaptureLogs (stack is actually lost due to a design bug)

**Comment by wickste** [comment]
@CIPop I am using MQTT. I have lost my repo since I worked around it and also re-structured my code for unrelated reasons, so I can't do #2 right now.

However, I am wondering if it has to do with this issue: apparently the Message instance created from stream is only usable for the lifetime of that stream, which seems unexpected.

Message message;
using (var stream = new MemoryStream(buffer))
{
    message = new Message(stream);
}
await iotHubClient.SendEventAsync(message);  // <- throws ObjectDisposedException

**Comment by wickste** [comment]
@CIPop I have re-created my repro and posted a minimal complete repro app here: https://gist.github.com/wickste/159a9858a4e10fe511b0843ff916c7c2

ETL file is here, not sure if it contains anything useful:
[iot_000001.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/2481489/iot_000001.zip)

**Comment by jenoola** [comment]
@rydergillen-compacSort could you try to repro with the latest version of SDK? I do not get repro with it
