### ISSUE TITLE
SendEventAsync will give a TimeoutException with Microsoft.Azure.Devices.Client 1.7.0 or newer

### ISSUE THREAD

**Issue by LeivoSepp** [Azure/azure-iot-sdk-csharp#580]
- **OS, version, SKU and CPU architecture used:** Windows 10 IoT Core
- **Application's .NET Target Framework :** Windows 10, version 1803 (Build 17134)
- **Device:** Raspberry PI2
- **SDK version used:** 
Microsoft.NETCore.UniversalWindowsPlatform 6.1.7
Microsoft.Azure.Devices.Client 1.7.0

## Description of the issue:
Trying to send Device To Cloud messages:
** Using Nuget package Microsoft.Azure.Devices.Client 1.7.0 or newer will give TimeoutException.
** Using Nuget package Microsoft.Azure.Devices.Client 1.6.3, everything is working as excpected. 

## Code sample exhibiting the issue:
        DeviceClient deviceClient;
        string IotHubConnectionString = "HostName=xxxx.azure-devices.net;DeviceId=xxxx;SharedAccessKey=xxxx=";
        private BackgroundTaskDeferral deferral;
        public async void Run(IBackgroundTaskInstance taskInstance)
        {
            deferral = taskInstance.GetDeferral();

            deviceClient = DeviceClient.CreateFromConnectionString(IotHubConnectionString);
            {
                try
                {
                    string msg = "test";
                    var message = new Message(Encoding.ASCII.GetBytes(msg));
                    await deviceClient.SendEventAsync(message); //here the code will get a timeout
                }
                catch (Exception e)
                {

                }
            }
        }

## Console log of the issue:
e	{System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c.<ApplyTimeout>b__74_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at BackgroundApplication6.StartupTask.<Run>d__2.MoveNext()}	System.Exception {System.TimeoutException}

**Comment by CIPop** [comment]
Thanks @LeivoSepp for the report. Are you saying this is happening from time to time or is it consistent?
Does it work if you use any other protocol such as HTTP or MQTT?

**Comment by LeivoSepp** [comment]
This is happening all the time, it is consistent. 
I did testing with MQTT / HTTP and they are both working with Microsoft.Azure.Devices.Client newest package.
So, the conclusion is, that only AMQP is affected.

**Comment by timtay-microsoft** [comment]
Are you still seeing this issue with the latest version of Microsoft.Azure.Devices.Client (1.18.0)?

**Comment by LeivoSepp** [comment]
I found a solution, using TransportType.**Amqp_WebSocket_Only** solves the issue.

**Comment by timtay-microsoft** [comment]
Did you try out the latest version of Microsoft.Azure.Devices.Client though?

**Comment by timtay-microsoft** [comment]
Closing this issue due to inactivity, and because the AMQP layer was redesigned so this issue likely isn't relevant anymore

**Comment by az-iot-builder-01** [comment]
@CIPop, @LeivoSepp, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
