### ISSUE TITLE
ReceiveAsync for UWP doesnt work with Microsoft.Azure.Devices.Client 1.6.1 or newer

### ISSUE THREAD

**Issue by LeivoSepp** [Azure/azure-iot-sdk-csharp#587]
- **OS, version, SKU and CPU architecture used:** Windows 10 IoT Core
- **Application's .NET Target Framework :** Windows 10, version 1803 (Build 17134)
- **Device:** Raspberry PI2
- **SDK version used:** 
Microsoft.NETCore.UniversalWindowsPlatform 6.1.7
Microsoft.Azure.Devices.Client 1.6.1 or newer

## Description of the issue:
Trying to send Cloud-to-Device messages.
I made testing with different Microsoft.Azure.Devices.Client versions and the conclusion is following:
1. Microsoft.Azure.Devices.Client 1.6.0 is working as excpected, everything OK.
2. Microsoft.Azure.Devices.Client 1.6.1 doesnt give any error if there is no messages in queue, If there is a message in queue, there will be ArgumentNullException Exception.
3. Microsoft.Azure.Devices.Client 1.17.1 (currently latest) will give an TimeoutException already for OpenAsync command. The code even doesnt reach to ReceiveAsync.

Errors are consistent, can be produced 100%.
MQTT protocol can see the message in queue, but cannot read the content with the following code.

## Code sample exhibiting the issue:
        DeviceClient deviceClient;
        string IotHubConnectionString = "HostName=xxx.azure-devices.net;DeviceId=xxx;SharedAccessKey=xxx";
        private BackgroundTaskDeferral deferral;
        public async void Run(IBackgroundTaskInstance taskInstance)
        {
            deferral = taskInstance.GetDeferral();

            deviceClient = DeviceClient.CreateFromConnectionString(IotHubConnectionString, TransportType.Amqp);
            {
                while (true)
                {
                    try
                    {
                        //1.6.0 is workig with AMQP
                        //1.6.1 getting ArgumentNullException exception when there is a message in queue
                        //1.17.1 latest will get timeout exception already for OpenAsync().
                        //MQTT can receieve messages, but doesnt see the content
                        await deviceClient.OpenAsync();
                        Message receivedMessage = await deviceClient.ReceiveAsync();
                        if (receivedMessage?.Properties.Count > 0)
                        {
                            string receivedText = Encoding.ASCII.GetString(receivedMessage.GetBytes());
                            var text = receivedText;
                            await deviceClient.CompleteAsync(receivedMessage);
                        }
                    }
                    catch (Exception e)
                    {

                    }
                }
            }
        }

## Console log of the issue:
**Error with Microsoft.Azure.Devices.Client 1.6.1 when it reads message from queue.**
{System.ArgumentNullException: Value cannot be null.
Parameter name: array
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c.<ApplyTimeoutMessage>b__69_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BackgroundApplication6.StartupTask.<Run>d__3.MoveNext()}	System.Exception {System.ArgumentNullException}

**Error with Microsoft.Azure.Devices.Client 1.17.1 Timeout for command OpenAsync()**
{System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at BackgroundApplication6.StartupTask.<Run>d__3.MoveNext()}	System.Exception {System.TimeoutException}

**Comment by CIPop** [comment]
Thanks for reporting @LeivoSepp !

**Comment by timtay-microsoft** [comment]
@bikamani have your fixes covered this issue, too?

**Comment by abhipsaMisra** [comment]
@LeivoSepp Do you still see this issue? We have had some fixes go in with how the device client handles the `ReceiveAsync()` operations. Would you mind trying your sample with the latest SDK and see if you still hit this error?
