### ISSUE TITLE
Cannot load resources if running as UWP background task

### ISSUE THREAD

**Issue by arturl** [Azure/azure-iot-sdk-csharp#6]
When trying to get a resource string, a customer is getting:

```
{"Resource Contexts may not be created on threads that do not have a CoreWindow. (Exception from HRESULT: 0x80073B27)"}
   at Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView()
   at Microsoft.Azure.Devices.Client.Common.ResourceManagerImpl..ctor()
   at Microsoft.Azure.Devices.Client.Common.Resources..cctor()
```

This is likely caused by the fact that background tasks don't have "views". The suggestion is to call `GetForViewIndependentUse` instead of `GetForCurrentView`.

**Comment by arturl** [comment]
Fixed by https://github.com/Azure/azure-iot-sdk-csharp/commit/cf8b77f47c330892564661de5052123acdb29b38.
