### ISSUE TITLE
Exception on the file uploading with a x509 certificate device

### ISSUE THREAD

**Issue by walkerlin-msft** [Azure/azure-iot-sdk-csharp#60]
I got an exception on UploadFileToBlob method in the x509 certificate device. 
Does it support file upload feature in the x509 device?

(Microsoft.Azure.Devices.Client) Version: 1.2.3

Here is the log:
------------------------
Type of Exception : ArgumentException
Message : '' is not a valid Base64 encoded string.
Parameter name: Key
Source : Microsoft.Azure.Devices.Client
Stack Trace :    at Microsoft.Azure.Devices.Client.StringValidationHelper.EnsureBase64String(String value, String paramName)
   at Microsoft.Azure.Devices.Client.IotHubConnectionString.BuildToken(TimeSpan& ttl)
   at Microsoft.Azure.Devices.Client.IotHubConnectionString.GetPassword()
   at Microsoft.Azure.Devices.Client.IotHubConnectionString.GetAuthorizationHeader()
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<ExecuteAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<PostAsync>d__16`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.<UploadToBlobAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.SmartFactory.Devices.Client.SfDeviceClient.<UploadFileToBlob>d__16.MoveNext() in C:\Users\a-walin\Github\MOEA-SmartFactory\sfDeviceLib\CSSDK\SfDeviceClient.cs:line 110
TargetSite : Void EnsureBase64String(System.String, System.String)
---------------------
Thanks for the help.

**Comment by tameraw** [comment]
@walkerlin-msft - We had not enabled X509 with FileUpload yet. It is in our backlog to enable it. We also welcome contributions to our repo if this interests you. You can find our contribution guideline here: [https://github.com/Azure/azure-iot-sdk-csharp/blob/master/CONTRIBUTING.md](url)

**Comment by walkerlin-msft** [comment]
Got it and will keep tracking the updates.
Thanks a lot.

**Comment by sergaz-msft** [comment]
Hello @walkerlin-msft have a look at the commit [Issue #60: enabling X509 support with FileUpload](https://github.com/Azure/azure-iot-sdk-csharp/commit/64e1603b33debed05a0ed261dd3474d02ca2cbf1) and test it. The changes will be added to the master branch soon. Thanks :)!

All Best.

**Comment by walkerlin-msft** [comment]
Hi @sergaz-msft  thanks for your updates. I've tested it successfully in my codes. I'm look forward to see the release update in the master branch.
Thanks a lot.

**Comment by adamkjonesmesh** [comment]
I am trying to upload a file to IoT hub using x.509 certs but am receiving an exception every time.  The exception is "Object reference not set to the instance of an object".  The inner exception is below:

StackTrace [string]:"   at Microsoft.Azure.Devices.Client.IotHubConnectionString.Microsoft.Azure.Devices.Client.IAuthorizationProvider.GetPasswordAsync()\r\n   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Devices.Client.Transport.HttpTransportHandler.UploadToBlobAsync(String blobName, Stream source)"

I am using Microsoft.Azure.Devices.Client 1.7.2.  Is file uploading using x.509 still not supported?

**Comment by CIPop** [comment]
@adamkjonesmesh please open a separate GH issue.

**Comment by adamkjonesmesh** [comment]
Will do.
