### ISSUE TITLE
AccessViolationException in Azure.Devices.Client

### ISSUE THREAD

**Issue by maxkornev** [Azure/azure-iot-sdk-csharp#604]
Hi everybody!

I use devices client in my Protocol gateway based on [azure-iot-protocol-gateway](https://github.com/Azure/azure-iot-protocol-gateway) . And sometimes (once in few days) i get an AccessViolationException that crashes my application. Now there is no load on my app (about 1000 messages daily). Exception stacktrace:
```Exception Info: System.AccessViolationException
   at DotNetty.Common.Internal.PlatformDependent.CopyMemory(Byte[], Int32, Byte*, Int32)
   at DotNetty.Buffers.UnsafeByteBufferUtil.SetBytes(DotNetty.Buffers.AbstractByteBuffer, Byte*, Int32, System.IO.Stream, Int32)
   at DotNetty.Buffers.UnpooledUnsafeDirectByteBuffer.SetBytesAsync(Int32, System.IO.Stream, Int32, System.Threading.CancellationToken)
   at DotNetty.Buffers.AbstractByteBuffer+<WriteBytesAsync>d__181.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[DotNetty.Buffers.AbstractByteBuffer+<WriteBytesAsync>d__181, DotNetty.Buffers, Version=0.5.0.0, Culture=neutral, PublicKeyToken=bc13ca065fa06c29]](<WriteBytesAsync>d__181 ByRef)
   at DotNetty.Buffers.AbstractByteBuffer.WriteBytesAsync(System.IO.Stream, Int32, System.Threading.CancellationToken)
   at DotNetty.Buffers.AbstractByteBuffer.WriteBytesAsync(System.IO.Stream, Int32)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.Util+<ComposePublishPacketAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.Azure.Devices.Client.Transport.Mqtt.Util+<ComposePublishPacketAsync>d__13, Microsoft.Azure.Devices.Client, Version=1.18.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ComposePublishPacketAsync>d__13 ByRef)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.Util.ComposePublishPacketAsync(DotNetty.Transport.Channels.IChannelHandlerContext, Microsoft.Azure.Devices.Client.Message, DotNetty.Codecs.Mqtt.Packets.QualityOfService, System.String)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter+<SendMessageAsync>d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter+<SendMessageAsync>d__48, Microsoft.Azure.Devices.Client, Version=1.18.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SendMessageAsync>d__48 ByRef)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(DotNetty.Transport.Channels.IChannelHandlerContext, Microsoft.Azure.Devices.Client.Message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter+<WriteAsync>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter+<WriteAsync>d__28, Microsoft.Azure.Devices.Client, Version=1.18.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<WriteAsync>d__28 ByRef)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(DotNetty.Transport.Channels.IChannelHandlerContext, System.Object)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeWriteAsync0(System.Object)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext+WriteAndFlushTask.WriteAsync(DotNetty.Transport.Channels.AbstractChannelHandlerContext, System.Object)
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext+AbstractWriteTask.Run()
   at DotNetty.Common.Concurrency.AbstractEventExecutor.SafeExecute(DotNetty.Common.Concurrency.IRunnable)
   at DotNetty.Common.Concurrency.SingleThreadEventExecutor.RunAllTasks(DotNetty.Common.PreciseTimeSpan)
   at DotNetty.Common.Concurrency.SingleThreadEventExecutor.<Loop>b__26_0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean)
   at System.Threading.Tasks.Task.InternalStartNew(System.Threading.Tasks.Task, System.Delegate, System.Object, System.Threading.CancellationToken, System.Threading.Tasks.TaskScheduler, System.Threading.Tasks.TaskCreationOptions, System.Threading.Tasks.InternalTaskOptions, System.Threading.StackCrawlMark ByRef)
   at System.Threading.Tasks.TaskFactory.StartNew(System.Action, System.Threading.CancellationToken, System.Threading.Tasks.TaskCreationOptions, System.Threading.Tasks.TaskScheduler)
   at DotNetty.Common.Concurrency.SingleThreadEventExecutor.Loop()
   at DotNetty.Common.Concurrency.XThread+<>c__DisplayClass13_0.<CreateLongRunningTask>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

Framework Version: v4.0.30319
Microsoft.Azure.Devices.Client Version=1.18.0.0
Windows Server 2012R2

Did you face with this exception and could you recommend me something ?

**Comment by CIPop** [comment]
Thanks @maxkornev! We have never seen this before. What is your .NET Target Framework? (4.5.2, 4.6, etc) 

@nayato this appears to be something inside dotNetty. Since the app is using the latest version of our DeviceClient, this could be something introduced in the Mqtt codec v0.5.0.

**Comment by nayato** [comment]
@maxkornev, I'm curious why did you switch to MQTT in IoT Hub Client SDK? By default it works over AMQP which supports muxing connections and generally is more efficient and scalable in gateway scenarios.

**Comment by nayato** [comment]
@StormHub, @yjjdelete any ideas here?

**Comment by StormHub** [comment]
Could you share the channel setup?

**Comment by nayato** [comment]
@stormhub here: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs#L919

**Comment by yyjdelete** [comment]
Unable to make an reproduce for `AccessViolationException`, but able to get an data mismatch and `ExecutionEngineException`, maybe the same issue.
1. That only happen with `DotNetty.Buffers` `0.5.0` but not `0.4.8`. Neither `Microsoft.Azure.Devices.Client` nor `Microsoft.Azure.Amqp` is needed.
2. That happen for netcoreapp1.0/1.1 with mutli-thread, but not for netcoreapp2.0(newest patch version)/2.1(newest patch version)/netfx472(runtime), not sure for other versions of netfx. 
3. That may only affected `UnpooledUnsafeDirectByteBuffer`. So one workaround is
call `Environment.SetEnvironmentVariable("io.netty.noPreferDirect", "true");` before all use of DotNetty(include the static ones, it's best to call at `Main` method or static ctor of class) or use `PooledByteBufferAllocator` instead

No idea what's happened, **seems no code change between `0.4.8` and `0.5.0`.**.But maybe related to `dotnet/coreclr#17071` (not sure)

@nayato @StormHub
Test project(run with netcoreapp1.0/1.1) if someone needed.
https://gist.github.com/yyjdelete/210da6dfb09a0d588b567e5deada6847

**Comment by StormHub** [comment]
@nayato 
This line does a sync read 
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Buffers/UnsafeByteBufferUtil.cs#L222
should the allocated temp buffer be pinned before read then copy?

**Comment by maxkornev** [comment]
Thanks @nayato for reply. We decided to use MQTT just because out iot devices which connect to iot hub directly (without protocol gateway) use this MQTT protocol. We can try to switch to AMQP in protocol gateway.

**Comment by az-iot-builder-01** [comment]
@nayato, @StormHub, @yyjdelete, @maxkornev, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
