### ISSUE TITLE
How to mock  Microsoft.Azure.Devices.ServiceClient and RegistryManager

### ISSUE THREAD

**Issue by PanClifton** [Azure/azure-iot-sdk-csharp#61]
Hello
Im trying to test my service for iot hub.
When im running my test im getting following error:

Result StackTrace:	
at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyInstance(Type proxyType, List`1 proxyArguments, Type classToProxy, Object[] constructorArguments)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.<InitializeInstance>b__24_0()
   at Moq.PexProtector.Invoke(Action action)
   at Moq.Mock`1.InitializeInstance()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock.GetObject()
   at Moq.Mock.get_Object()
   at Moq.Mock`1.get_Object()
   at IoTHubServiceTest.Setup() in IoTHubServiceTest.cs:line 32
Result Message:	
Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: Microsoft.Azure.Devices.ServiceClient.
Could not find a parameterless constructor.

This is my test class.
```
 public class IoTHubServiceTest
    {
        private Mock<ServiceClient> serviceClientMock;
        private IoTHubService ioTHubService;

        /// <summary>
        /// The start up.
        /// </summary>
        [SetUp]
        public void Setup()
        {        
            this.serviceClientMock = new Mock<ServiceClient>();
            ioTHubService = new IoTHubService(serviceClientMock.Object);
        }

        [Test]
        [Category("IoTMgt")]
        public async Task TestSendCloudToDeviceMessageAsyncShouldCall()
        {
            await ioTHubService.SendCloudToDeviceMessageAsync("TestDevice", "TestMessage");

            serviceClientMock.Verify(p => p.SendAsync(It.IsAny<string>(), It.IsAny<Message>()), Times.Once());
        }

    }
``

My question is how can i mock ServiceClient?
I want to test that my method called ServiceClient.SendAsync().

Thank you.
Bartek
```

**Comment by rajeevmv** [comment]
Currently, this is not possible since the parameter-less constructor is marked as internal.

**Comment by CIPop** [comment]
The type is currently designed to use the [Factory Method pattern](https://en.wikipedia.org/wiki/Factory_method_pattern) and we would like to keep that pattern to ensure we can enhance this in the future (i.e. return a different implementation of the abstract from the factory).

@rajeevmv @PanClifton Please feel free to submit a PR.

**Comment by CIPop** [comment]
From #87 : support would also be required for RegistryManager.

**Comment by CIPop** [comment]
I've reconsidered this. Please see my answer here: https://github.com/Azure/azure-iot-sdk-csharp/issues/110#issuecomment-371614649
