### ISSUE TITLE
Microsoft.Azure.Devices.Client.ModuleClient (InternalClient) throws NullReferenceException

### ISSUE THREAD

**Issue by uffebjorklund** [Azure/azure-iot-sdk-csharp#624]
- **OS:** Docker => microsoft/dotnet:2.1.2-runtime-bionic-arm32v7
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:**  Raspberry PI3
- **SDK version used:** `<PackageReference Include="Microsoft.Azure.Devices" Version="1.17.0" />
    <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.18.0" />`

## Description of the issue:
The ModuleClient crashes randomly with the exception pasted below (in the Console log).
The communication to the Azure IoT Edge Hub sometimes work for 10-15 minutes without errors, but sooner or later we see a null ref ex when using the ModuleClient.

We also see a lot of ConnectionStatusChanges... where the report is: `Disconnected, No Network`

**Update:** We need the ability for several of our own modules to connect to the EdgeHub and send/receive messages. It seems like this is not allowed since we get some kind of race condition when we create several instances using `moduleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);` within the same AzEdge-module.

Trying to get around this issue we created a simple wrapper for the ModuleClient opening a single connection: See [gist](https://gist.github.com/uffebjorklund/6b821a05048d2fc6d97153f17e77885e).

We are about to try this atm... Can you confirm that we cant create multiple instances of the ModuleClient in a AzEdgeModule? 

## Code sample exhibiting the issue:
```
// Open connection
AmqpTransportSettings amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);            
ITransportSettings[] settings = { amqpSetting };            
moduleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
await moduleClient.OpenAsync();

// Send loop
private async Task Send(byte[] data)
{          
    var message = new Message(data);
    message.ContentEncoding = "utf-8"; 
    message.ContentType = "application/json";
    await moduleClient.SendEventAsync ("output1", message);
}
```

## Console log of the issue:
```
Unhandled Exception:
Unhandled Exception:
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__61_1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.OnReceiveEventMessageCalled(String input, Message message)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.ProcessReceivedEventMessage(AmqpMessage amqpMessage)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__61_1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.OnReceiveEventMessageCalled(String input, Message message)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.ProcessReceivedEventMessage(AmqpMessage amqpMessage)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__61_1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.InternalClient.OnReceiveEventMessageCalled(String input, Message message)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.ProcessReceivedEventMessage(AmqpMessage amqpMessage)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by prmathur-microsoft** [comment]
We don't support this scenario. Edge module is suppose to have a single identity. What is your use case? why are you trying to create multiple instances of module client ?
@varunpuranik @CIPop to chime in more

**Comment by uffebjorklund** [comment]
@prmathur-microsoft ok, thanks for clarifying/confirming our suspicions. We solved it by creating a singleton wrapping your sdk. Seems to work fine at first attempts.
To explain our use case: our software is a edge node running several modules inside of it. Among many other modules we have one for receiving data from the Az Edge Hub and another for sending to the Az Edge Hub. These modules (not Az modules) all exist within the same docker container.

Obviously not explaining every bits and pieces, but that is the main concept in this case. Usually we do not host our selves in a container next to Az Edge.

Again, thanks for confirming our findings

Regards, Uffe

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @uffebjorklund, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
