### ISSUE TITLE
WinHttpException: Client Certificate Exception despite using SAS token. (V1.18/.NET Core 2.0)

### ISSUE THREAD

**Issue by NikMeyer** [Azure/azure-iot-sdk-csharp#628]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop x64 
- **Application's .NET Target Framework :** netcoreapp2.0 
- **Device:** x64 PC 
- **SDK version used:** Microsoft.Azure.Devices.Client.1.18.0 

## Description of the issue:

The IoT device SDK tries to use a client certificate despite using an SAS connection string. Connection to the IoT Hub fails with a `System.Net.Http.WinHttpException: 'A certificate is required to complete client authentication'` exception.

The issue only occurs when using the C# IoT Device Sdk 1.18.0 (Microsoft.Azure.Devices.Client) and .NET Core 2.0.
* Same code works with SDK 1.17.0 and .NET Core 2.0
* Same code works with SDK 1.18.0 and .NET Core 2.1

## Code sample exhibiting the issue:

```
//<Project Sdk = "Microsoft.NET.Sdk" >

//<PropertyGroup>
//  <OutputType>Exe</OutputType>
//  <TargetFramework>netcoreapp2.0</TargetFramework>
//</PropertyGroup>

//<ItemGroup>
//  <PackageReference Include = "Microsoft.Azure.Devices.Client" Version="1.18.0" />
//</ItemGroup>

//</Project>

namespace IoTOpenSample
{
    using System.Text;
    using System.Threading.Tasks;
    using Microsoft.Azure.Devices.Client;
    using Microsoft.Azure.Devices.Client.Transport.Mqtt;

    public static class Program
    {
        public static void Main(string[] args)
        {
            OpenAndSendAsync().GetAwaiter().GetResult();
        }

        static async Task OpenAndSendAsync()
        {
            var mqttSetting = new MqttTransportSettings(TransportType.Mqtt_WebSocket_Only);
            ITransportSettings[] settings = { mqttSetting };

            // Using an SAS access token.
            var connectionString = "HostName=<XXX>;DeviceId=<XXX>;SharedAccessKey=<XXX>";
            var ioTHubDeviceClient = DeviceClient.CreateFromConnectionString(connectionString, settings);
            
            await ioTHubDeviceClient.OpenAsync().ConfigureAwait(false);
            // When running as .NET Core 2.0 application the line above throws an exception:
            //   "System.Net.Http.WinHttpException: 'A certificate is required to complete client authentication'"
            // The exact same code works with either:
            //   - Microsoft.Azure.Devices.Client v1.17.0 & netcoreapp2.0
            //   - netcoreapp2.1

            var message = new Message(Encoding.ASCII.GetBytes("Hello IoT"));
            await ioTHubDeviceClient.SendEventAsync(message);
        }
    }
}
```
## Console log of the issue:

```
System.Net.Http.WinHttpException (0x80072F0C): A certificate is required to complete client authentication
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IoTOpenSample.Program.<OpenAndSendAsync>d__1.MoveNext() in Program.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IoTOpenSample.Program.Main(String[] args) in Program.cs:line 26
```

**Comment by CIPop** [comment]
@timtay-microsoft this could be the result of the server presenting a mandatory certificate challenge when connecting. We were not really supporting X509 auth until 1.18.0 (all X509 tests were disabled) and we had a hack in place for ns13 which wasn't supporting certs.

**Comment by CIPop** [comment]
@NikMeyer netcoreapp2.0 is not a supported product anymore: https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/

Please switch to netcoreapp2.1.

**Comment by az-iot-builder-01** [comment]
@NikMeyer, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
