### ISSUE TITLE
Unable to send message to IoTHub when using certificate based authentication and AMQP protocol with connection pooling.

### ISSUE THREAD

**Issue by Perun85** [Azure/azure-iot-sdk-csharp#672]
**Description**
Unable to send message to IoTHub when using **certificate based authentication** and **AMQP** protocol with **connection pooling**.
When I try to send message I am getting **NullReferenceException**.

**Framework versions:** Core 2.1 and .NET 4.6.1
**Library:** Microsoft.Azure.Devices.Client **1.18.1**
**OS Version**: Windows 10 Enterprise 2016 LTSB (Version: 1607, OSBuild: 14393.2485)

**StackTrace**:
 at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DeviceSimulatorDotNet.Program.<Main>d__0.MoveNext()

**Steps to reporoduce**:
Replace Main method of Console application (Core or DotNet) with following snippet and change C# version to 7.3. Replace [yourvalue] tags with appropriate values.

```
static async Task Main(string[] args)
{
   var cert = new X509Certificate2("[yourvalue].pfx", "[yourvalue]");
   var authMethod = new DeviceAuthenticationWithX509Certificate("[yourvalue]", cert);
   var amqpTransportSettings = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
   {
            AmqpConnectionPoolSettings = new AmqpConnectionPoolSettings
            {
                MaxPoolSize = 100,
            	Pooling = true
            }
   };
   var deviceClient = DeviceClient.Create("[yourvalue]", authMethod, new ITransportSettings[] { amqpTransportSettings });
    var messageBytes = Encoding.UTF8.GetBytes("Test message");
    var message = new Message(messageBytes);

    await deviceClient.SendEventAsync(message);

  Console.ReadKey();
```
If you need any other information, please let me know.

**Comment by Perun85** [comment]
Thank you for clarification. It would be nice to get more informative exception when this scenario happens.
