### ISSUE TITLE
Twin_ServiceSetsDesiredPropertyAndDeviceReceivesItOnNextGet_MqttWs failing with parsing error

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-iot-sdk-csharp#682]
Found by our WestUS CI

```
2018-10-25T03:18:57.2187821 [Microsoft-Azure-Devices-TestLogging-TestMessage] (GetTestDeviceAsync: Using device E2E_TwinE2ETests_Sasl_d17945cf-675e-4c2f-b99f-8276db38fdde.).
2018-10-25T03:18:57.9476123 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x69f2e7f5] RECEIVED_COMPLETE, ).
2018-10-25T03:18:57.9476123 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttIotHubAdapter#28131813, ChannelReadComplete, (MqttIotHubAdapter#0)).
2018-10-25T03:18:57.9476123 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x69f2e7f5] READ, ).
2018-10-25T03:18:57.9476123 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x69f2e7f5] RECEIVED_COMPLETE, ).
2018-10-25T03:18:57.9476123 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttIotHubAdapter#28131813, ChannelReadComplete, (MqttIotHubAdapter#0)).
2018-10-25T03:18:57.9476123 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x69f2e7f5] READ, ).
2018-10-25T03:18:57.9476123 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#28131813, ChannelReadComplete, MqttIotHubAdapter#0).
2018-10-25T03:18:57.9486132 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#28131813, ChannelReadComplete, MqttIotHubAdapter#0).
2018-10-25T03:18:57.9486132 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x69f2e7f5] RECEIVED: PublishPacket[Type=PUBLISH, QualityOfService=AtMostOnce, Duplicate=False, Retain=False], 1277B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|100000000| 39 2D 62 35 63 33 62 66 66 62 61 33 36 38 22 3A |9-b5c3bffba368":|
|100000010| 20 22 39 33 61 65 34 33 37 33 2D 30 34 39 65 2D | "93ae4373-049e-|
|100000020| 34 66 66 38 2D 61 31 31 61 2D 33 63 63 39 35 34 |4ff8-a11a-3cc954|
|100000030| 35 65 61 34 35 33 22 2C 0D 0A 20 20 20 20 22 63 |5ea453",..    "c|
|100000040| 65 39 32 34 61 32 62 2D 36 63 37 31 2D 34 64 35 |e924a2b-6c71-4d5|
|100000050| 35 2D 61 33 31 32 2D 31 66 36 64 33 65 65 65 61 |5-a312-1f6d3eeea|
|100000060| 61 61 38 22 3A 20 22 35 30 64 62 61 65 36 62 2D |aa8": "50dbae6b-|
|100000070| 38 62 36 36 2D 34 30 64 33 2D 39 66 39 33 2D 31 |8b66-40d3-9f93-1|
|100000080| 65 62 64 63 38 66 64 34 39 31 65 22 2C 0D 0A 20 |ebdc8fd491e",.. |
|100000090| 20 20 20 22 30 31 36 33 32 63 30 31 2D 30 35 64 |   "01632c01-05d|
|1000000A0| 35 2D 34 66 32 31 2D 61 33 62 34 2D 61 32 39 35 |5-4f21-a3b4-a295|
|1000000B0| 64 66 62 36 63 31 37 37 22 3A 20 22 37 65 33 36 |dfb6c177": "7e36|
|1000000C0| 36 35 64 38 2D 38 61 31 63 2D 34 32 61 31 2D 39 |65d8-8a1c-42a1-9|
|1000000D0| 31 64 35 2D 35 65 66 31 39 35 38 32 37 36 31 65 |1d5-5ef19582761e|
|1000000E0| 22 2C 0D 0A 20 20 20 20 22 24 76 65 72 73 69 6F |",..    "$versio|
|1000000F0| 6E 22 3A 20 35 0D 0A 20 20 7D 0D 0A 7D 7B 0D 0A |n": 5..  }..}{..|
|100000100| 20 20 22 64 65 73 69 72 65 64 22 3A 20 7B 0D 0A |  "desired": {..|
|100000110| 20 20 20 20 22 66 38 64 39 65 30 35 39 2D 30 61 |    "f8d9e059-0a|
|100000120| 66 39 2D 34 30 33 33 2D 61 36 34 38 2D 66 37 65 |f9-4033-a648-f7e|
|100000130| 38 33 31 37 64 30 32 35 34 22 3A 20 22 34 66 35 |8317d0254": "4f5|
|100000140| 66 31 65 63 61 2D 65 33 38 65 2D 34 36 35 36 2D |f1eca-e38e-4656-|
|100000150| 38 37 30 33 2D 35 65 39 66 61 34 34 32 61 32 65 |8703-5e9fa442a2e|
|100000160| 66 22 2C 0D 0A 20 20 20 20 22 31 66 32 31 39 38 |f",..    "1f2198|
|100000170| 33 65 2D 31 64 36 30 2D 34 38 34 39 2D 39 62 30 |3e-1d60-4849-9b0|
|100000180| 66 2D 37 63 64 32 61 39 65 30 30 66 31 39 22 3A |f-7cd2a9e00f19":|
|100000190| 20 22 33 37 31 62 63 37 37 33 2D 34 33 64 65 2D | "371bc773-43de-|
|1000001A0| 34 33 31 31 2D 39 61 35 37 2D 34 66 31 36 37 62 |4311-9a57-4f167b|
|1000001B0| 63 65 66 66 62 65 22 2C 0D 0A 20 20 20 20 22 62 |ceffbe",..    "b|
|1000001C0| 39 39 66 61 31 61 31 2D 38 61 31 63 2D 34 39 31 |99fa1a1-8a1c-491|
|1000001D0| 63 2D 62 34 62 30 2D 65 33 32 33 35 38 33 39 64 |c-b4b0-e3235839d|
|1000001E0| 32 32 37 22 3A 20 22 36 30 66 33 38 37 64 31 2D |227": "60f387d1-|
|1000001F0| 35 36 65 36 2D 34 36 64 33 2D 38 32 37 36 2D 63 |56e6-46d3-8276-c|
|100000200| 63 31 33 32 34 34 32 63 65 37 35 22 2C 0D 0A 20 |c132442ce75",.. |
|100000210| 20 20 20 22 65 34 65 64 62 38 64 36 2D 33 35 32 |   "e4edb8d6-352|
|100000220| 37 2D 34 30 65 39 2D 62 63 34 64 2D 35 64 35 33 |7-40e9-bc4d-5d53|
|100000230| 30 62 31 61 35 62 36 34 22 3A 20 22 34 63 32 65 |0b1a5b64": "4c2e|
|100000240| 62 36 61 66 2D 35 38 32 34 2D 34 36 34 36 2D 61 |b6af-5824-4646-a|
|100000250| 39 38 62 2D 30 33 34 63 65 36 61 66 36 38 38 34 |98b-034ce6af6884|
|100000260| 22 2C 0D 0A 20 20 20 20 22 36 37 35 34 34 66 34 |",..    "67544f4|
|100000270| 36 2D 37 62 35 63 2D 34 65 61 37 2D 61 61 37 62 |6-7b5c-4ea7-aa7b|
|100000280| 2D 34 64 35 61 62 31 36 66 63 61 35 65 22 3A 20 |-4d5ab16fca5e": |
|100000290| 22 61 35 31 62 39 61 64 65 2D 32 65 61 31 2D 34 |"a51b9ade-2ea1-4|
|1000002A0| 30 37 36 2D 61 63 30 61 2D 63 32 66 36 62 65 38 |076-ac0a-c2f6be8|
|1000002B0| 64 33 62 63 30 22 2C 0D 0A 20 20 20 20 22 32 63 |d3bc0",..    "2c|
|1000002C0| 65 63 39 37 65 30 2D 61 66 33 63 2D 34 38 65 63 |ec97e0-af3c-48ec|
|1000002D0| 2D 38 36 37 38 2D 38 61 32 37 36 32 65 65 61 32 |-8678-8a2762eea2|
|1000002E0| 39 64 22 3A 20 22 66 66 62 38 39 63 31 34 2D 32 |9d": "ffb89c14-2|
|1000002F0| 62 31 38 2D 34 31 33 32 2D 62 66 38 30 2D 31 31 |b18-4132-bf80-11|
|100000300| 63 65 30 63 30 63 34 36 37 33 22 2C 0D 0A 20 20 |ce0c0c4673",..  |
|100000310| 20 20 22 62 66 30 31 61 34 63 31 2D 34 66 32 30 |  "bf01a4c1-4f20|
|100000320| 2D 34 31 62 65 2D 61 62 64 66 2D 34 36 30 39 66 |-41be-abdf-4609f|
|100000330| 65 38 34 31 66 31 32 22 3A 20 22 34 64 30 66 61 |e841f12": "4d0fa|
|100000340| 64 36 34 2D 31 61 36 62 2D 34 38 64 37 2D 38 33 |d64-1a6b-48d7-83|
|100000350| 30 62 2D 61 36 34 34 65 63 32 33 37 64 66 30 22 |0b-a644ec237df0"|
|100000360| 2C 0D 0A 20 20 20 20 22 36 33 35 39 61 33 35 62 |,..    "6359a35b|
|100000370| 2D 61 30 33 33 2D 34 34 63 62 2D 39 32 64 63 2D |-a033-44cb-92dc-|
|100000380| 66 36 34 30 37 63 37 61 34 31 38 37 22 3A 20 22 |f6407c7a4187": "|
|100000390| 37 64 36 33 34 32 36 30 2D 64 30 38 65 2D 34 62 |7d634260-d08e-4b|
|1000003A0| 32 62 2D 62 39 31 35 2D 61 38 30 33 33 65 31 61 |2b-b915-a8033e1a|
|1000003B0| 34 63 62 36 22 2C 0D 0A 20 20 20 20 22 33 65 61 |4cb6",..    "3ea|
|1000003C0| 32 32 36 38 35 2D 38 33 31 39 2D 34 61 30 30 2D |22685-8319-4a00-|
|1000003D0| 39 39 65 65 2D 36 39 30 39 36 31 37 64 38 35 61 |99ee-6909617d85a|
|1000003E0| 63 22 3A 20 22 37 33 35 37 37 30 38 61 2D 34 64 |c": "7357708a-4d|
|1000003F0| 61 36 2D 34 62 39 38 2D 61 61 38 30 2D 64 61 33 |a6-4b98-aa80-da3|
|100000400| 33 39 30 63 38 32 33 35 36 22 2C 0D 0A 20 20 20 |390c82356",..   |
|100000410| 20 22 35 65 63 30 61 34 38 37 2D 36 62 33 63 2D | "5ec0a487-6b3c-|
|100000420| 34 39 35 32 2D 62 64 61 39 2D 64 30 62 36 65 66 |4952-bda9-d0b6ef|
|100000430| 39 64 38 66 35 63 22 3A 20 22 34 35 65 39 38 62 |9d8f5c": "45e98b|
|100000440| 36 36 2D 35 34 33 63 2D 34 34 37 32 2D 38 61 64 |66-543c-4472-8ad|
|100000450| 31 2D 64 32 30 64 61 64 33 36 35 39 36 34 22 2C |1-d20dad365964",|
|100000460| 0D 0A 20 20 20 20 22 24 76 65 72 73 69 6F 6E 22 |..    "$version"|
|100000470| 3A 20 31 31 0D 0A 20 20 7D 2C 0D 0A 20 20 22 72 |: 11..  },..  "r|
|100000480| 65 70 6F 72 74 65 64 22 3A 20 7B 0D 0A 20 20 20 |eported": {..   |
|100000490| 20 22 64 30 65 31 36 35 64 35 2D 34 36 37 63 2D | "d0e165d5-467c-|
|1000004A0| 34 30 38 32 2D 39 38 36 36 2D 35 63 39 39 35 34 |4082-9866-5c9954|
|1000004B0| 30 35 33 39 34 66 22 3A 20 22 36 39 64 31 65 36 |05394f": "69d1e6|
|1000004C0| 37 34 2D 35 65 62 63 2D 34 64 66 61 2D 61 33 64 |74-5ebc-4dfa-a3d|
|1000004D0| 37 2D 64 35 63 65 64 31 34 36 64 62 65 32 22 2C |7-d5ced146dbe2",|
|1000004E0| 0D 0A 20 20 20 20 22 39 65 31 65 66 61 64 35 2D |..    "9e1efad5-|
|1000004F0| 35 66 65 36 2D 34 35 61 39 2D 39 64 39          |5fe6-45a9-9d9   |
+--------+-------------------------------------------------+----------------+, ).
2018-10-25T03:18:57.9486132 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttIotHubAdapter#28131813, ChannelRead, (MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtMostOnce, Duplicate=False, Retain=False])).
2018-10-25T03:18:57.9486132 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttIotHubAdapter#28131813, ProcessMessage, (MqttIotHubAdapter#0, PUBLISH)).
2018-10-25T03:18:57.9486132 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttIotHubAdapter#28131813, ProcessPublish, (MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtMostOnce, Duplicate=False, Retain=False])).
2018-10-25T03:18:57.9486132 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttIotHubAdapter#28131813, AcceptMessageAsync, (MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtMostOnce, Duplicate=False, Retain=False])).
2018-10-25T03:18:57.9516123 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#28131813, AcceptMessageAsync, MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtMostOnce, Duplicate=False, Retain=False]).
2018-10-25T03:18:57.9516123 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#28131813, ProcessPublish, MqttIotHubAdapter#0, PublishPacket[Type=PUBLISH, QualityOfService=AtMostOnce, Duplicate=False, Retain=False]).
2018-10-25T03:18:57.9516123 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#28131813, ProcessMessage, MqttIotHubAdapter#0, PUBLISH).
2018-10-25T03:18:57.9516123 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#28131813, ChannelRead, MqttIotHubAdapter#0).
2018-10-25T03:18:57.9516123 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x69f2e7f5] RECEIVED_COMPLETE, ).
2018-10-25T03:18:57.9516123 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttIotHubAdapter#28131813, ChannelReadComplete, (MqttIotHubAdapter#0)).
2018-10-25T03:18:57.9516123 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x69f2e7f5] READ, ).
2018-10-25T03:18:57.9516123 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#28131813, ChannelReadComplete, MqttIotHubAdapter#0).
2018-10-25T03:18:57.9546556 [Microsoft-Azure-Devices-Device-Client-ErrorMessage] (ErrorDelegatingHandler#56501440, ExecuteWithErrorHandlingAsync, Non-transient exception caught: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: ". Path '', line 1, position 14.
   at Microsoft.Azure.Devices.Client.Transport.TransportHandler.<>c__DisplayClass3_0.<HandleTimeoutCancellation>b__1(Task t) in D:\a\1\s\iothub\device\src\Transport\TransportHandler.cs:line 38
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<SendTwinGetAsync>d__80.MoveNext() in D:\a\1\s\iothub\device\src\Transport\Mqtt\MqttTransportHandler.cs:line 829
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__22`1.MoveNext() in D:\a\1\s\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 204).
2018-10-25T03:18:57.9546556 [Microsoft-Azure-Devices-Device-Client-Enter] (ErrorDelegatingHandler#56501440, ErrorDelegatingHandler.Reset, (System.Threading.Tasks.TaskCompletionSource`1[System.Int32], ProtocolRoutingDelegatingHandler#10178521)).
2018-10-25T03:18:57.9546556 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttTransportHandler#41060973, MqttTransportHandler.CloseAsync, ()).```

**Comment by jenoola** [comment]
Unable to reproduce the issue in multiple serial, parallel and stress tests. Enabling the test for master brunch

PR: #713

**Comment by jenoola** [comment]
OK, repro with PR mentioned above.

**Comment by CIPop** [comment]
I found this is more likely to happen in .NET Framework 4.7 and 4.5.1.
I didn't see any repro in netcore.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
