### ISSUE TITLE
Timeout exception

### ISSUE THREAD

**Issue by nhuurnink** [Azure/azure-iot-sdk-csharp#687]
Hi,

I experience the following exception within IoT Edge, when connecting to the IoT Hub (AMQP Tcp Only).
It happens occassionally, not every time.

```
private ModuleClient ioTHubModuleClient;

  var setting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            ITransportSettings[] settings = { setting };

            // Open a connection to the Edge runtime
            ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await ioTHubModuleClient.OpenAsync();
```

Line 71 in initialize is OpenAsync() method call in above code.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DsmrReader.ObjectToHubSender.Initialize() in /app/DsmrReader/modules/DsmrReader/ObjectToHubSender.cs:line 71
   at DsmrReader.Program.Init() in /app/DsmrReader/modules/DsmrReader/Program.cs:line 44
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at DsmrReader.Program.Main(String[] args)

```

**Comment by jenoola** [comment]
@nhuurnink can you please fill in the issue template?

- **OS, version, SKU and CPU architecture used:** <VERSION> 
- **Application's .NET Target Framework :** <NETVERSION> 
- **Device:** <DEVICETYPE> 
- **SDK version used:** <VERSION>

**Comment by nhuurnink** [comment]
OS: Linux arm32v7 (Raspbian)
.NET Target framework: netcoreapp2.0
Device: Raspberry PI  3 B+
SDK version used: 1.18.0 (Azure.Devices.Client version)

**Comment by erwindemoel** [comment]
@jenoola  Any update on this issue? We are still experiencing this problem. Our messages are running fine and after a day or so, we run into this timeout exception that crashes our iotEdge module.

**Comment by prmathur-microsoft** [comment]
Could you upgrade to our latest SDK 1.19.0 where we resolved a bunch of issues around reconnection. Let us know if you still see issues with latest.

**Comment by yzhong94** [comment]
@erwindemoel  Let us know if updating to the latest SDK solves your issues.  Thanks!

**Comment by prmathur-microsoft** [comment]
Closing this as per above. Feel free to reopen if you still see the issue.

**Comment by az-iot-builder-01** [comment]
@jenoola, @nhuurnink, @erwindemoel, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
