### ISSUE TITLE
Intermittent test failure for KillTcp and MqttWs fault injection tests

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#764]
Intermittent test failure for fault injection tests having a combination of fault type `KillTcp` and transport type `MqttWs`. Disabled them for unblocking CI.

```
Message_TcpConnectionLossReceiveRecovery_MqttWs
Message_TcpConnectionLossSendRecovery_MqttWs
Method_DeviceReceivesMethodAndResponseRecovery_MqttWs
Twin_DeviceReportedPropertiesTcpConnRecovery_MqttWs
Twin_DeviceDesiredPropertyUpdateTcpConnRecovery_MqttWs
```

Logs: 
https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=8752&view=logs
https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=8762&view=logs

**Comment by abhipsaMisra** [comment]
```
2019-01-18T22:00:16.6045705Z  2019-01-18T22:00:16.5397360 [Microsoft-Azure-Devices-TestLogging-TestMessage] (ActivateFaultInjection: Fault injection requested.).
2019-01-18T22:00:16.6046398Z  2019-01-18T22:00:16.5398145 [Microsoft-Azure-Devices-TestLogging-TestMessage] (FaultInjection: Waiting for fault injection to be active: 0ms).
2019-01-18T22:00:16.6047081Z  2019-01-18T22:00:16.5399394 [Microsoft-Azure-Devices-Device-Client-Enter] (RetryDelegatingHandler#55649057, SendTwinPatchAsync, ({
2019-01-18T22:00:16.6047646Z    "37dd86e1-fb53-4224-a992-22e85f75b35c": "196f5455-98f9-4705-afdf-c93ef387afc5"
2019-01-18T22:00:16.6047873Z  }, CancellationToken#1324048)).
2019-01-18T22:00:16.6048577Z  2019-01-18T22:00:16.5399801 [Microsoft-Azure-Devices-Device-Client-Enter] (ErrorDelegatingHandler#36744480, ExecuteWithErrorHandlingAsync, ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync).
2019-01-18T22:00:16.6049331Z  2019-01-18T22:00:16.5400416 [Microsoft-Azure-Devices-Device-Client-Enter] (MqttTransportHandler#44419457, SendEventAsync, (CancellationToken#1324048)).
2019-01-18T22:00:16.6050195Z  2019-01-18T22:00:16.5400790 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttTransportHandler#44419457, SendEventAsync, CancellationToken#1324048).
2019-01-18T22:00:16.6051856Z  2019-01-18T22:00:16.5411662 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x0554a3a0] CLOSE, ).
2019-01-18T22:00:16.6052716Z  2019-01-18T22:00:16.5412065 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#11372239, ShutdownOnError, MqttIotHubAdapter#0).
2019-01-18T22:00:16.6053725Z  2019-01-18T22:00:16.5412382 [Microsoft-Azure-Devices-Device-Client-Exit] (MqttIotHubAdapter#11372239, ChannelInactive, MqttIotHubAdapter#0).
2019-01-18T22:00:16.6054387Z  2019-01-18T22:00:16.5412664 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x0554a3a0] UNREGISTERED, ).
2019-01-18T22:00:16.6054998Z  2019-01-18T22:00:16.5413194 [DotNetty-Default-Debug] (DotNetty.Handlers.Logging.LoggingHandler, [id: 0x0554a3a0] HANDLER_REMOVED, ).
2019-01-18T22:00:16.6055834Z  2019-01-18T22:00:16.5416380 [Microsoft-Azure-Devices-Device-Client-Info] (ProtocolRoutingDelegatingHandler#8967299, WaitForTransportClosedAsync, Client disconnected.).
2019-01-18T22:00:16.6056683Z  2019-01-18T22:00:16.5416890 [Microsoft-Azure-Devices-Device-Client-Associate] (ProtocolRoutingDelegatingHandler#8967299, InnerHandler, ProtocolRoutingDelegatingHandler#8967299, MqttTransportHandler#44419457).
2019-01-18T22:00:16.6059170Z  2019-01-18T22:00:16.5419391 [Microsoft-Azure-Devices-Device-Client-Associate] (MqttTransportHandler#42098336, InnerHandler, MqttTransportHandler#42098336, (null)).
2019-01-18T22:00:16.6060077Z  2019-01-18T22:00:16.5419810 [Microsoft-Azure-Devices-Device-Client-Associate] (ProtocolRoutingDelegatingHandler#8967299, InnerHandler, ProtocolRoutingDelegatingHandler#8967299, (null)).
2019-01-18T22:00:16.6060865Z  2019-01-18T22:00:16.5421585 [Microsoft-Azure-Devices-Device-Client-Info] (RetryDelegatingHandler#55649057, HandleDisconnect, Transport disconnected: unexpected.).
2019-01-18T22:00:16.6061631Z  2019-01-18T22:00:16.5421950 [Microsoft-Azure-Devices-Device-Client-Enter] (InternalClient#48278369, OnConnectionStatusChanged, (Disconnected, Communication_Error)).
2019-01-18T22:00:16.6062473Z  2019-01-18T22:00:16.5423393 [Microsoft-Azure-Devices-TestLogging-TestMessage] (FaultInjection.ConnectionStatusChangesHandler: status=Disconnected statusChangeReason=Communication_Error count=2).
2019-01-18T22:00:16.6064307Z  2019-01-18T22:00:16.5423964 [Microsoft-Azure-Devices-Device-Client-Exit] (InternalClient#48278369, OnConnectionStatusChanged, Disconnected, Communication_Error).
2019-01-18T22:00:16.6072190Z  2019-01-18T22:00:16.5439550 [Microsoft-Azure-Devices-Device-Client-ErrorMessage] (ErrorDelegatingHandler#36744480, ExecuteWithErrorHandlingAsync, Exception caught: DotNetty.Transport.Channels.ClosedChannelException: I/O error occurred.
2019-01-18T22:00:16.6104866Z     at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendTwinRequestAsync(Message request, String rid, CancellationToken cancellationToken) in /home/vsts/work/1/s/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs:line 747
2019-01-18T22:00:16.6105531Z     at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken) in /home/vsts/work/1/s/iothub/device/src/Transport/Mqtt/MqttTransportHandler.cs:line 832
2019-01-18T22:00:16.6106118Z     at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/iothub/device/src/Transport/ErrorDelegatingHandler.cs:line 152
2019-01-18T22:00:16.6106974Z  --- End of stack trace from previous location where exception was thrown ---
2019-01-18T22:00:16.6107366Z     at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in /home/vsts/work/1/s/iothub/device/src/Transport/ErrorDelegatingHandler.cs:line 163).
2019-01-18T22:00:16.6108358Z  2019-01-18T22:00:16.5440607 [Microsoft-Azure-Devices-Device-Client-Exit] (ErrorDelegatingHandler#36744480, ExecuteWithErrorHandlingAsync, ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync).
2019-01-18T22:00:16.6109337Z  2019-01-18T22:00:16.5445852 [Microsoft-Azure-Devices-Device-Client-Exit] (RetryDelegatingHandler#55649057, SendTwinPatchAsync, {
2019-01-18T22:00:16.6109914Z    "37dd86e1-fb53-4224-a992-22e85f75b35c": "196f5455-98f9-4705-afdf-c93ef387afc5"
2019-01-18T22:00:16.6110161Z  }, CancellationToken#1324048).
2019-01-18T22:00:16.6110723Z  2019-01-18T22:00:16.5449243 [Microsoft-Azure-Devices-TestLogging-TestMessage] (FaultInjection: Disposing deviceClient 49417258).
2019-01-18T22:00:16.6110926Z 
2019-01-18T22:00:16.6111014Z 
```

**Comment by jenoola** [comment]
Seeing the same error for Twin_DeviceReportedPropertiesGracefulShutdownRecovery_MqttWs test

Logs: https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=10203&view=logs

**Comment by CIPop** [comment]
Twin_DeviceDesiredPropertyUpdateGracefulShutdownRecovery_MqttWs failed as well:
https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=23398&view=ms.vss-test-web.build-test-results-tab&runId=1130616&resultId=100126&paneView=debug

```
Test method Microsoft.Azure.Devices.E2ETests.TwinFaultInjectionTests.Twin_DeviceDesiredPropertyUpdateGracefulShutdownRecovery_MqttWs threw exception: 
System.OperationCanceledException: The operation was canceled.

Stack trace
    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.E2ETests.TestDeviceCallbackHandler.WaitForTwinCallbackAsync(CancellationToken ct) in /home/vsts/work/1/s/e2e/test/TestDeviceCallbackHandler.cs:line 112
   at Microsoft.Azure.Devices.E2ETests.TwinFaultInjectionTests.<>c__DisplayClass22_0.<<Twin_DeviceDesiredPropertyUpdateRecovery>b__1>d.MoveNext() in /home/vsts/work/1/s/e2e/test/TwinFaultInjectionTests.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.E2ETests.FaultInjection.TestErrorInjectionAsync(String devicePrefix, TestDeviceType type, TransportType transport, String faultType, String reason, Int32 delayInSec, Int32 durationInSec, Func`3 initOperation, Func`3 testOperation, Func`1 cleanupOperation) in /home/vsts/work/1/s/e2e/test/FaultInjection.cs:line 184
   at Microsoft.Azure.Devices.E2ETests.FaultInjection.TestErrorInjectionAsync(String devicePrefix, TestDeviceType type, TransportType transport, String faultType, String reason, Int32 delayInSec, Int32 durationInSec, Func`3 initOperation, Func`3 testOperation, Func`1 cleanupOperation) in /home/vsts/work/1/s/e2e/test/FaultInjection.cs:line 219
   at Microsoft.Azure.Devices.E2ETests.TwinFaultInjectionTests.Twin_DeviceDesiredPropertyUpdateRecovery(TransportType transport, String faultType, String reason, Int32 delayInSec) in /home/vsts/work/1/s/e2e/test/TwinFaultInjectionTests.cs:line 271
   at Microsoft.Azure.Devices.E2ETests.TwinFaultInjectionTests.Twin_DeviceDesiredPropertyUpdateGracefulShutdownRecovery_MqttWs() in /home/vsts/work/1/s/e2e/test/TwinFaultInjectionTests.cs:line 164
```

**Comment by abhipsaMisra** [comment]
These tests are no longer failing in our nightly builds, closing this issue.

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
