### ISSUE TITLE
DeviceClient.UpdateReportedPropertiesAsync throws exceptions possible behaviour change post 1.6.4

### ISSUE THREAD

**Issue by KiwiBryn** [Azure/azure-iot-sdk-csharp#784]
Running on embedded device, blocking us upgrading NuGet - version 1.6.4 works but 1.19 it fails with this error every time.

Windows 10 IoT Core 10.0.17763.253 ARM on RPI3

The application is a background task built with 

Microsoft.Azure.Devices.Client 1.6.4 or 1.9
NET.CoreFramework.Debug.2.2_2.2.27129
Microsoft.NETCore.UniversalWindowsPlatform 6.2.3

The error message is

IoT Hub device twin failed System.AggregateException: One or more errors occurred. (One or more errors occurred. (Exception from HRESULT: 0x80072F0C)) ---> System.AggregateException: One or more errors occurred. (Exception from HRESULT: 0x80072F0C) ---> System.Exception: Exception from HRESULT: 0x80072F0C
   at System.Net.WebSockets.WinRTWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Transport.ClientWebSocketTransport.WriteAsyncCore(TransportAsyncCallbackArgs args)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateSessionAsync(TimeSpan timeout, CancellationToken token)
   at Microsoft.Azure.Devices.Client.IotHubSingleTokenConnection.CreateSessionAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.CreateValue(TaskCompletionSource`1 tcs, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.IotHubConnection.GetSessionAsync(TimeoutHelper timeoutHelper, CancellationToken token)
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateSendingLinkAsync(String path, IotHubConnectionString connectionString, String corrId, SendingLinkType linkType, TimeSpan timeout, ProductInfo productInfo, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.CreateEventSendingLinkAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.CreateValue(TaskCompletionSource`1 tcs, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass28_0.<<SendTwinPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at devMobile.MicrosoftAzureDevicesClient.Timer1_19.StartupTask.Run(IBackgroundTaskInstance taskInstance)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Exception from HRESULT: 0x80072F0C) ---> System.Exception: Exception from HRESULT: 0x80072F0C
   at System.Net.WebSockets.WinRTWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Transport.ClientWebSocketTransport.WriteAsyncCore(TransportAsyncCallbackArgs args)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateSessionAsync(TimeSpan timeout, CancellationToken token)
   at Microsoft.Azure.Devices.Client.IotHubSingleTokenConnection.CreateSessionAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.CreateValue(TaskCompletionSource`1 tcs, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.IotHubConnection.GetSessionAsync(TimeoutHelper timeoutHelper, CancellationToken token)
   at Microsoft.Azure.Devices.Client.IotHubConnection.CreateSendingLinkAsync(String path, IotHubConnectionString connectionString, String corrId, SendingLinkType linkType, TimeSpan timeout, ProductInfo productInfo, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.CreateEventSendingLinkAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.CreateValue(TaskCompletionSource`1 tcs, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass28_0.<<SendTwinPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
---> (Inner Exception #0) System.Exception: Exception from HRESULT: 0x80072F0C
   at System.Net.WebSockets.WinRTWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Transport.ClientWebSocketTransport.WriteAsyncCore(TransportAsyncCallbackArgs args)<---
<---

https://gist.github.com/KiwiBryn/74f3eaaad7d7c9b5da2c73d52059392d

I have solution with V1.6.4 (happy) & V1.19(sad) clients which exhibit issue, PM me if you need further detail or sample code.

**Comment by KiwiBryn** [comment]
Did some further trials today

v1.6.4 client UpdateReportedPropertiesAsync works with
TransportType.Amqp;
TransportType.Amqp_Tcp_Only;
TransportType.Mqtt;
TransportType.Mqtt_Tcp_Only;
TransportType.Http1;

v1.19 client UpdateReportedPropertiesAsync works with
TransportType.Mqtt;
TransportType.Mqtt_Tcp_Only;
TransportType.Http1;

v1.29.0-preview-001 client UpdateReportedPropertiesAsync appears to exhibit similar behaviour to V1.19
 
In addition for SendEventAsync really slow (many seconds) for
TransportType.Amqp
TransportType.Amqp_Tcp_Only

@KiwiBryn 
https://blog.devmobile.co.nz

**Comment by prmathur-microsoft** [comment]
We have root caused this issue to underlying amqp library and this is where we are tracking the issue https://github.com/Azure/azure-amqp/issues/120

**Comment by jenoola** [comment]
@KiwiBryn please try to add Microsoft.Azure.Amqp 2.4.1 to your project, it should fix the issue.

**Comment by prmathur-microsoft** [comment]
We have released another version of SDK which points to Microsoft.Azure.Amqp 2.4.1. Please let us know if you still see this issue.

**Comment by az-iot-builder-01** [comment]
@KiwiBryn, @prmathur-microsoft, @jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by KiwiBryn** [comment]
Hi

MicrosoftAzure.Devices.Client doesn’t appear to work in my application post version 1.19.0.

When I get a spare evening this week I will try and track down what is breaking
