### ISSUE TITLE
gitHub Publisher solution for Azure Cloud

### ISSUE THREAD

**Issue by marru8619** [Azure/azure-iot-sdk-csharp#792]
Hello Everybody,

 

I'm new and I'm sorry if this is a wrong place to describe my problem. This is the first time that I use that.

I'm working on a connection between an OPC Ua client and Azure Cloud using the publisher solution downloaded by gitHub repository.

 

After the configuration and start the publisher and OPC client, the data starts to send to the cloude and through the a function app created ad hoc on Azure the data start to comes. Till this moment everything work good.

 

The problem occurs after about 1 hour (more or less) and sistematically repeted. The communication is lost and the following message coming out (extracted from the log):

 

2019-02-11 08:39:13.845 +01:00 [INF] Current directory is: C:\SIM_SCADA_Publisher\opcpublisher\bin\Debug\netcoreapp2.1
2019-02-11 08:39:14.168 +01:00 [INF] Log file is: testvm-publisher.log
2019-02-11 08:39:14.238 +01:00 [INF] Log level is: info
2019-02-11 08:39:14.251 +01:00 [INF] OPC Publisher V2.3.0 starting up...
2019-02-11 08:39:14.259 +01:00 [INF] OPC UA monitored item notifications with one of the following 2 status codes will not generate telemetry events:
2019-02-11 08:39:14.275 +01:00 [INF] StatusCode: BadNoCommunication (dec: 2150694912, hex: 80310000)
2019-02-11 08:39:14.278 +01:00 [INF] StatusCode: BadWaitingForInitialData (dec: 2150760448, hex: 80320000)
2019-02-11 08:39:14.297 +01:00 [INF] opcstacktracemask set to: 0x0
2019-02-11 08:39:14.316 +01:00 [INF] OperationTimeout set to 120000
2019-02-11 08:39:14.334 +01:00 [INF] OPC UA server base address: opc.tcp://testvm:62222/UA/Publisher
2019-02-11 08:39:14.342 +01:00 [INF] Security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256 with mode SignAndEncrypt added
2019-02-11 08:39:14.384 +01:00 [INF] Trusted Issuer store type is: Directory
2019-02-11 08:39:14.404 +01:00 [INF] Trusted Issuer Certificate store path is: pki/issuer
2019-02-11 08:39:14.419 +01:00 [INF] Trusted Peer Certificate store type is: Directory
2019-02-11 08:39:14.423 +01:00 [INF] Trusted Peer Certificate store path is: pki/trusted
2019-02-11 08:39:14.427 +01:00 [INF] Rejected certificate store type is: Directory
2019-02-11 08:39:14.431 +01:00 [INF] Rejected Certificate store path is: pki/rejected
2019-02-11 08:39:14.434 +01:00 [INF] Rejection of SHA1 signed certificates is disabled
2019-02-11 08:39:14.438 +01:00 [INF] Minimum certificate key size set to 1024
2019-02-11 08:39:14.456 +01:00 [INF] Application Certificate store type is: Directory
2019-02-11 08:39:14.460 +01:00 [INF] Application Certificate store path is: pki/own
2019-02-11 08:39:14.463 +01:00 [INF] Application Certificate subject name is: testvm
2019-02-11 08:39:14.616 +01:00 [INF] Application certificate with thumbprint '34FA1E177138402B170BAD19A78E98E017037044' found in the application certificate store.
2019-02-11 08:39:14.682 +01:00 [INF] Application certificate is for ApplicationUri 'urn:testvm:testvm:microsoft:', ApplicationName 'testvm' and Subject is 'testvm'
2019-02-11 08:39:14.688 +01:00 [INF] LDS(-ME) registration intervall set to 0 ms (0 means no registration)
2019-02-11 08:39:14.703 +01:00 [INF] Trusted issuer store contains 0 certs
2019-02-11 08:39:14.708 +01:00 [INF] Trusted issuer store has 0 CRLs.
2019-02-11 08:39:14.713 +01:00 [INF] Trusted peer store contains 0 certs
2019-02-11 08:39:14.720 +01:00 [INF] Trusted peer store has 0 CRLs.
2019-02-11 08:39:14.723 +01:00 [INF] Rejected certificate store contains 0 certs
2019-02-11 08:39:14.745 +01:00 [INF] There is no site configured.
2019-02-11 08:39:14.758 +01:00 [INF] Starting server on endpoint opc.tcp://testvm:62222/UA/Publisher ...
2019-02-11 08:39:17.760 +01:00 [INF] Server started.
2019-02-11 08:39:17.790 +01:00 [INF] Using default telemetry configuration.
2019-02-11 08:39:17.803 +01:00 [INF] The name of the configuration file for published nodes is: C:\SIM_SCADA_Publisher\opcpublisher\bin\Debug\netcoreapp2.1\publishednodes.json
2019-02-11 08:39:17.819 +01:00 [INF] Attemtping to load node configuration from: C:\SIM_SCADA_Publisher\opcpublisher\bin\Debug\netcoreapp2.1\publishednodes.json
2019-02-11 08:39:18.429 +01:00 [INF] Loaded 1 config file entry/entries.
2019-02-11 08:39:18.435 +01:00 [INF] There are 142 nodes to publish.
2019-02-11 08:39:18.456 +01:00 [INF] IoT Hub owner connection string not passed as argument.
2019-02-11 08:39:18.459 +01:00 [INF] IoTHub device cert store type is: X509Store
2019-02-11 08:39:18.461 +01:00 [INF] IoTHub device cert path is: My
2019-02-11 08:39:18.463 +01:00 [INF] IoT Hub owner connection string not specified. Assume device connection string already in cert store or passed in via command line option.
2019-02-11 08:39:18.470 +01:00 [INF] Attempting to read device connection string from cert store using subject name: testvm
2019-02-11 08:39:18.626 +01:00 [INF] IoTCentral mode: False
2019-02-11 08:39:20.312 +01:00 [INF] Connection status changed to 'Connected', reason 'Connection_Ok'
2019-02-11 08:39:21.522 +01:00 [INF] Message processing and hub communication configured with a send interval of 10 sec and a message buffer size of 262144 bytes.
2019-02-11 08:39:21.721 +01:00 [INF] Creating task process and batch monitored item data updates...
2019-02-11 08:39:21.777 +01:00 [INF]
2019-02-11 08:39:21.789 +01:00 [INF]
2019-02-11 08:39:21.792 +01:00 [INF] Publisher is running. Press CTRL-C to quit.
2019-02-11 08:39:26.290 +01:00 [INF] Connect and monitor session and nodes on endpoint 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1'.
2019-02-11 08:39:27.996 +01:00 [INF] Create unsecured session for endpoint URI 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1' with timeout of 10000 ms.
2019-02-11 08:39:28.134 +01:00 [INF] Session successfully created with Id ns=2;i=1777359191.
2019-02-11 08:39:28.158 +01:00 [INF] The session to endpoint 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1' has 4 entries in its namespace array:
2019-02-11 08:39:28.175 +01:00 [INF] Namespace index 0: http://opcfoundation.org/UA/
2019-02-11 08:39:28.176 +01:00 [INF] Namespace index 1: urn:TestVM:FactoryTalk Linx Gateway OPC UA Server
2019-02-11 08:39:28.178 +01:00 [INF] Namespace index 2: http://www.softing.com/OPCUA_Toolkit
2019-02-11 08:39:28.179 +01:00 [INF] Namespace index 3: http://www.rockwellautomation.com/OpcUa
2019-02-11 08:39:28.187 +01:00 [INF] The server on endpoint 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1' supports a minimal sampling interval of 0 ms.
2019-02-11 08:39:28.233 +01:00 [INF] Created subscription with id 656843538 on endpoint 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1'
2019-02-11 08:39:28.265 +01:00 [INF] Create subscription on endpoint 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1' requested OPC publishing interval is 0 ms. (revised: 0 ms)
2019-02-11 08:39:28.269 +01:00 [INF] Start monitoring items on endpoint 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1'. Currently monitoring 0 items.
2019-02-11 08:39:28.578 +01:00 [INF] Done processing unmonitored items on endpoint 'opc.tcp://testvm:4990/FactoryTalkLinxGateway1' took 305 msec. Now monitoring 142 items in subscription with id '656843538'.
2019-02-11 09:49:25.572 +01:00 [ERR] Connection status changed to 'Disconnected_Retrying', reason 'Communication_Error'
2019-02-11 09:49:25.802 +01:00 [INF] Connection status changed to 'Connected', reason 'Connection_Ok'

 

Anyway, the data continue to coming out on the function app.

 

 

Someone know How to Fix this problem?

Thank you

**Comment by az-iot-builder-01** [comment]
@marru8619, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by yzhong94** [comment]
@marru8619 What are you using for the OPC publisher?  Are you using this [publisher ]([url](https://github.com/OPCFoundation/UA-.NETStandard/blob/master/ComIOP/README.md))from Azure?  If so, please file an issue on OPCFoundation repository.  https://github.com/OPCFoundation/UA-.NETStandard  Thank you!

**Comment by marru8619** [comment]
Hi yzhong94,

I'm using the publisher solution downloaded from this gitHub repository:
https://github.com/Azure/iot-edge-opc-publisher

**Comment by marru8619** [comment]
And this morning a new Error appear:

2019-02-15 10:18:32.137 +01:00 [INF] ==========================================================================
2019-02-15 10:18:35.048 +01:00 [WRN] Session endpoint: opc.tcp://testvm:4990/FactoryTalkLinxGateway1 has Status: BadNoCommunication 'Server not responding to keep alive requests.'
2019-02-15 10:18:35.051 +01:00 [INF] Outstanding requests: 0, Defunct requests: 0
2019-02-15 10:18:35.053 +01:00 [INF] Good publish requests: 0, KeepAlive interval: 2000
2019-02-15 10:18:35.055 +01:00 [INF] SessionId: ns=2;i=1510732496
2019-02-15 10:18:35.057 +01:00 [INF] Missed KeepAlives: 1
2019-02-15 10:18:37.047 +01:00 [WRN] Session endpoint: opc.tcp://testvm:4990/FactoryTalkLinxGateway1 has Status: BadNoCommunication 'Server not responding to keep alive requests.'
2019-02-15 10:18:37.054 +01:00 [INF] Outstanding requests: 0, Defunct requests: 0
2019-02-15 10:18:37.057 +01:00 [INF] Good publish requests: 0, KeepAlive interval: 2000
2019-02-15 10:18:37.061 +01:00 [INF] SessionId: ns=2;i=1510732496
2019-02-15 10:18:37.066 +01:00 [INF] Missed KeepAlives: 2
2019-02-15 10:18:39.046 +01:00 [WRN] Session endpoint: opc.tcp://testvm:4990/FactoryTalkLinxGateway1 has Status: BadNoCommunication 'Server not responding to keep alive requests.'
2019-02-15 10:18:39.049 +01:00 [INF] Outstanding requests: 0, Defunct requests: 0
2019-02-15 10:18:39.054 +01:00 [INF] Good publish requests: 0, KeepAlive interval: 2000
2019-02-15 10:18:39.059 +01:00 [INF] SessionId: ns=2;i=1510732496
2019-02-15 10:18:39.061 +01:00 [INF] Missed KeepAlives: 3
**2019-02-15 10:18:39.570 +01:00 [ERR] Exception
Opc.Ua.ServiceResultException: BadSessionIdInvalid
   at Opc.Ua.ClientBase.ValidateResponse(ResponseHeader header) in C:\Build\Projects\NETStandard-NuGet\src\Stack\Opc.Ua.Core\Stack\Client\ClientBase.cs:line 488
   at Opc.Ua.SessionClient.SetPublishingMode(RequestHeader requestHeader, Boolean publishingEnabled, UInt32Collection subscriptionIds, StatusCodeCollection& results, DiagnosticInfoCollection& diagnosticInfos) in C:\Build\Projects\NETStandard-NuGet\src\Stack\Opc.Ua.Core\Stack\Generated\Opc.Ua.Client.cs:line 3849
   at Opc.Ua.Client.Subscription.SetPublishingMode(Boolean enabled) in C:\Build\Projects\NETStandard-NuGet\src\SampleApplications\SDK\Opc.Ua.Client\Subscription.cs:line 1052
   at OpcPublisher.OpcSession.MonitorNodesAsync(CancellationToken ct) in C:\SIM_SCADA_Publisher\opcpublisher\OpcSession.cs:line 565
2019-02-15 10:18:41.056 +01:00 [WRN] Session endpoint: opc.tcp://testvm:4990/FactoryTalkLinxGateway1 has Status: BadNoCommunication 'Server not responding to keep alive requests.'**

Any idea?

**Comment by yzhong94** [comment]
Hi @marru8619 sorry to redirect you, but we are not experts of this OPC publisher.  Do you mind filing an issue at https://github.com/Azure/iot-edge-opc-publisher ?  Feel free to leave this issue open and reference it.

**Comment by prmathur-microsoft** [comment]
I'm going to close this as this is not C# SDK related. It can still link to this issue.
