### ISSUE TITLE
TimeoutException with Microsoft.Azure.Devices.Client in docker

### ISSUE THREAD

**Issue by bilalmalik777** [Azure/azure-iot-sdk-csharp#796]
- OS : Windows 10 pro 1809

- OS Build : 17763.292

- Docker : 18.09.1 windows container

- Microsoft.Azure.Devices.Clien : 1.7.1.0

I am facing the following issue when i try to send data to iot hub.
System.TimeoutException: Operation timeout expired.
at Microsoft.Azure.Devices.Client.DeviceClient.<>c.b__74_2(Task t)
For more detail you can see in attach file.
It was working perfectly before windows updation to the current version. Wihout docker, it is working perfectly either in debug or release mode. Please help me to solve this issue. If you need more information regarding the machine please let me know
![27d613ef-548e-474a-a02c-2f6188876b04](https://user-images.githubusercontent.com/23011613/52715670-d9731380-2fbe-11e9-9a93-6526b1645538.png)

**Comment by prmathur-microsoft** [comment]
We believe this issue is resolved as of 1.19.0 Can you please update to latest SDK and let us know if you still see this issue?

**Comment by bilalmalik777** [comment]
Hi @prmathur-microsoft  thanks for your response.
I updated the * Microsoft.Azure.Devices.Clien to 1.19.0 but still facing the same error

> Error in deviceHealth Message publishing for Equipment: VAR2 at:2/14/2019 11:39:07 AM +00:00. Error is System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<SendEventAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.InternalClient.<SendEventAsync>d__67.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.<SendEventAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TT.RPC.Services.TelemetryService.<SendHealthDataToIotHub>d__38.MoveNext() in C:\Users\TX-G1-134\source\repos\ThingTraxDevice\ThingtraxWebServiceClient\TT.Device\TT.RPC.Services\TelemetryService.cs:line 389

This error is just coming in case of docker when i run application in docker container but when i run without docker container it works perfectly

**Comment by jenoola** [comment]
Which protocol are you using? AMQP, MQTT, HTTP? With sockets, TCP only or generic? Please provide more detail about your scenario

**Comment by bilalmalik777** [comment]
@jenoola , thanks for your response. i am using MQTT protocol, it is working perfectly without docker but 
when i run the same application in docker windows container it is sending the "System.TimeoutException"

**Comment by jenoola** [comment]
@bilalmalik777 sorry for the late reply.

You mentioned that the issue appeared after win update. Have you tried to reinstall/repair docker?

What do you use as docker container image? What windows and .net version it has?

**Comment by bilalmalik777** [comment]
No worries. 
Yes, i tried couple of time to reinstall docker. We run application in Windows docker container.windows version i mention above in issue in this thread and .net version is 4.7.1(i am not sure about .net version because machine is in office and i am now in home, in office hour, machine can be accessed.  Right now here is 10 pm. Tomarrrow i will confirm .net version)

**Comment by bilalmalik777** [comment]
The .net version is 4.6.1.

**Comment by abhipsaMisra** [comment]
@bilalmalik777 Are you still seeing this issue in sending messages to IoT Hub from a docker container? Do you have your ports open to internet?

**Comment by abhipsaMisra** [comment]
Closing due to lack of activity.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @bilalmalik777, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
