### ISSUE TITLE
TaskScheduler.UnobservedTaskException being thrown from Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler

### ISSUE THREAD

**Issue by SwatantraYadav** [Azure/azure-iot-sdk-csharp#834]
- **OS, version, SKU and CPU architecture used:**Windows 10 Pro  6.3.14393 x64 

- **Application's .NET Target Framework :** net471, net472, 4.7.02053 
- **Device:** Laptop 
- **SDK version used:** Microsoft.Azure.Devices.Client -Version 1.19.0 

## Description of the issue:

We are using DeviceClient to send and receive messages. Entire code to initialize device client, send messages is enclosed within a Try-Catch block and we are disposing the client in finally. However because the library is probably not catching an exception somewhere there is an UnobservedTaskException somewhere. 

This is how I am able to catch this exception:
TaskScheduler.UnobservedTaskException += (sender, eventArgs) =>
            {
                Log.Critical("An exceptiored in an unobserved Task.");
eventArgs.SetObserved();
            };
## Code sample exhibiting the issue:

Please see here: https://gist.github.com/SwatantraYadav/1fea89c6e763ec656832e67b8667c3d2

## Console log of the issue:

An exception occured in an unobserved Task.
Type: System.AggregateException
Message: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
HResult: -2146233088

---- Inner Exception #1-1 ----

Type: System.Net.Sockets.SocketException
ErrorCode: 10054
Message: An existing connection was forcibly closed by the remote host
NativeErrorCode: 10054
StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.<SubscribeAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.<WriteAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<SubscribeTwinResponsesAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<OpenAsyncInternal>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<OpenAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.<OpenAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<ExecuteWithErrorHandlingAsync>d__23`1.MoveNext()
Source: mscorlib
HResult: -2147467259

**Comment by CIPop** [comment]
Thanks for reporting @SwatantraYadav ! 
Most .NET runtimes would not care about unobserved task exceptions and so while we do want to avoid throwing unobserved exception, we don't consider this a high priority. Marking with `help wanted` - feel free to submit a PR to await and observe the result of the task causing this exception.

**Comment by SwatantraYadav** [comment]
Thanks @CIPop Thanks for the response. To move forward, we will ignore these exceptions. From what I understand, garbage collector's finalizer will generate these errors when a task is not observed. I assume 'observed' means it is not waited and its exception is not checked.

**Comment by timtay-microsoft** [comment]
Closing this issue since there is no reliable repro, and because the customer is fine with just ignoring these exceptions

**Comment by az-iot-builder-01** [comment]
@CIPop, @SwatantraYadav, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ramondeklein** [comment]
We also encountered this issue with v1.33.1. It returns an `AggregateException` holding an `Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException` with the text "*MQTT channel open failed*". The stack-trace looks like this:
```
  Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: MQTT channel open failed.
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<>c__DisplayClass100_0.<<CreateChannelFactory>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass26_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass37_0.<<OpenInternalAsync>b__0>d.MoveNext()
```
It seems that the device-client code also tries to fall back to websockets when no MQTT connection can be made, because I also see the following unobserved exception:
```
 System.Net.WebSockets.WebSocketException: Unable to connect to the remote server
  => System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (cp-xpac-dev.azure-devices.net:443)
     => System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<>c__DisplayClass101_0.<<CreateWebSocketChannelFactory>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass26_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
```
I noticed that there were some updates in this code, so we'll try to upgrade to v1.36 and see what happens.
