### ISSUE TITLE
Modules with special characters such as $edgeHub and $edgeAgent cannot connect to IoTHub

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-csharp#875]
## Description of the issue:
Modules (and I presume devices) with special characters, such as $edgeHub and $edgeAgent can no longer connect to IoTHub using bits in master. 

This seems like a regression caused by https://github.com/Azure/azure-iot-sdk-csharp/commit/12478d0838b4598d795c0a26d03b4e96ae46946c

## Code sample exhibiting the issue:
string connStr = @"HostName=TestIoTHub.azure-devices.net;DeviceId=testdevice;ModuleId=$edgeHub;SharedAccessKey=***";
var mc = ModuleClient.CreateFromConnectionString(connStr);
await mc.OpenAsync();

## Console log of the issue:
System.AggregateException: One or more errors occurred. (Put token failed. status-code: 401, status-description: The specified SAS token has an invalid signature. It does not match either the primary or secondary key..) ---> Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: Put token failed. status-code: 401, status-description: The specified SAS token has an invalid signature. It does not match either the primary or secondary key..
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\AmqpTransportHandler.cs:line 162
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\ProtocolRoutingDelegatingHandler.cs:line 70
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 165
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext() in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 499
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 476
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync() in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\InternalClient.cs:line 327
   at SDKDirectRefTest1.Program.Test0() in c:\users\vpuranik.redmond\documents\visual studio 2017\Projects\SDKDirectRefTest1\SDKDirectRefTest1\Program.cs:line 19
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SDKDirectRefTest1.Program.Main(String[] args) in c:\users\vpuranik.redmond\documents\visual studio 2017\Projects\SDKDirectRefTest1\SDKDirectRefTest1\Program.cs:line 11
---> (Inner Exception #0) Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: Put token failed. status-code: 401, status-description: The specified SAS token has an invalid signature. It does not match either the primary or secondary key..
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\AmqpTransportHandler.cs:line 162
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\ProtocolRoutingDelegatingHandler.cs:line 70
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 165
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext() in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 499
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken) in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 476
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync() in E:\workspace\sdk\azure-iot-sdk-csharp\iothub\device\src\InternalClient.cs:line 327
   at SDKDirectRefTest1.Program.Test0() in c:\users\vpuranik.redmond\documents\visual studio 2017\Projects\SDKDirectRefTest1\SDKDirectRefTest1\Program.cs:line 19<---

**Comment by jenoola** [comment]
Tried with device named special$device and module special$module, no error.

When creating a module $specialmodule2 in Azure online, got an error: 
`An error prevented the module identity from being created. {"message":"BadRequest:{\r\n  \"Message\": \"ErrorCode:ArgumentInvalid;BadRequest\",\r\n  \"ExceptionMessage\": \"Tracking ID:0ba1de97cb384a8bbd466e4ab783fb28-G:5-TimeStamp:04/09/2019 20:52:38\"\r\n}"}`

The error you mention suggests that SharedAccessKey is wrong, not device/module id

**Comment by az-iot-builder-01** [comment]
@jenoola, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
