### ISSUE TITLE
A network disruption is causing endless connect-disconnect cycle

### ISSUE THREAD

**Issue by VikSab** [Azure/azure-iot-sdk-csharp#895]
Found a Bug - the issue is in the C# (.net) SDK - A network disruption is causing rapid connect-disconnect cycle

-  **OS version SKU and CPU architecture used:** Ubuntu 17.10 x64
- **Application's .NET Target Framework :** netcoreapp2.1
- **Device:** Virtual Machine (hosted in VMWare)
- **SDK version used:** 1.19.0

## Description of the issue:
A non-deterministic Network issue is causing the internal Device Client to rapidly connect-disconnect - this is using up connections for the IotHub client pool and we are reaching the MaxPool limit - our service is then not able to create any device clients - this results in the application remaining in a stuck state

This is the exception thrown

## Code sample exhibiting the issue:

we connect on receiving a device connection (we are a protocol broker) we moved to using  iothub connection pooling to reduce the Tcp connection issue that we experienced

This is the exception that we see getting thrown

Failed to initialize device client.
System.InvalidOperationException: device scope connection pool capacity reached. Consider increasing AmqpConnectionSettings.MaxPoolSize
   at Microsoft.Azure.Devices.Client.IotHubDeviceScopeConnectionPool.GetConnection(String deviceId)
   at Microsoft.Azure.Devices.Client.IotHubConnectionCache.GetConnection(IotHubConnectionString connectionString, AmqpTransportSettings amqpTransportSetting)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler..ctor(IPipelineContext context, IotHubConnectionString connectionString, AmqpTransportSettings transportSettings, Func`2 onMethodCallback, Action`1 onDesiredStatePatchReceived, Func`3 onEventReceivedCallback)
   at Microsoft.Azure.Devices.Client.Transport.TransportHandlerFactory.Create(IPipelineContext context)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.CreateNewTransportHandler()
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Dover.Devices.Rdm.InBound.MessageProcessors.RegistrationProcessor.InitializeDeviceClientAsync(Guid deviceId, ILogger log, IEnumerable`1 retryIntervals)
   at Dover.Devices.Rdm.InBound.MessageProcessors.RegistrationProcessor.RegisterDevice(RegistrationRequest request, IEnumerable`1 retryIntervals)

## Console log of the issue:
Attaching the console logs - 
[ConnectDisconnect-Logs.zip](https://github.com/Azure/azure-iot-sdk-csharp/files/3045487/ConnectDisconnect-Logs.zip)

**Comment by jenoola** [comment]
@VikSab please provide code sample or steps to repro and specify which protocol you are using (amqp, mqtt, with / without web sockets, etc.)

**Comment by VikSab** [comment]
We are using AMQP protocol - these are the repro steps we used -

The Repro steps:

1) Open the connection to Iothub - as if multiple devices are connecting to the IotHub (we are a protocol broker)
2) Use iptables to block port 5671
3) Let the system retry connecting to IotHub while blocking port
4) After few hours - the system gets into a Max Pool Connection exception

**Comment by jenoola** [comment]
hello @VikSab please try SDK version 1.20.1, the issue should be fixed there

**Comment by prmathur-microsoft** [comment]
Closing this as I have not heard from you in a while. If you still happen to see this, feel free to reopen.

**Comment by az-iot-builder-01** [comment]
@jenoola, @VikSab, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
