### ISSUE TITLE
Cant connect to Azure IoTHub behind https proxy with self-signed cert

### ISSUE THREAD

**Issue by uffebjorklund** [Azure/azure-iot-sdk-csharp#903]
## Description of the issue:
Our customers are almost always behind a https proxy. We are using `Microsoft.Azure.Devices.Client` and the `DeviceClient` to open a connection to the IoTHub.

We have no issues when connecting without a proxy or when using a http proxy. However, when using a https proxy with a CA cert on our client machine we get the error: `The remote certificate is invalid according to the validation procedure.`

Edit: Might also be worth mentioning that we have no issues communicating with other services over the http proxy using the CA cert.

## Example:
```
var proxy = new WebProxy("myproxy:4128") { BypassProxyOnLocal = false };
var transport = new Http1TransportSettings
{
    Proxy = proxy,
    ClientCertificate = myCA, // code for loading cert not included
};
var deviceAuth = new DeviceAuthenticationWithRegistrySymmetricKey("myDeviceId", "myDeviceKey");
var deviceClient = DeviceClient.Create("myHubUri", deviceAuth, new ITransportSettings[] { transport });
await deviceClient.OpenAsync();
```

## Console of exception:
```
System.Security.Authentication.AuthenticationException: TLS authentication error. ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass17_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
```

**Comment by uffebjorklund** [comment]
When using CURL it works just fine, so this makes me even more convinced that this is an issue with the DeviceClient

## Curl
```
curl --request POST --url 'https://{iothub}.azure-devices.net/devices/{device-name}/messages/events?api-version=2018-06-30' --header 'authorization: {sas-token}' --data 'Hello IoTHub' --proxy http://squid.local:4128 --cacert CA.pem -v
```

## Result (removed things such as hubname from result)
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to squid.local (127.0.0.1) port 4128 (#0)
* Establish HTTP proxy tunnel to ********.azure-devices.net:443
> CONNECT ********.azure-devices.net:443 HTTP/1.1
> Host: ********.azure-devices.net:443
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: CA.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.azure-devices.net
*  start date: May 10 20:11:27 2017 GMT
*  expire date: Apr 30 20:11:27 2019 GMT
*  subjectAltName: host "********.azure-devices.net" matched cert's "*.azure-devices.net"
*  issuer: CN=squid.local; O=squid; OU=squid; C=US
*  SSL certificate verify ok.
> POST /devices/poe_crosser/messages/events?api-version=2018-06-30 HTTP/1.1
> Host: ********.azure-devices.net
> User-Agent: curl/7.54.0
> Accept: */*
> authorization: ****************
> Content-Length: 13
> Content-Type: application/x-www-form-urlencode
```

**Comment by abhipsaMisra** [comment]
Thanks for bringing this up, we are passing along the x509 client certificate provided to the HttpClient underneath, so we would expect it to be honored. Are you able to inspect your request and see if the the certificate info is passed?

**Comment by abhipsaMisra** [comment]
@uffebjorklund Are you still blocked on this issue?

**Comment by uffebjorklund** [comment]
@abhipsaMisra The issue is still present, but since it also turned out that the only transport that worked well with this client was HTTP (AMQP/MQTT does not work well at all) our users stopped using IoT Hub. No way they could wait over a year to even get initial feedback on the issue

**Comment by uffebjorklund** [comment]
Will close since we do not have any users using IoT Hub right now

**Comment by az-iot-builder-01** [comment]
@uffebjorklund, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by abhipsaMisra** [comment]
You are correct @uffebjorklund , it is unreasonable to have to wait for such a long time to get an issue addressed, and we apologize for the delay. We had to prioritize some stabilization work with one of our supported protocols for the last couple of milestones, so we've not been able to respond to each issue as quickly as we would have liked to. We are working hard to improve in this aspect.
