### ISSUE TITLE
c# DPS X.509 deviceRegistration error for indivisual enrollment

### ISSUE THREAD

**Issue by meenaTrex** [Azure/azure-iot-sdk-csharp#907]
ProvisioningClient RegisterAsync . . . Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: AMQP transport exception ---> Microsoft.Azure.Amqp.AmqpException: {"errorCode":401002,"trackingId":"b3990321-f238-414d-96ad-dd52300db848","message":"IotHubUnauthorizedAccess","timestampUtc":"2019-04-11T06:59:58.9485669Z"}
at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.AmqpClientLink.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.CreateLinksAsync(AmqpClientConnection connection, String linkEndpoint, String productInfo)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)

**Comment by rajeevmv** [comment]
This provisioning client attempted to connect to the service without providing any credentials. 
The client must present a TPM, X.509 or SAS token credential in order to connect successfully to the service.

**Comment by prmathur-microsoft** [comment]
Can you give us more details ?

OS, version, SKU and CPU architecture used: 

Application's .NET Target Framework : 

Device: 

SDK version used:

**Comment by timtay-microsoft** [comment]
@meenaTrex are you still seeing any issues here?

**Comment by meenaTrex** [comment]
> This provisioning client attempted to connect to the service without providing any credentials.
> The client must present a TPM, X.509 or SAS token credential in order to connect successfully to the service.

This was done by providing X.509 certificate

**Comment by meenaTrex** [comment]
> @meenaTrex are you still seeing any issues here?

No it was resolved from my side..Thanq

**Comment by CIPop** [comment]
Thanks @meenaTrex . Please reopen if you are still seeing issues.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @meenaTrex, @CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
