### ISSUE TITLE
upgrade 'newtonsoft.json' to latest version

### ISSUE THREAD

**Issue by seanmcd-msft** [Azure/azure-iot-sdk-csharp#940]
I’m intermittently hitting a bug with a stack that looks like the below.  there can't be a dupe since there's only 1 item in the collection.  i also hit a variant where the same code complains about a null ref when i can't be passing a null since the parm i'm passing is local and i print it right before the call. this appears to be a newtonsoft bug that was fixed back in November.
`
2019/05/06 18:32:01.463020 :                                    ConnectionBase UpdateObject lambda exception System.ArgumentException: Can not add property Orientation to Newtonso
ft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Microsoft.Azure.Devices.Shared.TwinCollection.TrySetMemberInternal(String propertyName, Object value)
   at CallSite.Target(Closure , CallSite , TwinCollection , String , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.Azure.Devices.Shared.TwinCollection.set_Item(String propertyName, Object value)
   at EdgeModuleSamples.Common.Azure.AzureModuleBase.UpdateReportedPropertiesAsync(KeyValuePair``2 u) in D:\src\Windows-iotcore-samples\Samples\EdgeModules\Common\CS\AzureConnectio
n.cs:line 118
   at EdgeModuleSamples.Common.Azure.AzureConnectionBase.<UpdateObject>b__17_0() in D:\src\Windows-iotcore-samples\Samples\EdgeModules\Common\CS\AzureConnection.cs:line 398
`

my code looks like:

            TwinCollection delta = new TwinCollection();
            delta[u.Key] = u.Value;
            Log.WriteLine("updating twin reported properties with key = {0}, vt = {1}:{2}", u.Key, u.Value.GetType(), u.Value.ToString());
            await _moduleClient.UpdateReportedPropertiesAsync(delta).ConfigureAwait(false);

Please upgrade the SDK  from v10.x to latest(v12).

**Comment by timtay-microsoft** [comment]
In our latest release of the Shared nuget, we have upgraded the newtonsoft dependency to 12.0.3, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@seanmcd-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
