### ISSUE TITLE
MQTT connection can't recover after Edge Hub restarted

### ISSUE THREAD

**Issue by philipktlin** [Azure/azure-iot-sdk-csharp#975]
OS: raspbian ARM32
sdk version: master
Protocol: MQTT

I am from IoT Edge team and I am running IoT Edge of master branch and deploy with tempSensor and tempFilter module; which messages are expected to route from tempSensor module to tempFilter module, then upstream.

I added sdk projects directly to iotedge solution in order to add additional log messages for troubleshooting; I compiled a new version of tempFilter and manually deployed to device.

Started up with this sequence, edgehub, tempFilter, then tempSensor.    Checking tempFilter logs to ensure messages received in it.  Then run `docker rm -f edgeHub` to remove edgeHub, IoT Edge will start up edgeHub automatically.  You will see tempSensor continue to send messages from log.  However there is no new message received by tempFilter. 

Here is the log with custom messags I added:
```
[2019-06-19 22:58:17.213 INF] Received message: 171, Body: [{"machine":{"temperature":101.08030719220658,"pressure":10.12307297126404},"ambient":{"temperature":21.122682700689268,"humidity":24},"timeCreated":"2019-06-19T22:58:17.1851566Z"}]
[2019-06-19 22:58:17.213 INF] Temperature 101.080307192207 exceeds threshold 19
MqttTransportHandler.EnsureValidState called: Open
SimpleWorkQueue.Post called.
OrderedTwoPhaseWorkQueue.DoWork called.
SimpleWorkQueue.DoWork called.
MqttTransportHandler.EnsureValidState called: Open
RetryDelegatingHandler.HandleDisconnect: Transport disconnected: unexpected.
RetryDelegatingHandler.HandleDisconnect: Attempting to recover subscriptions.
MqttTransportHandler.EnsureValidState called: NotInitialized
MqttTransportHandler.TryStateTransition called: from state=NotInitialized, toState=Opening
ERROR *************** Caught by ErrorDelgatingHandler.ExecuteWithErrorHandlingAsync: DotNetty.Transport.Channels.ConnectException
ERROR *************** Network Exception Chain
RetryDelegatingHandler.TransientErrorStrategy: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
RetryDelegatingHandler.HandleDisconnect: Attempting to recover subscriptions.
MqttTransportHandler.EnsureValidState called: NotInitialized
ERROR *************** Caught by ErrorDelgatingHandler.ExecuteWithErrorHandlingAsync: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
ERROR *************** throw as original exception.
RetryDelegatingHandler.TransientErrorStrategy: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
ERROR ********** RetryDelegatingHandler.HandleDisconnect: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken) in C:\git\azure-iot-sdk-csharp\iothub\device\src\Transport\Mqtt\MqttTransportHandler.cs:line 531
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken) in C:\git\azure-iot-sdk-csharp\iothub\device\src\Transport\Mqtt\MqttTransportHandler.cs:line 171
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken) in C:\git\azure-iot-sdk-csharp\iothub\device\src\Transport\ProtocolRoutingDelegatingHandler.cs:line 70
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() in C:\git\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation) in C:\git\azure-iot-sdk-csharp\iothub\device\src\Transport\ErrorDelegatingHandler.cs:line 165
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<HandleDisconnect>b__0>d.MoveNext() in C:\git\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 553
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.HandleDisconnect() in C:\git\azure-iot-sdk-csharp\iothub\device\src\Transport\RetryDelegatingHandler.cs:line 549.
```

You can see that there are 2 exceptions thrown from transport handler; first is `DotNetty.Transport.Channels.ConnectException` and then `System.Net.Internals.SocketExceptionFactory+ExtendedSocketException`.  Since the 2nd one is not treated as transient exception, therefore it stop to recover the subscription.

Suggested solution:
You need to update TransientErrorStrategy.IsTransient method in RetryDelegatingHandler.cs to treat 2nd exception as transient exception; therefore current recovery logic should work.

**Comment by CIPop** [comment]
@philipktlin thanks for reporting! We are aware that the MQTT handler isn't properly handling all exceptions but we weren't aware of this particular one.

To scope the issue:
1. We need to ensure that _all_ exceptions thrown by the `TransportHandler`s need to be converted into known exceptions as stated in https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/devdoc/architecture.md#transporthandler point 3.
2. We need to add tests for these scenarios and potentially move away from the IoT Hub fault injection mechanism (which proves less useful given these classes of bugs).

Adding this in the overall redesign of the stack given that it's within the same class of errors that need to be fixed to move the code towards the design. (Not really AMQP related.)

/cc @prmathur-microsoft @tameraw

**Comment by philipktlin** [comment]
Thanks for your reply.  Do you have estimated completion date?

**Comment by ewertons** [comment]
According to @philipktlin , this issue has been fixed by 
https://github.com/Azure/azure-iot-sdk-csharp/pull/988
Which he has validated using IoT Edge.

**Comment by az-iot-builder-01** [comment]
@CIPop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ewertons** [comment]
Reopening it to track missing automated test for this scenario, as requested by @CIPop

**Comment by timtay-microsoft** [comment]
Seeing as the PR that contained this fix does contain a unit test, I feel comfortable closing this issue

**Comment by abhipsaMisra** [comment]
This will be addressed once we have the IoT Edge tests as a part of our release-validation gate.
