### ISSUE TITLE
Token refresher is not getting called on the faulted device, failing device reconnection

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-csharp#978]
The CBS token refresher sometimes fails to refresh the token for a faulted device (on device recovery, the CBS token refresher fails to kick in).

Test: `Method_IotHubSak_DeviceMethodTcpConnRecovery_MultipleConnections_Amqp`
Error: `DeviceNotFoundException`
The device client was unable to recover after fault. The service client tries to invoke a method on the faulted device, and instead gets DeviceNotFoundException.
```
Test method Microsoft.Azure.Devices.E2ETests.FaultInjectionPoolAmqpTests.Method_IotHubSak_DeviceMethodTcpConnRecovery_MultipleConnections_Amqp threw exception: 
Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException: Device {"Message":"{\"errorCode\":404103,\"trackingId\":\"fcdb60afabc940d894acdd14ce8ec5cf-TimeStamp:06/21/2019 01:00:09\",\"message\":\"Timed out waiting for device to connect.\",\"info\":{\"timeout\":\"00:00:00\"},\"timestampUtc\":\"2019-06-21T01:00:09.255248Z\"}","ExceptionMessage":""} not registered
```
Stack trace:
```
Stack Trace:
    at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken) in D:\a\1\s\common\src\service\HttpClientHelper.cs:line 846
   at Microsoft.Azure.Devices.HttpClientHelper.PostAsync[T,T2](Uri requestUri, T entity, TimeSpan operationTimeout, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken) in D:\a\1\s\common\src\service\HttpClientHelper.cs:line 527
   at Microsoft.Azure.Devices.E2ETests.MethodE2ETests.ServiceSendMethodAndVerifyResponse(String deviceName, String methodName, String respJson, String reqJson) in D:\a\1\s\e2e\test\MethodE2ETests.cs:line 110
   at Microsoft.Azure.Devices.E2ETests.FaultInjectionPoolAmqpTests.<>c__DisplayClass143_0.<<SendMethodAndRespondRecoveryPoolOverAmqp>b__1>d.MoveNext() in D:\a\1\s\e2e\test\MethodFaultInjectionPoolAmqpTests.cs:line 712
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.E2ETests.FaultInjectionPoolingOverAmqp.TestFaultInjectionPoolAmqpAsync(String devicePrefix, TransportType transport, Int32 poolSize, Int32 devicesCount, String faultType, String reason, Int32 delayInSec, Int32 durationInSec, Func`3 initOperation, Func`3 testOperation, Func`2 cleanupOperation, ConnectionStringAuthScope authScope) in D:\a\1\s\e2e\test\FaultInjectionPoolingOverAmqp.cs:line 104
   at Microsoft.Azure.Devices.E2ETests.FaultInjectionPoolingOverAmqp.TestFaultInjectionPoolAmqpAsync(String devicePrefix, TransportType transport, Int32 poolSize, Int32 devicesCount, String faultType, String reason, Int32 delayInSec, Int32 durationInSec, Func`3 initOperation, Func`3 testOperation, Func`2 cleanupOperation, ConnectionStringAuthScope authScope) in D:\a\1\s\e2e\test\FaultInjectionPoolingOverAmqp.cs:line 147
   at Microsoft.Azure.Devices.E2ETests.FaultInjectionPoolAmqpTests.SendMethodAndRespondRecoveryPoolOverAmqp(TestDeviceType type, TransportType transport, Int32 poolSize, Int32 devicesCount, Func`3 setDeviceReceiveMethod, String faultType, String reason, Int32 delayInSec, Int32 durationInSec, ConnectionStringAuthScope authScope) in D:\a\1\s\e2e\test\MethodFaultInjectionPoolAmqpTests.cs:line 726
   at Microsoft.Azure.Devices.E2ETests.FaultInjectionPoolAmqpTests.Method_IotHubSak_DeviceMethodTcpConnRecovery_MultipleConnections_Amqp() in D:\a\1\s\e2e\test\MethodFaultInjectionPoolAmqpTests.cs:line 400
```

**Comment by CIPop** [comment]
@abhipsaMisra do you have the client side logs / wireshark available? The above stack shows only the service client error.

**Comment by abhipsaMisra** [comment]
The build run is unfortunately no longer available: https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=24056. This means I no longer have the ETL logs.
The VSTS build log is attached.

**Comment by abhipsaMisra** [comment]
This test is no longer failing on our nightly builds, closing this issue.

**Comment by az-iot-builder-01** [comment]
@CIPop, @abhipsaMisra, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
